package com.mitian.airad.dao;

import com.mitian.airad.model.AccDivideConfig;

public interface AccDivideConfigDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    int deleteByPrimaryKey(Integer divideId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    void insert(AccDivideConfig record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    void insertSelective(AccDivideConfig record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    AccDivideConfig selectByPrimaryKey(Integer divideId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    int updateByPrimaryKeySelective(AccDivideConfig record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    int updateByPrimaryKey(AccDivideConfig record);
}
