package com.mitian.airad.dao;

import java.util.List;

import com.mitian.airad.model.AgentMemberExtend;
import com.mitian.airad.model.BssPersonalShare;

public interface BssPersonalShareDAO {
    /**
     * 根据memberId查找最新一条
     * 
     * @param bssPersonalShare
     * @return
     */
    BssPersonalShare selectByMemberID(BssPersonalShare bssPersonalShare);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    int deleteByPrimaryKey(Integer shareId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    void insert(BssPersonalShare record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    void insertSelective(BssPersonalShare record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    BssPersonalShare selectByPrimaryKey(Integer shareId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    int updateByPrimaryKeySelective(BssPersonalShare record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    int updateByPrimaryKey(BssPersonalShare record);

    List<AgentMemberExtend> findAgentList(String email);
}
