package com.mitian.airad.dao;

import java.util.List;
import java.util.Map;

import com.mitian.airad.model.BssUserInfo;

public interface BssUserInfoDAO {
    /** 用户信息列表查询 */
    List<BssUserInfo> findUserInfoList(BssUserInfo record, int fromRecord, int pageSize);

    /** 查询用户数量 */
    int findAdminUserInfoCount(BssUserInfo buInfo);

    BssUserInfo findAdminUserInfoById(Integer userId);

    // 条件查询用户数量
    int findAdminUserSize(BssUserInfo buInfo);

    List<BssUserInfo> querylistbeanbyConds(Map<String, Object> params);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table BSS_USER_INFO
     * 
     * @ibatorgenerated Wed Mar 09 14:56:24 CST 2011
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table BSS_USER_INFO
     * 
     * @ibatorgenerated Wed Mar 09 14:56:24 CST 2011
     */
    void insert(BssUserInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table BSS_USER_INFO
     * 
     * @ibatorgenerated Wed Mar 09 14:56:24 CST 2011
     */
    void insertSelective(BssUserInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table BSS_USER_INFO
     * 
     * @ibatorgenerated Wed Mar 09 14:56:24 CST 2011
     */
    BssUserInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table BSS_USER_INFO
     * 
     * @ibatorgenerated Wed Mar 09 14:56:24 CST 2011
     */
    int updateByPrimaryKeySelective(BssUserInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table BSS_USER_INFO
     * 
     * @ibatorgenerated Wed Mar 09 14:56:24 CST 2011
     */
    int updateByPrimaryKey(BssUserInfo record);
}
