package com.mitian.airad.dao;

import java.util.List;
import java.util.Map;

import com.mitian.airad.model.CoreAdvertiser;

public interface CoreAdvertiserDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    void insert(CoreAdvertiser record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int insertSelective(CoreAdvertiser record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    CoreAdvertiser selectByPrimaryKey(Integer advertiserId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int updateByPrimaryKeySelective(CoreAdvertiser record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int updateByPrimaryKey(CoreAdvertiser record);

    /**
     * 根据条件查询所有的广告商认证信息
     * 
     * @param key 条件（email,memberId,aduitStatus,排序）
     * @return
     */
    List<CoreAdvertiser> findAdvertisersAndImgByKey(Map<String, Object> key);

    /**
     * 根据条件查询总数（email,memberId,aduitStatus）
     * 
     * @return
     */
    int findCountByAdmin(Map<String, Object> key);

    /**
     * 根据会员ID修改身份证号
     * 
     * @param record
     * @return
     */
    int updateByPrimaryKeyMemberId(CoreAdvertiser record);
}
