package com.mitian.airad.dao;

import java.util.List;
import java.util.Map;

import com.mitian.airad.model.CoreAgentRelation;
import com.mitian.airad.model.CoreMemberInfo;

public interface CoreAgentRelationDAO {

    List<CoreMemberInfo> pageQueryCoreAgentRelationList(Map<String, String> params);

    List<CoreMemberInfo> pageQueryCoreAgentRelationListByTimeSlot(Map<String, String> params);

    int pageQueryCountByTimeSlot(Map params);

    int totalCount(Map params);

    /**
     * 查找代理商旗下的所有广告
     * 
     * @param record
     * @return
     */
    List<CoreAgentRelation> agentRelationList(Map<String, String> map);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AGENT_RELATION
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int deleteByPrimaryKey(Integer relationId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AGENT_RELATION
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    void insert(CoreAgentRelation record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AGENT_RELATION
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    void insertSelective(CoreAgentRelation record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AGENT_RELATION
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    CoreAgentRelation selectByPrimaryKey(Integer relationId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AGENT_RELATION
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int updateByPrimaryKeySelective(CoreAgentRelation record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AGENT_RELATION
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int updateByPrimaryKey(CoreAgentRelation record);
}
