package com.mitian.airad.dao;

import com.mitian.airad.model.CoreUserHis;

public interface CoreUserHisDAO {
    /**
     * 根据会员Id查找历史
     * 
     * @param memberId
     * @return
     */
    CoreUserHis selectByMemberId(Long memberId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_USER_HIS
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_USER_HIS
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    void insert(CoreUserHis record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_USER_HIS
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    void insertSelective(CoreUserHis record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_USER_HIS
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    CoreUserHis selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_USER_HIS
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    int updateByPrimaryKeySelective(CoreUserHis record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_USER_HIS
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    int updateByPrimaryKey(CoreUserHis record);
}
