package com.mitian.airad.dao;

import java.util.List;

import com.mitian.airad.model.DictionaryGlobalRegion;

public interface DictionaryGlobalRegionDAO {
    /**
     * 查出所有省
     * 
     * @param dictionaryGlobalRegion
     * @return
     */
    List<DictionaryGlobalRegion> findProvList(DictionaryGlobalRegion dictionaryGlobalRegion);

    /**
     * 根据省查出所有市
     * 
     * @param dictionaryGlobalRegion
     * @return
     */
    List<DictionaryGlobalRegion> findCityList(DictionaryGlobalRegion dictionaryGlobalRegion);

    /**
     * 根据市查出所有区
     * 
     * @param dictionaryGlobalRegion
     * @return
     */
    List<DictionaryGlobalRegion> findAreaList(DictionaryGlobalRegion dictionaryGlobalRegion);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * DICTIONARY_GLOBAL_REGION
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    int deleteByPrimaryKey(Short regionId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * DICTIONARY_GLOBAL_REGION
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    void insert(DictionaryGlobalRegion record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * DICTIONARY_GLOBAL_REGION
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    void insertSelective(DictionaryGlobalRegion record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * DICTIONARY_GLOBAL_REGION
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    DictionaryGlobalRegion selectByPrimaryKey(Short regionId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * DICTIONARY_GLOBAL_REGION
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    int updateByPrimaryKeySelective(DictionaryGlobalRegion record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * DICTIONARY_GLOBAL_REGION
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    int updateByPrimaryKey(DictionaryGlobalRegion record);

    Integer selectRegionIdByName(DictionaryGlobalRegion record);

    /**
     * 根据地理位置取得该地理位置在表中 的Id
     * 
     * @param RegionName
     * @return
     */
    DictionaryGlobalRegion queryDictionaryGlobalRegionByRegionName(String regionName);

    /**
     * 根据中文名称获取英文名称
     */
    String selectEnByRegionName(DictionaryGlobalRegion record);

    /**
     * 根据英文名称,类型获取 ID
     */
    Integer selectIdByEnName(DictionaryGlobalRegion record);

    Integer selectAreaId(DictionaryGlobalRegion record);
}
