package com.mitian.airad.dao;

import com.mitian.airad.model.LibImgSourceType;

public interface LibImgSourceTypeDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    int deleteByPrimaryKey(Integer imgSourceId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    void insert(LibImgSourceType record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    void insertSelective(LibImgSourceType record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    LibImgSourceType selectByPrimaryKey(Integer imgSourceId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    int updateByPrimaryKeySelective(LibImgSourceType record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    int updateByPrimaryKey(LibImgSourceType record);
}
