package com.mitian.airad.dao;

import com.mitian.airad.model.LibTaobao;

public interface LibTaobaoDAO {
    LibTaobao selectByRichId(Integer richId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    void insert(LibTaobao record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    Integer insertSelective(LibTaobao record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    LibTaobao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    int updateByPrimaryKeySelective(LibTaobao record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    int updateByPrimaryKey(LibTaobao record);
}
