package com.mitian.airad.dao;

import java.util.List;
import java.util.Map;

import com.mitian.airad.model.SdkResource;

public interface SdkResourceDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    int deleteByPrimaryKey(Integer resVId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    void insert(SdkResource record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    void insertSelective(SdkResource record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    SdkResource selectByPrimaryKey(Integer resVId);

    /**
     * 根据id查询（查询ID小于传入ID的数据）
     * 
     * @return
     */
    List<SdkResource> findSdkResourceById(Map<String, Object> record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    int updateByPrimaryKeySelective(SdkResource record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    int updateByPrimaryKeyWithBLOBs(SdkResource record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    int updateByPrimaryKeyWithoutBLOBs(SdkResource record);

    SdkResource findNewResource(String osTypes);
}
