package com.mitian.airad.dao;

import java.util.List;
import java.util.Map;

import com.mitian.airad.model.LogInfo;
import com.mitian.airad.model.StatAd;

public interface StatAdDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AD
     * 
     * @ibatorgenerated Wed Mar 09 15:41:05 CST 2011
     */
    int deleteByPrimaryKey(Integer shatAdId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AD
     * 
     * @ibatorgenerated Wed Mar 09 15:41:05 CST 2011
     */
    void insert(StatAd record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AD
     * 
     * @ibatorgenerated Wed Mar 09 15:41:05 CST 2011
     */
    void insertSelective(StatAd record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AD
     * 
     * @ibatorgenerated Wed Mar 09 15:41:05 CST 2011
     */
    StatAd selectByPrimaryKey(Integer shatAdId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AD
     * 
     * @ibatorgenerated Wed Mar 09 15:41:05 CST 2011
     */
    int updateByPrimaryKeySelective(StatAd record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AD
     * 
     * @ibatorgenerated Wed Mar 09 15:41:05 CST 2011
     */
    int updateByPrimaryKey(StatAd record);

    List<StatAd> querybyadTotalList(Map<String, String> map);

    List<StatAd> querybyadDetailList(Map<String, String> map);

    /**
     * 某个用户的广告的总展示次数
     * 
     * @param map
     * @return
     */
    StatAd queryAdShwoByMemberId(Map<String, String> map);

    /**
     * 活动统计(详细)
     */
    List<StatAd> queryCampaignDetailList(Map<String, String> map);

    /**
     * 活动统计(汇总)
     */
    List<StatAd> queryCampaignTotalList(Map<String, String> map);

    /**
     * 广告组统计(详细)
     */
    List<StatAd> querybyadGroupDetailList(Map<String, String> map);

    /**
     * 广告组统计(汇总)
     */
    List<StatAd> querybyadGroupTotalList(Map<String, String> map);

    /**
     * 所有
     */
    List<StatAd> selectadDetailList(Map<String, String> map);

    List<StatAd> selectadTotalList(Map<String, String> map);

    List<StatAd> selectadGroupDetailList(Map<String, String> map);

    List<StatAd> selectadGroupTotalList(Map<String, String> map);

    List<StatAd> selectcampaignIdDetailList(Map<String, String> map);

    List<StatAd> selectcampaignIdTotalList(Map<String, String> map);

    // /**
    // * 广告统计表
    // *
    // * @param jobTime
    // */
    // void findByTiimeAd(String jobTime, String tomorrowDay, String type) throws Exception;

    /**
     * @param record
     * @return
     */
    List<StatAd> queryCampaignbyList(StatAd record);

    /**
     * @param record
     * @return
     */
    List<StatAd> querybyadGroupList(StatAd record);

    /**
     * @param record
     * @return
     */
    List<StatAd> querybyadList(StatAd record);

    /**
     * 查找广告总数
     * 
     * @return
     */
    int statCountAdId(StatAd paramStatAd);

    /**
     * 根据条件查找日志总数
     * 
     * @return
     */
    int statCountLog(LogInfo logBean);

    /**
     * 分页查找LOG的数据
     * 
     * @param paramLogInfo
     * @return
     */
    List<LogInfo> limitLogList(LogInfo paramLogInfo);

    /**
     * 分页查找StatAd的数据
     * 
     * @param paramStatAd
     * @return
     */
    List<StatAd> limitStatAdList(StatAd paramStatAd);

    /**
     * 写入广告数据
     * 
     * @param statAd
     */
    void addJobStatAd(StatAd statAd);

}
