package com.mitian.airad.dao.impl;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.mitian.airad.dao.AdinfoViewDAO;
import com.mitian.airad.model.AdinfoView;

/**
 * AdinfoViewDAOImpl.java
 * 
 * @author baojun
 */
public class AdinfoViewDAOImpl extends SqlMapClientDaoSupport implements AdinfoViewDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADINFO_VIEW
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public AdinfoViewDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADINFO_VIEW
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public void insert(AdinfoView record) {
        getSqlMapClientTemplate().insert("ADINFO_VIEW.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADINFO_VIEW
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public void insertSelective(AdinfoView record) {
        getSqlMapClientTemplate().insert("ADINFO_VIEW.ibatorgenerated_insertSelective", record);
    }
}
