package com.mitian.airad.dao.impl;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.BssPersonalShareDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.AgentMemberExtend;
import com.mitian.airad.model.BssPersonalShare;

/**
 * BssPersonalShareDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class BssPersonalShareDAOImpl extends CustomSqlMapClientDaoSupport implements BssPersonalShareDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    public BssPersonalShareDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    public int deleteByPrimaryKey(Integer shareId) {
        BssPersonalShare key = new BssPersonalShare();
        key.setShareId(shareId);
        int rows = getSqlMapClientTemplate().delete("BSS_PERSONAL_SHARE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    public void insert(BssPersonalShare record) {
        getSqlMapClientTemplate().insert("BSS_PERSONAL_SHARE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    public void insertSelective(BssPersonalShare record) {
        getSqlMapClientTemplate().insert("BSS_PERSONAL_SHARE.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    public BssPersonalShare selectByPrimaryKey(Integer shareId) {
        BssPersonalShare key = new BssPersonalShare();
        key.setShareId(shareId);
        BssPersonalShare record =
                (BssPersonalShare) getSqlMapClientTemplate().queryForObject(
                        "BSS_PERSONAL_SHARE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    public int updateByPrimaryKeySelective(BssPersonalShare record) {
        int rows =
                getSqlMapClientTemplate().update("BSS_PERSONAL_SHARE.ibatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * BSS_PERSONAL_SHARE
     * 
     * @ibatorgenerated Wed Mar 09 14:38:56 CST 2011
     */
    public int updateByPrimaryKey(BssPersonalShare record) {
        int rows = getSqlMapClientTemplate().update("BSS_PERSONAL_SHARE.ibatorgenerated_updateByPrimaryKey", record);

        return rows;
    }

    public List<AgentMemberExtend> findAgentList(String email) {
        List<AgentMemberExtend> recordList =
                getSqlMapClientTemplate().queryForList("BSS_PERSONAL_SHARE.ibatorgenerated_selectAgentList", email);
        return recordList;
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.BssPersonalShareDAO#selectByMemberID(com.mitian.airad.model.BssPersonalShare)
     */
    // 交易中也用到了这个方法，在改时请注意通知及备份
    public BssPersonalShare selectByMemberID(BssPersonalShare bssPersonalShare) {
        BssPersonalShare bssPersonalShareFresh = new BssPersonalShare();
        bssPersonalShareFresh =
                (BssPersonalShare) getSqlMapClientTemplate().queryForObject(
                        "BSS_PERSONAL_SHARE.ibatorgenerated_selectByMemberId", bssPersonalShare);
        return bssPersonalShareFresh;
    }
}
