package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.CoreWapAdDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.CoreWapAd;

/**
 * CoreWapAdDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class CoreWapAdDAOImpl extends CustomSqlMapClientDaoSupport implements CoreWapAdDAO {
    /**
     * 根据广告id查询贫媒体信息
     */
    public CoreWapAd findByAdId(Integer adId, Long memberId) {
        CoreWapAd key = new CoreWapAd();
        key.setAdId(adId);
        key.setMemberId(memberId);
        CoreWapAd record = (CoreWapAd) getSqlMapClientTemplate().queryForObject("CORE_WAP_AD.selectByAdId", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WAP_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public CoreWapAdDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WAP_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public int deleteByPrimaryKey(Integer wapId, Long memberId) {
        CoreWapAd key = new CoreWapAd();
        key.setWapId(wapId);
        key.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().delete("CORE_WAP_AD.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WAP_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public Integer insert(CoreWapAd record, Long memberId) {
        Integer adId = 0;
        record.setMemberId(memberId);
        Object obj = getSqlMapClientTemplate().insert("CORE_WAP_AD.ibatorgenerated_insert", record);
        if (null != obj && !"".equals(obj)) {
            adId = Integer.parseInt(obj.toString());

        }
        return adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WAP_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void insertSelective(CoreWapAd record, Long memberId) {
        record.setMemberId(memberId);
        getSqlMapClientTemplate().insert("CORE_WAP_AD.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WAP_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public CoreWapAd selectByadId(Integer adId, Long memberId) {
        CoreWapAd key = new CoreWapAd();
        key.setAdId(adId);
        key.setMemberId(memberId);
        CoreWapAd record =
                (CoreWapAd) getSqlMapClientTemplate().queryForObject("CORE_WAP_AD.ibatorgenerated_selectByPrimaryKey",
                        key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WAP_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public int updateByPrimaryKeySelective(CoreWapAd record, Long memberId) {
        record.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().update("CORE_WAP_AD.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WAP_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public int updateByPrimaryKeyWithBLOBs(CoreWapAd record, Long memberId) {
        record.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().update("CORE_WAP_AD.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WAP_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public int updateByPrimaryKeyWithoutBLOBs(CoreWapAd record, Long memberId) {
        record.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().update("CORE_WAP_AD.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
