package com.mitian.airad.dao.impl;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.CoreRichAdDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.CoreRichAd;

/**
 * CoreRichAdDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class CoreRichAdDAOImpl extends CustomSqlMapClientDaoSupport implements CoreRichAdDAO {

    public CoreRichAdDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_RICH_AD
     * 
     * @ibatorgenerated Fri Feb 18 13:48:47 CST 2011
     */
    public int deleteByPrimaryKey(Integer richId, Long memberId) {
        CoreRichAd key = new CoreRichAd();
        key.setRichId(richId);
        key.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().delete("CORE_RICH_AD.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    public int deleteByPrimarySortAndAdId(Integer sort, Integer adId, Long memberId) {
        CoreRichAd key = new CoreRichAd();
        key.setAdId(adId);
        key.setSort(sort);
        key.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().delete("CORE_RICH_AD.ibatorgenerated_deleteByAdIdAndSort", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_RICH_AD
     * 
     * @ibatorgenerated Fri Feb 18 13:48:47 CST 2011
     */
    public Integer insert(CoreRichAd record, Long memberId) {
        record.setMemberId(memberId);
        return (Integer) getSqlMapClientTemplate().insert("CORE_RICH_AD.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_RICH_AD
     * 
     * @ibatorgenerated Fri Feb 18 13:48:47 CST 2011
     */
    public Integer insertSelective(CoreRichAd record, Long memberId) {
        record.setMemberId(memberId);
        return (Integer) getSqlMapClientTemplate().insert("CORE_RICH_AD.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_RICH_AD
     * 
     * @ibatorgenerated Fri Feb 18 13:48:47 CST 2011
     */
    public int updateByPrimaryKey(CoreRichAd record, Long memberId) {
        record.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().update("CORE_RICH_AD.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public Integer updateRelByPrimaryKey(CoreRichAd record, Long memberId) {
        record.setMemberId(memberId);
        return getSqlMapClientTemplate().update("CORE_RICH_AD.ibatorgenerated_updateRelByPrimaryKey", record);
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.CoreRichAdDAO#selectRichIdByAdId(java.lang.Integer）根据广告id查询富媒体信息
     */
    public CoreRichAd selectRichIdByAdId(Integer adId, Long memberId) {
        CoreRichAd key = new CoreRichAd();
        key.setRichId(adId);
        key.setMemberId(memberId);
        CoreRichAd record =
                (CoreRichAd) getSqlMapClientTemplate().queryForObject("CORE_RICH_AD.selectRichIdByAdId", key);
        return record;
    }

    /**
     *通过广告id获取富媒体
     */
    public List<CoreRichAd> findAdListByAsId(Integer adId, Long memberId) {
        List<CoreRichAd> richList = new ArrayList<CoreRichAd>();
        CoreRichAd key = new CoreRichAd();
        key.setAdId(adId);
        key.setMemberId(memberId);
        richList = getSqlMapClientTemplate().queryForList("CORE_RICH_AD.selectRichAllByAdId", key);
        return richList;
    }

}
