package com.mitian.airad.dao.impl;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.mitian.airad.dao.LibImgSourceTypeDAO;
import com.mitian.airad.model.LibImgSourceType;

/**
 * LibImgSourceTypeDAOImpl.java
 * 
 * @author baojun
 */
public class LibImgSourceTypeDAOImpl extends SqlMapClientDaoSupport implements LibImgSourceTypeDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public LibImgSourceTypeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public int deleteByPrimaryKey(Integer imgSourceId) {
        LibImgSourceType key = new LibImgSourceType();
        key.setImgSourceId(imgSourceId);
        int rows = getSqlMapClientTemplate().delete("LIB_IMG_SOURCE_TYPE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void insert(LibImgSourceType record) {
        getSqlMapClientTemplate().insert("LIB_IMG_SOURCE_TYPE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void insertSelective(LibImgSourceType record) {
        getSqlMapClientTemplate().insert("LIB_IMG_SOURCE_TYPE.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public LibImgSourceType selectByPrimaryKey(Integer imgSourceId) {
        LibImgSourceType key = new LibImgSourceType();
        key.setImgSourceId(imgSourceId);
        LibImgSourceType record =
                (LibImgSourceType) getSqlMapClientTemplate().queryForObject(
                        "LIB_IMG_SOURCE_TYPE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public int updateByPrimaryKeySelective(LibImgSourceType record) {
        int rows =
                getSqlMapClientTemplate().update("LIB_IMG_SOURCE_TYPE.ibatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_IMG_SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public int updateByPrimaryKey(LibImgSourceType record) {
        int rows = getSqlMapClientTemplate().update("LIB_IMG_SOURCE_TYPE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
