package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.RelAdSDKMappingDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.RelAdSDKMapping;
import com.mitian.airad.model.SdkResource;

/**
 * SdkResourceDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class RelAdSDKMappingDAOImpl extends CustomSqlMapClientDaoSupport implements RelAdSDKMappingDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public RelAdSDKMappingDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public int deleteByPrimaryKey(Integer resVId) {
        SdkResource key = new SdkResource();
        key.setResVId(resVId);
        int rows = getSqlMapClientTemplate().delete("REL_AD_SDK_MAPPING.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public void insert(RelAdSDKMapping record) {
        getSqlMapClientTemplate().insert("REL_AD_SDK_MAPPING.ibatorgenerated_insertSelective", record);
    }

}
