package com.mitian.airad.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.ReqAppOnlineTimeDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.ReqAppOnlineTime;

/**
 * ReqAppOnlineTimeDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class ReqAppOnlineTimeDAOImpl extends CustomSqlMapClientDaoSupport implements ReqAppOnlineTimeDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public ReqAppOnlineTimeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public int deleteByPrimaryKey(Integer appOnlineId) {
        ReqAppOnlineTime key = new ReqAppOnlineTime();
        key.setAppOnlineId(appOnlineId);
        int rows = getSqlMapClientTemplate().delete("REQ_APP_ONLINE_TIME.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public void insert(ReqAppOnlineTime record) {
        getSqlMapClientTemplate().insert("REQ_APP_ONLINE_TIME.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public void insertSelective(ReqAppOnlineTime record) {
        getSqlMapClientTemplate().insert("REQ_APP_ONLINE_TIME.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public ReqAppOnlineTime selectByPrimaryKey(Integer appOnlineId) {
        ReqAppOnlineTime key = new ReqAppOnlineTime();
        key.setAppOnlineId(appOnlineId);
        ReqAppOnlineTime record =
                (ReqAppOnlineTime) getSqlMapClientTemplate().queryForObject(
                        "REQ_APP_ONLINE_TIME.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public int updateByPrimaryKeySelective(ReqAppOnlineTime record) {
        int rows =
                getSqlMapClientTemplate().update("REQ_APP_ONLINE_TIME.ibatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public int updateByPrimaryKey(ReqAppOnlineTime record) {
        int rows = getSqlMapClientTemplate().update("REQ_APP_ONLINE_TIME.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /*
     * (non-Javadoc)
     * @see
     * com.mitian.airad.dao.ReqAppOnlineTimeDAO#selectByAdIdAndAppCodeAndSoleId(com.mitian.airad.model.ReqAppOnlineTime)
     */
    public ReqAppOnlineTime selectByAppCodeAndSoleId(ReqAppOnlineTime appTime) {
        ReqAppOnlineTime reqAppOnlineTime =
                (ReqAppOnlineTime) getSqlMapClientTemplate().queryForObject(
                        "REQ_APP_ONLINE_TIME.selectByAppCodeAndSoleId", appTime);
        return reqAppOnlineTime;
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.ReqAppOnlineTimeDAO#queryReqAppOnlineTimeByAppCodeAndTime(java.lang.String,
     * java.lang.String)
     */
    public List<ReqAppOnlineTime> queryReqAppOnlineTimeByAppCodeAndTime(String appCode, String qTime) {
        Map<String, Object> key = new HashMap<String, Object>();
        key.put("appCode", appCode);
        key.put("reqTime", qTime);
        List<ReqAppOnlineTime> result =
                getSqlMapClientTemplate().queryForList("REQ_APP_ONLINE_TIME.selectByAppCodeAndAppStartTime", key);
        return result;
    }
}
