package com.mitian.airad.dao.impl;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.StatAppViewDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.StatAppView;
import com.mitian.airad.utils.StringUtil;

/**
 * StatAppViewDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class StatAppViewDAOImpl extends CustomSqlMapClientDaoSupport implements StatAppViewDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_APP_VIEW
     * 
     * @ibatorgenerated Tue Mar 01 13:18:20 CST 2011
     */
    public StatAppViewDAOImpl() {
        super();
    }

    /**
     * 详细列表(分页)
     */
    @SuppressWarnings("unchecked")
    public List<StatAppView> findByTimeList(Map<String, String> map) {
        int pageSize = StringUtil.stringToInteger(map.get("pageSize"));
        int currentPage = StringUtil.stringToInteger(map.get("currentPage")) - 1;
        int fromRecord = pageSize * currentPage;
        map.put("fromRecord", String.valueOf(fromRecord));
        map.put("currentPage", String.valueOf(currentPage));
        List<StatAppView> list = getSqlMapClientTemplate().queryForList("STAT_APP_VIEW.findByTimeList", map);
        return list;
    }

    /**
     * 详细列表(所有)
     */
    @SuppressWarnings("unchecked")
    public List<StatAppView> findByTimeLists(Map<String, String> map) {
        List<StatAppView> list = getSqlMapClientTemplate().queryForList("STAT_APP_VIEW.findByTimeList", map);
        if (list.isEmpty()) {
            list = new ArrayList<StatAppView>();
        }
        return list;
    }

    /**
     * 查找总条数
     * 
     * @param map
     * @return
     */
    public Integer findCount(Map<String, String> map) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("STAT_APP_VIEW.selectCount", map);
        return count;
    }

    public StatAppView findByAppName(Map<String, Object> params) {
        return (StatAppView) getSqlMapClientTemplate().queryForObject("STAT_APP_VIEW.selectByAppName", params);
    }

    /**
     * 图表统计
     * 
     * @param map
     * @return
     */
    public List<StatAppView> findTotalByTime(Map<String, String> map) {
        List<StatAppView> list = getSqlMapClientTemplate().queryForList("STAT_APP_VIEW.findTotalByTime", map);
        return list;
    }

}
