package com.mitian.airad.dao.impl;

import com.mitian.airad.dao.AccDivideConfigDAO;
import com.mitian.airad.model.AccDivideConfig;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AccDivideConfigDAOImpl extends SqlMapClientDaoSupport implements AccDivideConfigDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public AccDivideConfigDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public int deleteByPrimaryKey(Integer divideId) {
        AccDivideConfig key = new AccDivideConfig();
        key.setDivideId(divideId);
        int rows = getSqlMapClientTemplate().delete("ACC_DIVIDE_CONFIG.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public void insert(AccDivideConfig record) {
        getSqlMapClientTemplate().insert("ACC_DIVIDE_CONFIG.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public void insertSelective(AccDivideConfig record) {
        getSqlMapClientTemplate().insert("ACC_DIVIDE_CONFIG.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public AccDivideConfig selectByPrimaryKey(Integer divideId) {
        AccDivideConfig key = new AccDivideConfig();
        key.setDivideId(divideId);
        AccDivideConfig record =
                (AccDivideConfig) getSqlMapClientTemplate().queryForObject(
                        "ACC_DIVIDE_CONFIG.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public int updateByPrimaryKeySelective(AccDivideConfig record) {
        int rows =
                getSqlMapClientTemplate().update("ACC_DIVIDE_CONFIG.ibatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * ACC_DIVIDE_CONFIG
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public int updateByPrimaryKey(AccDivideConfig record) {
        int rows = getSqlMapClientTemplate().update("ACC_DIVIDE_CONFIG.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
