package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.LibTaobaoDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.LibTaobao;

@Repository
public class LibTaobaoDAOImpl extends CustomSqlMapClientDaoSupport implements LibTaobaoDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    public LibTaobaoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        LibTaobao key = new LibTaobao();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("LIB_TAOBAO.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    public void insert(LibTaobao record) {
        getSqlMapClientTemplate().insert("LIB_TAOBAO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    public Integer insertSelective(LibTaobao record) {

        Integer res = (Integer) getSqlMapClientTemplate().insert("LIB_TAOBAO.ibatorgenerated_insertSelective", record);
        return res;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    public LibTaobao selectByPrimaryKey(Integer id) {
        LibTaobao key = new LibTaobao();
        key.setId(id);
        LibTaobao record =
                (LibTaobao) getSqlMapClientTemplate().queryForObject("LIB_TAOBAO.ibatorgenerated_selectByPrimaryKey",
                        key);
        return record;
    }

    public LibTaobao selectByRichId(Integer richId) {
        LibTaobao key = new LibTaobao();
        key.setRichId(richId);
        LibTaobao record =
                (LibTaobao) getSqlMapClientTemplate().queryForObject("LIB_TAOBAO.ibatorgenerated_selectByRechId", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    public int updateByPrimaryKeySelective(LibTaobao record) {
        int rows = getSqlMapClientTemplate().update("LIB_TAOBAO.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_TAOBAO
     * 
     * @ibatorgenerated Wed Jun 01 15:51:58 CST 2011
     */
    public int updateByPrimaryKey(LibTaobao record) {
        int rows = getSqlMapClientTemplate().update("LIB_TAOBAO.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
