package com.mitian.airad.dao;

import com.mitian.airad.model.AdminUserInfo;

public interface AdminUserInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_INFO
     * 
     * @ibatorgenerated Thu Mar 03 15:02:41 CST 2011
     */
    void insert(AdminUserInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_INFO
     * 
     * @ibatorgenerated Thu Mar 03 15:02:41 CST 2011
     */
    void insertSelective(AdminUserInfo record);

    /**
     * 根据用户和密码查询
     * 
     * @param name
     * @param pwd
     * @return
     */
    AdminUserInfo queryAdminUser(String name, String pwd);

}
