package com.mitian.airad.dao;

import java.util.List;
import java.util.Map;

import com.mitian.airad.model.CoreRechargeHis;

public interface CoreRechargeHisDAO {
    int updateByPrimaryKeyStatus(CoreRechargeHis record);

    /**
     * 根据代理商id 查询代理商下所有的充值记录
     * 
     * @return
     */
    List<CoreRechargeHis> selectCoreRechargeHisByAgentAdderId(Map params, int fromRecordHis, int pageSizeHis);

    int countTotal(Map params);

    /**
     * 根据会员id查询会员充值历史记录
     * 
     * @param memberId
     * @return
     */
    // List<CoreRechargeHis> selectRechargeHisByMemberId(Long memberId, int currentPage, int pageSize);

    List<CoreRechargeHis> selectRechargeHisByMemberId(Long memberId, String status);

    // 根据时间顺序查询充值历史
    List<CoreRechargeHis> queryRecHisOrderByTime(Map<String, Object> params);

    /**
     * 通过会员id查询会员充值历史记录的数量
     * 
     * @param memberId
     * @return
     */
    // public int selectCountByMemberId(Long memberId);

    /**
     * 通过订单号查询出交易记录
     * 
     * @param orderId
     * @return
     */
    CoreRechargeHis selectRechargeHisByOrderId(String serialNum);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RECHARGE_HIS
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RECHARGE_HIS
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    void insert(CoreRechargeHis record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RECHARGE_HIS
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    void insertSelective(CoreRechargeHis record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RECHARGE_HIS
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    CoreRechargeHis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RECHARGE_HIS 银联充值，数据库更新操作
     */
    int updateByPrimaryKeySelective(CoreRechargeHis record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RECHARGE_HIS
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    int updateByPrimaryKey(CoreRechargeHis record);

    int selectCountByMemberId(CoreRechargeHis coreRechargeHis);

    List<CoreRechargeHis> selectRechargeHisByMemberId(Long memberId, int currentPage, int pageSize, String flag,
            String desc);

    /**
     * 更新订单状态
     * 
     * @param serialNum
     * @param memberId
     * @return
     */
    int updateRechargeOrderStatus(CoreRechargeHis coreRechargeHis);

    /**
     * 获取充值记录
     * 
     * @param serialNum
     * @param memberId
     * @return
     */
    CoreRechargeHis getCoreRechargeHisByOrderIdAndMemberId(String serialNum, Long memberId);

    /**
     * 后台会员充值历史记录的数量
     * 
     * @author gao
     * @param memberId
     * @return
     */
    CoreRechargeHis selectCountPlatForm(String status, Long memberId);

    /**
     * 后台查看充值
     * 
     * @author gao
     * @param currentPage
     * @param pageSize
     * @param flag
     * @param desc
     * @return
     */
    List<CoreRechargeHis> queryRechargeHisListPlatForm(int currentPage, int pageSize, String flag, String desc,
            Long memberId);

    /**
     * 历史导出xml gao
     * 
     * @param status
     * @param desc
     * @return
     */
    List<CoreRechargeHis> queryReHisListPFormXml(String status, String desc);
}
