package com.mitian.airad.dao;

import com.mitian.airad.model.CoreResettingPassword;

public interface CoreResettingPasswordDAO {
    /**
     * 增加返回Id
     * 
     * @param record
     * @return
     */
    int insertReturnId(CoreResettingPassword record);

    // 账户账本邮件发送，历史记录
    int updateRestingPasswordHistory(CoreResettingPassword record);

    // 账户账本，邮件链接失效处理
    int updateTag(CoreResettingPassword record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RESETTING_PASSWORD
     * 
     * @ibatorgenerated Thu Feb 17 10:43:23 CST 2011
     */
    int deleteByPrimaryKey(Integer resettingId);

    /**
     * 根据会员Id及类型查询
     * 
     * @param memberId
     * @return
     */
    CoreResettingPassword findByMemBerId(Long memberId, String resettingType);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RESETTING_PASSWORD
     * 
     * @ibatorgenerated Thu Feb 17 10:43:23 CST 2011
     */
    void insert(CoreResettingPassword record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RESETTING_PASSWORD
     * 
     * @ibatorgenerated Thu Feb 17 10:43:23 CST 2011
     */
    void insertSelective(CoreResettingPassword record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RESETTING_PASSWORD
     * 
     * @ibatorgenerated Thu Feb 17 10:43:23 CST 2011
     */
    CoreResettingPassword selectByPrimaryKey(Integer resettingId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RESETTING_PASSWORD
     * 
     * @ibatorgenerated Thu Feb 17 10:43:23 CST 2011
     */
    int updateByPrimaryKeySelective(CoreResettingPassword record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_RESETTING_PASSWORD
     * 
     * @ibatorgenerated Thu Feb 17 10:43:23 CST 2011
     */
    int updateByPrimaryKey(CoreResettingPassword record);
}
