package com.mitian.airad.dao;

import java.util.List;

import com.mitian.airad.model.LibMarketDetail;

public interface LibMarketDetailDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    void insert(LibMarketDetail record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    void insertSelective(LibMarketDetail record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    LibMarketDetail selectByPrimaryKey(Integer id);

    List<LibMarketDetail> selectByMarketId(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    int updateByPrimaryKeySelective(LibMarketDetail record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    int updateByPrimaryKey(LibMarketDetail record);
}
