package com.mitian.airad.dao;

import java.util.List;

import com.mitian.airad.model.ReqAppOnlineTime;

public interface ReqAppOnlineTimeDAO {

    ReqAppOnlineTime selectByAppCodeAndSoleId(ReqAppOnlineTime appTime);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    int deleteByPrimaryKey(Integer appOnlineId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    void insert(ReqAppOnlineTime record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    void insertSelective(ReqAppOnlineTime record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    ReqAppOnlineTime selectByPrimaryKey(Integer appOnlineId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    int updateByPrimaryKeySelective(ReqAppOnlineTime record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_APP_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    int updateByPrimaryKey(ReqAppOnlineTime record);

    /**
     * 根据appCode time查询
     * 
     * @param appCode
     * @param qTime
     * @return
     */
    List<ReqAppOnlineTime> queryReqAppOnlineTimeByAppCodeAndTime(String appCode, String qTime);
}
