package com.mitian.airad.dao;

import com.mitian.airad.model.StatAgentView;

public interface StatAgentViewDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AGENT_VIEW
     * 
     * @ibatorgenerated Mon Mar 07 10:07:05 CST 2011
     */
    void insert(StatAgentView record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AGENT_VIEW
     * 
     * @ibatorgenerated Mon Mar 07 10:07:05 CST 2011
     */
    void insertSelective(StatAgentView record);
}
