package com.ivyinfo.addressbook.dao;

public interface AddressBook {
//	public final static String Name = "name";
//	public final static String Namepy = "namepy";
//	public final static String Alias = "alias";
//	public final static String Sex = "sex";
//	public final static String Birthday = "birthday";
//	public final static String Email = "email";
//	public final static String Companyname = "companyname";
//	public final static String Companyaddress = "companyaddress";
//	public final static String Companypostcode = "companypostcode";
//	public final static String Familyaddress = "familyaddress";
//	public final static String Familypostcode = "familypostcode";
//	public final static String Phone = "phone";
//	public final static String Remark = "remark";
//	public final static String Contactgroup = "contactgroup";
	
	public final static String Groupname = "groupname";
	public final static String Superiorgroupid = "superiorgroupid";
	public final static String Gremark = "gremark";
	
	public final static String Username = "username";
	public final static String FirstName = "firstName";
	public final static String MiddleName = "middleName";
	public final static String LastName = "lastName";
	public final static String Title = "title";
	public final static String Sex = "sex";
	public final static String GsmNoPrimary = "gsmNoPrimary";
	public final static String GsmNoAlternate = "gsmNoAlternate";
	public final static String EmailPrimary = "emailPrimary";
	public final static String EmailAlternate = "emailAlternate";
	public final static String WebPage = "webPage";
	public final static String PersonalNote = "personalNote";
	public final static String SpouseName = "spouseName";
	public final static String NickName = "nickName";
	public final static String HomeAddress = "homeAddress";
	public final static String HomeCity = "homeCity";
	public final static String HomeProvince = "homeProvince";
	public final static String HomeZip = "homeZip";
	public final static String HomeCountry = "homeCountry";
	public final static String HomePhone = "homePhone";
	public final static String HomeFaks = "homeFaks";
	public final static String WorkCompany = "workCompany";
	public final static String WorkJobTitle = "workJobTitle";
	public final static String WorkOffice = "workOffice";
	public final static String WorkProfession = "workProfession";
	public final static String WorkManagerName = "workManagerName";
	public final static String WorkAssistantName = "workAssistantName";
	public final static String WorkAddress = "workAddress";
	public final static String WorkCity = "workCity";
	public final static String WorkProvince = "workProvince";
	public final static String WorkZip = "workZip";
	public final static String WorkCountry = "workCountry";
	public final static String WorkPhone = "workPhone";
	public final static String WorkFaks = "workFaks";
	public final static String WorkDepartment = "workDepartment";
	public final static String BirthDay = "birthDay";
	public final static String BirthMonth = "birthMonth";
	public final static String AnniversaryDay = "anniversaryDay";
	public final static String AnniversaryMonth = "anniversaryMonth";
}
