package com.mitian.airad.dao;

import com.mitian.airad.model.AccIncomePay;

public interface AccIncomePayDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ACC_INCOME_PAY
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    int deleteByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ACC_INCOME_PAY
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    void insert(AccIncomePay record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ACC_INCOME_PAY
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    void insertSelective(AccIncomePay record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ACC_INCOME_PAY
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    AccIncomePay selectByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ACC_INCOME_PAY
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    int updateByPrimaryKeySelective(AccIncomePay record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ACC_INCOME_PAY
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    int updateByPrimaryKey(AccIncomePay record);

}
