package com.mitian.airad.dao;

import java.util.List;
import java.util.Map;

import com.mitian.airad.model.CoreWithdraw;
import com.mitian.airad.model.StatWithdraw;

public interface CoreWithdrawDAO {
    /**
     * 根据memberId和时间段批量跟新状态
     * 
     * @param map
     * @return
     */
    void updateByKeyAndTime(Map<String, Object> map);

    /**
     * 统计提现
     * 
     * @param map
     * @return
     */
    List<StatWithdraw> selectAllStatistic(Map<String, Object> map);

    int selectCountByMemberIdStatictis();

    List<CoreWithdraw> selectByMemberIdStatistic(Map<String, Object> map);

    int selectCountByMemberIdStatistic(Map<String, Object> map);

    /**
     * @param map
     * @return
     */
    List<CoreWithdraw> selectAll(Map<String, Object> map);

    /**
     * 通过会员id查询提现历史记录的数量
     * 
     * @param memberId
     * @return
     */
    int selectCountByMemberId(Long memberId);

    int queryCount(Long memberId);

    // 判断是否设置提款设置
    int queryTag(Long memberId);

    /**
     * 通过会员id查询历史记录根据时间排序
     */
    List<CoreWithdraw> queryListByOrderTime(Map<String, Object> params);

    /**
     * 通过会员id查询提现历史记录列表
     * 
     * @param memberId
     * @return
     */
    List<CoreWithdraw> selectByMemberId(Long memberId, int currentPage, int pageSize, String asce);

    List<CoreWithdraw> selectByMemberId(Long memberId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WITHDRAW
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    int deleteByPrimaryKey(Integer drawMoneyId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WITHDRAW
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    void insert(CoreWithdraw record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WITHDRAW
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    int insertSelective(CoreWithdraw record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WITHDRAW
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    CoreWithdraw selectByPrimaryKey(Integer drawMoneyId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WITHDRAW
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    int updateByPrimaryKeySelective(CoreWithdraw record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_WITHDRAW
     * 
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    int updateByPrimaryKey(CoreWithdraw record);

    /*************************************** for short time ****************************************************************/
    int selectCountForShortTime();

    List<CoreWithdraw> queryListForShortTime(Map<String, Object> params);
}
