package com.mitian.airad.dao;

import com.mitian.airad.model.CoreAccountInfo;

public interface CoreAccountInfoDAO {

    /**
     * 根据会员id修改会员账户信息
     * 
     * @param record
     * @return
     */
    int updateByMemberIdSelective(CoreAccountInfo record);

    /**
     * 根据会员id查询账户信息
     * 
     * @param memberId
     * @return
     */
    CoreAccountInfo selectAccountInfoByMemberId(Long memberId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_ACCOUNT_INFO
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    int deleteByPrimaryKey(Integer accId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_ACCOUNT_INFO
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    void insert(CoreAccountInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_ACCOUNT_INFO
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    int insertSelective(CoreAccountInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_ACCOUNT_INFO
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    CoreAccountInfo selectByPrimaryKey(Integer accId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_ACCOUNT_INFO
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    int updateByPrimaryKeySelective(CoreAccountInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_ACCOUNT_INFO
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    int updateByPrimaryKey(CoreAccountInfo record);
}
