package com.mitian.airad.dao;

import java.util.List;

import com.mitian.airad.model.CoreAdGroupextend;

public interface CoreAdGroupextendDAO {
    CoreAdGroupextend selectByAdGroupId(Integer adGroupId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    int deleteByPrimaryKey(Integer adGroupextendId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    void insert(CoreAdGroupextend record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    void insertSelective(CoreAdGroupextend record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    CoreAdGroupextend selectByPrimaryKey(Integer adGroupextendId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    int updateByPrimaryKeySelective(CoreAdGroupextend record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    int updateByPrimaryKeyWithBLOBs(CoreAdGroupextend record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    int updateByPrimaryKeyWithoutBLOBs(CoreAdGroupextend record);

    /**
     * @return
     */
    List<CoreAdGroupextend> findAllGroupExtend();
}
