package com.mitian.airad.dao;

import com.mitian.airad.model.SdkVersion;

public interface SdkVersionDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_VERSION
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    int deleteByPrimaryKey(Integer sdkVId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_VERSION
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    void insert(SdkVersion record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_VERSION
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    void insertSelective(SdkVersion record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_VERSION
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    SdkVersion selectByPrimaryKey(Integer sdkVId);

    /**
     * 根据版本号查询
     * 
     * @param sdkVersion
     * @return
     */
    SdkVersion selectBySdkVersion(String sdkVersion, String osType);

    /**
     * 查询最新资源版本
     * 
     * @return
     */
    SdkVersion findNewSdkVersion();

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_VERSION
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    int updateByPrimaryKeySelective(SdkVersion record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_VERSION
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    int updateByPrimaryKey(SdkVersion record);
}
