package com.mitian.airad.dao;

import java.util.List;

import com.mitian.airad.model.SysConfig;

public interface SysConfigDAO {
    /**
     * 根据配置类型查找代理商、开发者给自己转换公式
     * 
     * @param sysConfig
     * @return
     */
    SysConfig selectAgentOrAppPercent(SysConfig sysConfig);

    SysConfig findMax(String sysType);

    SysConfig findConfigByTypeAndKey(String sysType, String sysKey);

    List<SysConfig> findConfigListByType(String sysType);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SYS_CONFIG
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    int deleteByPrimaryKey(Integer sysConfigId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SYS_CONFIG
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    void insert(SysConfig record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SYS_CONFIG
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    void insertSelective(SysConfig record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SYS_CONFIG
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    SysConfig selectByPrimaryKey(Integer sysConfigId);

    int updateAdConfig(SysConfig sysConfig);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SYS_CONFIG
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    int updateByPrimaryKeySelective(SysConfig record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SYS_CONFIG
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    int updateByPrimaryKey(SysConfig record);

    /**
     * @return
     */
    public List<SysConfig> getAll();

}
