package com.mitian.airad.dao;

import java.util.List;
import java.util.Map;

import com.mitian.airad.model.CoreAd;
import com.mitian.airad.model.CoreAdGroup;

public interface CoreAdDAO {
    /**
     * 根据广告组Id查找广告(统计各个状态条数)
     * 
     * @param ad
     * @return
     */
    public CoreAd findAdListByAdGroupId(CoreAd ad);

    /**
     * 根据活动Id查找广告(统计各个状态条数)
     * 
     * @param ad
     * @return
     */
    public CoreAd findAdListByCampaignId(CoreAd ad);

    /**
     * 根据时间段统计
     * 
     * @param params
     * @param record
     * @param pageSize
     * @return
     */
    public List<CoreAd> findAdListByTimeSlot(Map params, int record, int pageSize);

    public List<CoreAd> findAdListByTimeSlot(Map<String, String> params);

    /**
     * 根据时间段统计
     * 
     * @param params
     * @param record
     * @param pageSize
     * @return
     */
    public int totalCountByTimeSlot(Map params, int record, int pageSize);

    public int totalCountByTimeSlot(Map<String, String> params);

    /**
     * 批量发布广告
     * 
     * @param listBean
     */
    void batchSendCoreAd(final List<CoreAd> listBean);

    /**
     * 批量暂停广告
     * 
     * @param listBean
     */
    void batchStopCoreAd(final List<CoreAd> listBean);

    /**
     * 根据广告组Id查询旗下所有广告
     * 
     * @param memberId
     * @return
     */
    List<CoreAd> findAllAd(CoreAdGroup coreAdGroup);

    List<CoreAd> findAdListByMemberId(Long memberId);

    List<CoreAd> findAdListByCond(Map params, int record, int pageSize);

    List<CoreAd> findAdListByCond(Map<String, String> params);

    List<Integer> findDeledAdIdList(String updTime, int record, int size);

    List<Integer> findNoDeledAdList(String updTime, int record, int size);

    int countTotal(Map<String, String> params);

    int insertAd(CoreAd record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    void insert(CoreAd record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    void insertSelective(CoreAd record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    CoreAd selectByPrimaryKey(Integer adId, Long member);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_AD
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    int updateByPrimaryKeySelective(CoreAd record);

    /**
     * @param adGroupextend
     * @return
     */
    List<CoreAd> findCoreadByGroupextend(Integer groupextendId);

    /**
     * 商铺店主广告列表查询
     * 
     * @param coreAd
     */
    public List<CoreAd> queryList4Shopper(CoreAd coreAd);

    /**
     * 获取广告展示数量总数
     * 
     * @param memberId
     */
    public Integer getTotalAdShowCount(Long memberId);

}
