package com.mitian.airad.dao;

import java.util.List;

import com.mitian.airad.model.Dictionary;

public interface DictionaryDAO {
    /**
     * 查询所属行业
     * 
     * @return
     */
    List<Dictionary> findIndustryInvolvedList();

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table DICTIONARY
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int deleteByPrimaryKey(Integer dictId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table DICTIONARY
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    void insert(Dictionary record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table DICTIONARY
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    void insertSelective(Dictionary record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table DICTIONARY
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    Dictionary selectByPrimaryKey(Integer dictId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table DICTIONARY
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table DICTIONARY
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    int updateByPrimaryKey(Dictionary record);

    /**
     * 查询所有的字典数据
     * 
     * @return
     */
    public List<Dictionary> findList();

    public List<Dictionary> getAll();

    /**
     * 根据类型查询数据字典
     * 
     * @param type
     * @return
     */
    List<Dictionary> findListByType(String type1, String type2);
}
