package com.mitian.airad.dao;

import com.mitian.airad.model.LogErrorInfo;

public interface LogErrorInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_ERROR_INFO
     * 
     * @ibatorgenerated Wed Mar 16 16:27:10 CST 2011
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_ERROR_INFO
     * 
     * @ibatorgenerated Wed Mar 16 16:27:10 CST 2011
     */
    void insert(LogErrorInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_ERROR_INFO
     * 
     * @ibatorgenerated Wed Mar 16 16:27:10 CST 2011
     */
    void insertSelective(LogErrorInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_ERROR_INFO
     * 
     * @ibatorgenerated Wed Mar 16 16:27:10 CST 2011
     */
    LogErrorInfo selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_ERROR_INFO
     * 
     * @ibatorgenerated Wed Mar 16 16:27:10 CST 2011
     */
    int updateByPrimaryKeySelective(LogErrorInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_ERROR_INFO
     * 
     * @ibatorgenerated Wed Mar 16 16:27:10 CST 2011
     */
    int updateByPrimaryKey(LogErrorInfo record);
}
