package com.mitian.airad.dao;

import com.mitian.airad.model.LogInfo;

public interface LogInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_INFO
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_INFO
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    void insert(LogInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_INFO
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    void insertSelective(LogInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_INFO
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    LogInfo selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_INFO
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    int updateByPrimaryKeySelective(LogInfo record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_INFO
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    int updateByPrimaryKey(LogInfo record);
}
