package com.mitian.airad.dao;

import java.util.List;

import com.mitian.airad.model.StatWithdrawMonth;

/**
 * 财务管理模块
 * 
 * @author 李丰光
 */
public interface StatWithdrawMonthDAO {

    /** 提现汇总列表查看 */
    List<StatWithdrawMonth> pageQueryStatWithdrawMonthDAO(StatWithdrawMonth swdm, int fromRecord, int pageSize);

    /** 查询记录数量 **/
    int queryCount(StatWithdrawMonth swdm);

    /** 汇款后标志位处理 */
    int updateByPrimaryKey(Integer drawSumId);

    /** 汇款记录数 */
    int queryWithdrawHistoryCount(StatWithdrawMonth swdm);

    /** 汇款汇总列表 */
    List<StatWithdrawMonth> pageQueryWithdrawHistoryDAO(StatWithdrawMonth swdm, int fromRecord, int pageSize);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * STAT_WITHDRAW_MONTH
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    int deleteByPrimaryKey(Integer drawSumId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * STAT_WITHDRAW_MONTH
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    void insert(StatWithdrawMonth record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * STAT_WITHDRAW_MONTH
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    void insertSelective(StatWithdrawMonth record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * STAT_WITHDRAW_MONTH
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    StatWithdrawMonth selectByPrimaryKey(Integer drawSumId);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * STAT_WITHDRAW_MONTH
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    int updateByPrimaryKeySelective(StatWithdrawMonth record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * STAT_WITHDRAW_MONTH
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    int updateByPrimaryKey(StatWithdrawMonth record);
}
