package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.AdminUserHisDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.AdminUserHis;

/**
 * AdminUserHisDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class AdminUserHisDAOImpl extends CustomSqlMapClientDaoSupport implements AdminUserHisDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_HIS
     * 
     * @ibatorgenerated Thu Mar 03 14:42:42 CST 2011
     */
    public AdminUserHisDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_HIS
     * 
     * @ibatorgenerated Thu Mar 03 14:42:42 CST 2011
     */
    public int deleteByPrimaryKey(Integer loginId) {
        AdminUserHis key = new AdminUserHis();
        key.setLoginId(loginId);
        int rows = getSqlMapClientTemplate().delete("ADMIN_USER_HIS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_HIS
     * 
     * @ibatorgenerated Thu Mar 03 14:42:42 CST 2011
     */
    public void insert(AdminUserHis record) {
        getSqlMapClientTemplate().insert("ADMIN_USER_HIS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_HIS
     * 
     * @ibatorgenerated Thu Mar 03 14:42:42 CST 2011
     */
    public void insertSelective(AdminUserHis record) {
        getSqlMapClientTemplate().insert("ADMIN_USER_HIS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_HIS
     * 
     * @ibatorgenerated Thu Mar 03 14:42:42 CST 2011
     */
    public AdminUserHis selectByPrimaryKey(Integer loginId) {
        AdminUserHis key = new AdminUserHis();
        key.setLoginId(loginId);
        AdminUserHis record =
                (AdminUserHis) getSqlMapClientTemplate().queryForObject(
                        "ADMIN_USER_HIS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_HIS
     * 
     * @ibatorgenerated Thu Mar 03 14:42:42 CST 2011
     */
    public int updateByPrimaryKeySelective(AdminUserHis record) {
        int rows =
                getSqlMapClientTemplate().update("ADMIN_USER_HIS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_HIS
     * 
     * @ibatorgenerated Thu Mar 03 14:42:42 CST 2011
     */
    public int updateByPrimaryKey(AdminUserHis record) {
        int rows = getSqlMapClientTemplate().update("ADMIN_USER_HIS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
