package com.mitian.airad.dao.impl;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.CoreAdvertiserDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.CoreAdvertiser;
import com.mitian.airad.utils.StringUtil;

/**
 * CoreAdvertiserDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class CoreAdvertiserDAOImpl extends CustomSqlMapClientDaoSupport implements CoreAdvertiserDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public CoreAdvertiserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public int deleteByPrimaryKey(Long memberId) {
        CoreAdvertiser key = new CoreAdvertiser();
        key.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().delete("CORE_ADVERTISER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void insert(CoreAdvertiser record) {
        getSqlMapClientTemplate().insert("CORE_ADVERTISER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public int insertSelective(CoreAdvertiser record) {
        Object obj = getSqlMapClientTemplate().insert("CORE_ADVERTISER.ibatorgenerated_insertSelective", record);
        int id = 0;
        if (obj != null) {
            id = Integer.parseInt(obj.toString());
        }
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public CoreAdvertiser selectByPrimaryKey(Integer advertiserId) {
        CoreAdvertiser key = new CoreAdvertiser();
        key.setAdvertiserId(advertiserId);
        CoreAdvertiser record =
                (CoreAdvertiser) getSqlMapClientTemplate().queryForObject(
                        "CORE_ADVERTISER.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public int updateByPrimaryKeySelective(CoreAdvertiser record) {
        int rows =
                getSqlMapClientTemplate().update("CORE_ADVERTISER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_ADVERTISER
     * 
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public int updateByPrimaryKey(CoreAdvertiser record) {
        int rows = getSqlMapClientTemplate().update("CORE_ADVERTISER.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.CoreAdvertiserDAO#findAdvertisersAndImgByKey(java.util.Map)
     */
    public List<CoreAdvertiser> findAdvertisersAndImgByKey(Map<String, Object> key) {
        int pageSize = StringUtil.stringToInteger(key.get("pageSize").toString());
        int currentPage = StringUtil.stringToInteger(key.get("currentPage").toString()) - 1;
        int fromRecord = pageSize * currentPage;
        List<CoreAdvertiser> result =
                getSqlMapClientTemplate().queryForList("CORE_ADVERTISER.ibatorgenerated_selectImgByPrimaryKey", key,
                        fromRecord, pageSize);
        return result;
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.CoreAdvertiserDAO#findCountByAdmin()
     */
    public int findCountByAdmin(Map<String, Object> key) {
        return (Integer) getSqlMapClientTemplate().queryForObject(
                "CORE_ADVERTISER.ibatorgenerated_selectCountImgByPrimaryKey", key);
    }

    public int updateByPrimaryKeyMemberId(CoreAdvertiser record) {
        int rows =
                getSqlMapClientTemplate().update("CORE_ADVERTISER.ibatorgenerated_updateByPrimaryKeyMemberId", record);
        return rows;
    }
}
