package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.CoreClientDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.CoreClient;

/**
 * CoreClientDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class CoreClientDAOImpl extends CustomSqlMapClientDaoSupport implements CoreClientDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_CLIENT
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    public CoreClientDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_CLIENT
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    public int deleteByPrimaryKey(Integer clientId) {
        CoreClient key = new CoreClient();
        key.setClientId(clientId);
        int rows = getSqlMapClientTemplate().delete("CORE_CLIENT.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_CLIENT
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    public void insert(CoreClient record) {
        getSqlMapClientTemplate().insert("CORE_CLIENT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_CLIENT
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    public void insertSelective(CoreClient record) {
        getSqlMapClientTemplate().insert("CORE_CLIENT.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_CLIENT
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    public CoreClient selectByPrimaryKey(Integer clientId) {
        CoreClient key = new CoreClient();
        key.setClientId(clientId);
        CoreClient record =
                (CoreClient) getSqlMapClientTemplate().queryForObject("CORE_CLIENT.ibatorgenerated_selectByPrimaryKey",
                        key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_CLIENT
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    public int updateByPrimaryKeySelective(CoreClient record) {
        int rows = getSqlMapClientTemplate().update("CORE_CLIENT.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_CLIENT
     * 
     * @ibatorgenerated Thu Feb 17 14:53:14 CST 2011
     */
    public int updateByPrimaryKey(CoreClient record) {
        int rows = getSqlMapClientTemplate().update("CORE_CLIENT.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.CoreClientDAO#selectByAllKey(com.mitian.airad.model.CoreClient)
     */
    public int selectByAllKey(CoreClient record) {
        int result =
                (Integer) getSqlMapClientTemplate()
                        .queryForObject("CORE_CLIENT.ibatorgenerated_selectByAllKey", record);
        return result;
    }
}
