package com.mitian.airad.dao.impl;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.CoreAdGroupextendDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.CoreAdGroupextend;

/**
 * CoreAdGroupextendDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class CoreAdGroupextendDAOImpl extends CustomSqlMapClientDaoSupport implements CoreAdGroupextendDAO {

    public CoreAdGroupextend selectByAdGroupId(Integer adGroupId) {
        CoreAdGroupextend key = new CoreAdGroupextend();
        key.setAdGroupId(adGroupId);
        CoreAdGroupextend record =
                (CoreAdGroupextend) getSqlMapClientTemplate().queryForObject("CORE_AD_GROUPEXTEND.selectByAdGroupId",
                        key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public CoreAdGroupextendDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public int deleteByPrimaryKey(Integer adGroupextendId) {
        CoreAdGroupextend key = new CoreAdGroupextend();
        key.setAdGroupextendId(adGroupextendId);
        int rows = getSqlMapClientTemplate().delete("CORE_AD_GROUPEXTEND.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public void insert(CoreAdGroupextend record) {
        getSqlMapClientTemplate().insert("CORE_AD_GROUPEXTEND.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public void insertSelective(CoreAdGroupextend record) {
        getSqlMapClientTemplate().insert("CORE_AD_GROUPEXTEND.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public CoreAdGroupextend selectByPrimaryKey(Integer adGroupextendId) {
        CoreAdGroupextend key = new CoreAdGroupextend();
        key.setAdGroupextendId(adGroupextendId);
        CoreAdGroupextend record =
                (CoreAdGroupextend) getSqlMapClientTemplate().queryForObject(
                        "CORE_AD_GROUPEXTEND.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * 获取所有的地区信息
     */
    public List<CoreAdGroupextend> findAllGroupExtend() {
        List<CoreAdGroupextend> adGroupextendList =
                getSqlMapClientTemplate().queryForList("CORE_AD_GROUPEXTEND.ibatorgenerated_selectAllGroupExtend");
        return adGroupextendList;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public int updateByPrimaryKeySelective(CoreAdGroupextend record) {
        int rows =
                getSqlMapClientTemplate().update("CORE_AD_GROUPEXTEND.ibatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public int updateByPrimaryKeyWithBLOBs(CoreAdGroupextend record) {
        int rows =
                getSqlMapClientTemplate().update("CORE_AD_GROUPEXTEND.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
                        record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * CORE_AD_GROUPEXTEND
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public int updateByPrimaryKeyWithoutBLOBs(CoreAdGroupextend record) {
        int rows = getSqlMapClientTemplate().update("CORE_AD_GROUPEXTEND.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
