package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.LibMarketDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.LibMarket;

/**
 * LibMarketDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class LibMarketDAOImpl extends CustomSqlMapClientDaoSupport implements LibMarketDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_MARKET
     * 
     * @ibatorgenerated Mon Jun 20 10:49:16 CST 2011
     */
    public LibMarketDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_MARKET
     * 
     * @ibatorgenerated Mon Jun 20 10:49:16 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        LibMarket key = new LibMarket();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("LIB_MARKET.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_MARKET
     * 
     * @ibatorgenerated Mon Jun 20 10:49:16 CST 2011
     */
    public Integer insert(LibMarket record) {

        Integer id = 0;
        id = (Integer) getSqlMapClientTemplate().insert("LIB_MARKET.ibatorgenerated_insert", record);
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_MARKET
     * 
     * @ibatorgenerated Mon Jun 20 10:49:16 CST 2011
     */
    public Integer insertSelective(LibMarket record) {
        Integer id = 0;
        id = (Integer) getSqlMapClientTemplate().insert("LIB_MARKET.ibatorgenerated_insertSelective", record);
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_MARKET
     * 
     * @ibatorgenerated Mon Jun 20 10:49:16 CST 2011
     */
    public LibMarket selectByPrimaryKey(Integer id) {
        LibMarket key = new LibMarket();
        key.setId(id);
        LibMarket record =
                (LibMarket) getSqlMapClientTemplate().queryForObject("LIB_MARKET.ibatorgenerated_selectByPrimaryKey",
                        key);
        return record;
    }

    public LibMarket selectByRichId(Integer id) {
        LibMarket key = new LibMarket();
        key.setRichId(id);
        LibMarket record =
                (LibMarket) getSqlMapClientTemplate().queryForObject("LIB_MARKET.ibatorgenerated_selectByRich", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_MARKET
     * 
     * @ibatorgenerated Mon Jun 20 10:49:16 CST 2011
     */
    public int updateByPrimaryKeySelective(LibMarket record) {
        int rows = getSqlMapClientTemplate().update("LIB_MARKET.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LIB_MARKET
     * 
     * @ibatorgenerated Mon Jun 20 10:49:16 CST 2011
     */
    public int updateByPrimaryKey(LibMarket record) {
        int rows = getSqlMapClientTemplate().update("LIB_MARKET.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
