package com.mitian.airad.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.LibMarketDetailDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.LibMarketDetail;

/**
 * LibMarketDetailDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class LibMarketDetailDAOImpl extends CustomSqlMapClientDaoSupport implements LibMarketDetailDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    public LibMarketDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        LibMarketDetail key = new LibMarketDetail();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("LIB_MARKET_DETAIL.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    public void insert(LibMarketDetail record) {
        getSqlMapClientTemplate().insert("LIB_MARKET_DETAIL.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    public void insertSelective(LibMarketDetail record) {
        getSqlMapClientTemplate().insert("LIB_MARKET_DETAIL.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    public LibMarketDetail selectByPrimaryKey(Integer id) {
        LibMarketDetail key = new LibMarketDetail();
        key.setId(id);
        LibMarketDetail record =
                (LibMarketDetail) getSqlMapClientTemplate().queryForObject(
                        "LIB_MARKET_DETAIL.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    public List<LibMarketDetail> selectByMarketId(Integer id) {
        Map<String, String> params = new HashMap();
        params.put("marketId", id.toString());
        List<LibMarketDetail> marketList =
                getSqlMapClientTemplate().queryForList("LIB_MARKET_DETAIL.ibatorgenerated_selectByMarketId", params);
        return marketList;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    public int updateByPrimaryKeySelective(LibMarketDetail record) {
        int rows =
                getSqlMapClientTemplate().update("LIB_MARKET_DETAIL.ibatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * LIB_MARKET_DETAIL
     * 
     * @ibatorgenerated Mon Jun 20 10:42:32 CST 2011
     */
    public int updateByPrimaryKey(LibMarketDetail record) {
        int rows = getSqlMapClientTemplate().update("LIB_MARKET_DETAIL.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
