package com.mitian.airad.dao.impl;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.SdkResourceDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.SdkResource;

/**
 * SdkResourceDAOImpl.java
 * 
 * @author baojun
 */
@Repository
public class SdkResourceDAOImpl extends CustomSqlMapClientDaoSupport implements SdkResourceDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public SdkResourceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public int deleteByPrimaryKey(Integer resVId) {
        SdkResource key = new SdkResource();
        key.setResVId(resVId);
        int rows = getSqlMapClientTemplate().delete("SDK_RESOURCE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public void insert(SdkResource record) {
        getSqlMapClientTemplate().insert("SDK_RESOURCE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public void insertSelective(SdkResource record) {
        getSqlMapClientTemplate().insert("SDK_RESOURCE.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public SdkResource selectByPrimaryKey(Integer resVId) {
        SdkResource key = new SdkResource();
        key.setResVId(resVId);
        SdkResource record =
                (SdkResource) getSqlMapClientTemplate().queryForObject(
                        "SDK_RESOURCE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public int updateByPrimaryKeySelective(SdkResource record) {
        int rows = getSqlMapClientTemplate().update("SDK_RESOURCE.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public int updateByPrimaryKeyWithBLOBs(SdkResource record) {
        int rows = getSqlMapClientTemplate().update("SDK_RESOURCE.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table SDK_RESOURCE
     * 
     * @ibatorgenerated Thu Feb 17 16:34:34 CST 2011
     */
    public int updateByPrimaryKeyWithoutBLOBs(SdkResource record) {
        int rows = getSqlMapClientTemplate().update("SDK_RESOURCE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.SdkResourceDAO#findSdkResourceById(com.mitian.airad.model.SdkResource)
     */
    public List<SdkResource> findSdkResourceById(Map<String, Object> record) {
        return getSqlMapClientTemplate().queryForList("SDK_RESOURCE.ibatorgenerated_selectById", record);
    }

    public SdkResource findNewResource(String osTypes) {
        return (SdkResource) getSqlMapClientTemplate().queryForObject("SDK_RESOURCE.ibatorgenerated_selectNewVersion",
                osTypes);
    }
}
