package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * AccIncome.java
 * 
 * @author baojun
 */
public class AccIncome {
    /** 应用名称 */
    private String appName;
    /** 应用code范围 */
    private String inAppCode;
    private BigDecimal sumOffer;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ACC_INCOME.INCOME_ID
     * 
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    private Integer incomeId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ACC_INCOME.GUIDE_ID
     * 
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    private Integer guideId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ACC_INCOME.OFFER
     * 
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    private BigDecimal offer;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ACC_INCOME.INCOME_TYPE
     * 
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    private String incomeType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ACC_INCOME.INCOME_FORMULA
     * 
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    private String incomeFormula;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ACC_INCOME.REQ_TIME
     * 
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    private Date reqTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ACC_INCOME.APP_CODE
     * 
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    private String appCode;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME.INCOME_ID
     * 
     * @return the value of ACC_INCOME.INCOME_ID
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public Integer getIncomeId() {
        return incomeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME.INCOME_ID
     * 
     * @param incomeId the value for ACC_INCOME.INCOME_ID
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public void setIncomeId(Integer incomeId) {
        this.incomeId = incomeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME.GUIDE_ID
     * 
     * @return the value of ACC_INCOME.GUIDE_ID
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public Integer getGuideId() {
        return guideId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME.GUIDE_ID
     * 
     * @param guideId the value for ACC_INCOME.GUIDE_ID
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public void setGuideId(Integer guideId) {
        this.guideId = guideId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME.OFFER
     * 
     * @return the value of ACC_INCOME.OFFER
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public BigDecimal getOffer() {
        return offer;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME.OFFER
     * 
     * @param offer the value for ACC_INCOME.OFFER
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public void setOffer(BigDecimal offer) {
        this.offer = offer;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME.INCOME_TYPE
     * 
     * @return the value of ACC_INCOME.INCOME_TYPE
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public String getIncomeType() {
        return incomeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME.INCOME_TYPE
     * 
     * @param incomeType the value for ACC_INCOME.INCOME_TYPE
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public void setIncomeType(String incomeType) {
        this.incomeType = incomeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME.INCOME_FORMULA
     * 
     * @return the value of ACC_INCOME.INCOME_FORMULA
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public String getIncomeFormula() {
        return incomeFormula;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME.INCOME_FORMULA
     * 
     * @param incomeFormula the value for ACC_INCOME.INCOME_FORMULA
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public void setIncomeFormula(String incomeFormula) {
        this.incomeFormula = incomeFormula;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME.REQ_TIME
     * 
     * @return the value of ACC_INCOME.REQ_TIME
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public Date getReqTime() {
        return reqTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME.REQ_TIME
     * 
     * @param reqTime the value for ACC_INCOME.REQ_TIME
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public void setReqTime(Date reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * @return the appName
     */
    public String getAppName() {
        return appName;
    }

    /**
     * @param appName the appName to set
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * @return the inAppCode
     */
    public String getInAppCode() {
        return inAppCode;
    }

    /**
     * @param inAppCode the inAppCode to set
     */
    public void setInAppCode(String inAppCode) {
        this.inAppCode = inAppCode;
    }

    /**
     * @return the sumOffer
     */
    public BigDecimal getSumOffer() {
        return sumOffer;
    }

    /**
     * @param sumOffer the sumOffer to set
     */
    public void setSumOffer(BigDecimal sumOffer) {
        this.sumOffer = sumOffer;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME.APP_CODE
     * 
     * @return the value of ACC_INCOME.APP_CODE
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME.APP_CODE
     * 
     * @param appCode the value for ACC_INCOME.APP_CODE
     * @ibatorgenerated Wed Mar 02 13:45:24 CST 2011
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }
}
