package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 会员提现记录表
 * 
 * @author tangwenjun
 */
public class CoreWithdraw {
    /**
     * 会员提现id
     */
    private Integer drawMoneyId;
    /**
     * 会员Id
     */
    private Long memberId;

    /**
     * 会员提现汇总表Id
     */
    private Integer drawSumId;

    /**
     * 会员提现流水号
     */
    private String drawMoneySerialId;

    /**
     * 提现额度
     */
    private BigDecimal drawMoney;

    /**
     * 申请时间
     */
    private Date drawTime;

    /**
     * 受理状态
     */
    private String status;

    /**
     * 提现备注
     */
    private String drawRemark;

    /**
     * 银联账号
     */
    private String unionpayId;

    /**
     * 提现人姓名
     */
    private String drawName;

    /**
     * 体现银行
     */
    private String drawBankNum;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.DRAW_MONEY_ID
     * 
     * @return the value of CORE_WITHDRAW.DRAW_MONEY_ID
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public Integer getDrawMoneyId() {
        return drawMoneyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.DRAW_MONEY_ID
     * 
     * @param drawMoneyId the value for CORE_WITHDRAW.DRAW_MONEY_ID
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setDrawMoneyId(Integer drawMoneyId) {
        this.drawMoneyId = drawMoneyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.MEMBER_ID
     * 
     * @return the value of CORE_WITHDRAW.MEMBER_ID
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.MEMBER_ID
     * 
     * @param memberId the value for CORE_WITHDRAW.MEMBER_ID
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.DRAW_SUM_ID
     * 
     * @return the value of CORE_WITHDRAW.DRAW_SUM_ID
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public Integer getDrawSumId() {
        return drawSumId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.DRAW_SUM_ID
     * 
     * @param drawSumId the value for CORE_WITHDRAW.DRAW_SUM_ID
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setDrawSumId(Integer drawSumId) {
        this.drawSumId = drawSumId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.DRAW_MONEY
     * 
     * @return the value of CORE_WITHDRAW.DRAW_MONEY
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public BigDecimal getDrawMoney() {
        return drawMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.DRAW_MONEY
     * 
     * @param drawMoney the value for CORE_WITHDRAW.DRAW_MONEY
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setDrawMoney(BigDecimal drawMoney) {
        this.drawMoney = drawMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.DRAW_TIME
     * 
     * @return the value of CORE_WITHDRAW.DRAW_TIME
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public Date getDrawTime() {
        return drawTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.DRAW_TIME
     * 
     * @param drawTime the value for CORE_WITHDRAW.DRAW_TIME
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setDrawTime(Date drawTime) {
        this.drawTime = drawTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.STATUS
     * 
     * @return the value of CORE_WITHDRAW.STATUS
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public String getStatus() {

        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.STATUS
     * 
     * @param status the value for CORE_WITHDRAW.STATUS
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.DRAW_REMARK
     * 
     * @return the value of CORE_WITHDRAW.DRAW_REMARK
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public String getDrawRemark() {
        return drawRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.DRAW_REMARK
     * 
     * @param drawRemark the value for CORE_WITHDRAW.DRAW_REMARK
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setDrawRemark(String drawRemark) {
        this.drawRemark = drawRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.UNIONPAY_ID
     * 
     * @return the value of CORE_WITHDRAW.UNIONPAY_ID
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public String getUnionpayId() {
        return unionpayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.UNIONPAY_ID
     * 
     * @param unionpayId the value for CORE_WITHDRAW.UNIONPAY_ID
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setUnionpayId(String unionpayId) {
        this.unionpayId = unionpayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.DRAW_NAME
     * 
     * @return the value of CORE_WITHDRAW.DRAW_NAME
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public String getDrawName() {
        return drawName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.DRAW_NAME
     * 
     * @param drawName the value for CORE_WITHDRAW.DRAW_NAME
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setDrawName(String drawName) {
        this.drawName = drawName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_WITHDRAW.DRAW_BANK_NUM
     * 
     * @return the value of CORE_WITHDRAW.DRAW_BANK_NUM
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public String getDrawBankNum() {
        return drawBankNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_WITHDRAW.DRAW_BANK_NUM
     * 
     * @param drawBankNum the value for CORE_WITHDRAW.DRAW_BANK_NUM
     * @ibatorgenerated Thu Jan 27 09:21:17 CST 2011
     */
    public void setDrawBankNum(String drawBankNum) {
        this.drawBankNum = drawBankNum;
    }

    /**
     * @return the drawMoneySerialId
     */
    public String getDrawMoneySerialId() {
        return drawMoneySerialId;
    }

    /**
     * @param drawMoneySerialId the drawMoneySerialId to set
     */
    public void setDrawMoneySerialId(String drawMoneySerialId) {
        this.drawMoneySerialId = drawMoneySerialId;
    }

}
