package com.mitian.airad.model;

/**
 * CoreAdGroupextend.java
 * 
 * @author baojun
 */
public class CoreAdGroupextend {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUPEXTEND.AD_GROUPEXTEND_ID
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    private Integer adGroupextendId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUPEXTEND.AD_GROUP_ID
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    private Integer adGroupId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUPEXTEND.GEOGRAPHICAL_POSITION
     * 
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    private String geographicalPosition;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUPEXTEND.AD_GROUPEXTEND_ID
     * 
     * @return the value of CORE_AD_GROUPEXTEND.AD_GROUPEXTEND_ID
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */

    private String shortGeographicalPosition;

    public Integer getAdGroupextendId() {
        return adGroupextendId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUPEXTEND.AD_GROUPEXTEND_ID
     * 
     * @param adGroupextendId the value for CORE_AD_GROUPEXTEND.AD_GROUPEXTEND_ID
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public void setAdGroupextendId(Integer adGroupextendId) {
        this.adGroupextendId = adGroupextendId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUPEXTEND.AD_GROUP_ID
     * 
     * @return the value of CORE_AD_GROUPEXTEND.AD_GROUP_ID
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public Integer getAdGroupId() {
        return adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUPEXTEND.AD_GROUP_ID
     * 
     * @param adGroupId the value for CORE_AD_GROUPEXTEND.AD_GROUP_ID
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public void setAdGroupId(Integer adGroupId) {
        this.adGroupId = adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUPEXTEND.GEOGRAPHICAL_POSITION
     * 
     * @return the value of CORE_AD_GROUPEXTEND.GEOGRAPHICAL_POSITION
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public String getGeographicalPosition() {
        return geographicalPosition;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUPEXTEND.GEOGRAPHICAL_POSITION
     * 
     * @param geographicalPosition the value for CORE_AD_GROUPEXTEND.GEOGRAPHICAL_POSITION
     * @ibatorgenerated Sat Feb 26 11:32:27 CST 2011
     */
    public void setGeographicalPosition(String geographicalPosition) {
        this.geographicalPosition = geographicalPosition;
    }

    public String getShortGeographicalPosition() {
        return shortGeographicalPosition;
    }

    public void setShortGeographicalPosition(String shortGeographicalPosition) {
        this.shortGeographicalPosition = shortGeographicalPosition;
    }

}
