package com.mitian.airad.model;

/**
 * DictionaryGlobalRegion.java
 * 
 * @author baojun
 */
public class DictionaryGlobalRegion {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * DICTIONARY_GLOBAL_REGION.REGION_ID
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    private Short regionId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * DICTIONARY_GLOBAL_REGION.PARENT_ID
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    private Short parentId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * DICTIONARY_GLOBAL_REGION.REGION_NAME
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    private String regionName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * DICTIONARY_GLOBAL_REGION.REGION_NAME_EN
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    private String regionNameEn;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * DICTIONARY_GLOBAL_REGION.REGION_TYPE
     * 
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    private String regionType;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * DICTIONARY_GLOBAL_REGION.REGION_ID
     * 
     * @return the value of DICTIONARY_GLOBAL_REGION.REGION_ID
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    public Short getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * DICTIONARY_GLOBAL_REGION.REGION_ID
     * 
     * @param regionId the value for DICTIONARY_GLOBAL_REGION.REGION_ID
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    public void setRegionId(Short regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * DICTIONARY_GLOBAL_REGION.PARENT_ID
     * 
     * @return the value of DICTIONARY_GLOBAL_REGION.PARENT_ID
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * DICTIONARY_GLOBAL_REGION.PARENT_ID
     * 
     * @param parentId the value for DICTIONARY_GLOBAL_REGION.PARENT_ID
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * DICTIONARY_GLOBAL_REGION.REGION_NAME
     * 
     * @return the value of DICTIONARY_GLOBAL_REGION.REGION_NAME
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * DICTIONARY_GLOBAL_REGION.REGION_NAME
     * 
     * @param regionName the value for DICTIONARY_GLOBAL_REGION.REGION_NAME
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * DICTIONARY_GLOBAL_REGION.REGION_NAME_EN
     * 
     * @return the value of DICTIONARY_GLOBAL_REGION.REGION_NAME_EN
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    public String getRegionNameEn() {
        return regionNameEn;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * DICTIONARY_GLOBAL_REGION.REGION_NAME_EN
     * 
     * @param regionNameEn the value for DICTIONARY_GLOBAL_REGION.REGION_NAME_EN
     * @ibatorgenerated Fri Mar 18 14:05:07 CST 2011
     */
    public void setRegionNameEn(String regionNameEn) {
        this.regionNameEn = regionNameEn;
    }

    /**
     * @return the regionType
     */
    public String getRegionType() {
        return regionType;
    }

    /**
     * @param regionType the regionType to set
     */
    public void setRegionType(String regionType) {
        this.regionType = regionType;
    }

}
