package com.mitian.airad.model;

/**
 * LibImgSourceType.java
 * 
 * @author baojun
 */
public class LibImgSourceType {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_IMG_SOURCE_TYPE.IMG_SOURCE_ID
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private Integer imgSourceId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_IMG_SOURCE_TYPE.IMG_PATER_SOURCE_ID
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private Integer imgPaterSourceId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_IMG_SOURCE_TYPE.IMG_SOURCE_DEC
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private String imgSourceDec;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG_SOURCE_TYPE.IMG_SOURCE_ID
     * 
     * @return the value of LIB_IMG_SOURCE_TYPE.IMG_SOURCE_ID
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public Integer getImgSourceId() {
        return imgSourceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG_SOURCE_TYPE.IMG_SOURCE_ID
     * 
     * @param imgSourceId the value for LIB_IMG_SOURCE_TYPE.IMG_SOURCE_ID
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgSourceId(Integer imgSourceId) {
        this.imgSourceId = imgSourceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG_SOURCE_TYPE.IMG_PATER_SOURCE_ID
     * 
     * @return the value of LIB_IMG_SOURCE_TYPE.IMG_PATER_SOURCE_ID
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public Integer getImgPaterSourceId() {
        return imgPaterSourceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG_SOURCE_TYPE.IMG_PATER_SOURCE_ID
     * 
     * @param imgPaterSourceId the value for LIB_IMG_SOURCE_TYPE.IMG_PATER_SOURCE_ID
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgPaterSourceId(Integer imgPaterSourceId) {
        this.imgPaterSourceId = imgPaterSourceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG_SOURCE_TYPE.IMG_SOURCE_DEC
     * 
     * @return the value of LIB_IMG_SOURCE_TYPE.IMG_SOURCE_DEC
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public String getImgSourceDec() {
        return imgSourceDec;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG_SOURCE_TYPE.IMG_SOURCE_DEC
     * 
     * @param imgSourceDec the value for LIB_IMG_SOURCE_TYPE.IMG_SOURCE_DEC
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgSourceDec(String imgSourceDec) {
        this.imgSourceDec = imgSourceDec;
    }
}
