package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * StatWithdraw.java
 * 
 * @author baojun
 */
public class StatWithdraw {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.STAT_DRAW_ID
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private Integer statDrawId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.MEMBER_ID
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private Integer memberId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.DRAW_MONEY_SERIAL_ID
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private String drawMoneySerialId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.DRAW_MONEY
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private BigDecimal drawMoney;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.STATUS
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.UNIONPAY_ID
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private String unionpayId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.DRAW_BANK_NUM
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private String drawBankNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.DRAW_NAME
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private String drawName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.ADD_TIME
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW.JOB_STAT_TIME
     * 
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    private Date jobStatTime;

    // 统计时间
    private String jobTime;

    /**
     * @return the jobTime
     */
    public String getJobTime() {
        return jobTime;
    }

    /**
     * @param jobTime the jobTime to set
     */
    public void setJobTime(String jobTime) {
        this.jobTime = jobTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.STAT_DRAW_ID
     * 
     * @return the value of STAT_WITHDRAW.STAT_DRAW_ID
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public Integer getStatDrawId() {
        return statDrawId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.STAT_DRAW_ID
     * 
     * @param statDrawId the value for STAT_WITHDRAW.STAT_DRAW_ID
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setStatDrawId(Integer statDrawId) {
        this.statDrawId = statDrawId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.MEMBER_ID
     * 
     * @return the value of STAT_WITHDRAW.MEMBER_ID
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.MEMBER_ID
     * 
     * @param memberId the value for STAT_WITHDRAW.MEMBER_ID
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.DRAW_MONEY_SERIAL_ID
     * 
     * @return the value of STAT_WITHDRAW.DRAW_MONEY_SERIAL_ID
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public String getDrawMoneySerialId() {
        return drawMoneySerialId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.DRAW_MONEY_SERIAL_ID
     * 
     * @param drawMoneySerialId the value for STAT_WITHDRAW.DRAW_MONEY_SERIAL_ID
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setDrawMoneySerialId(String drawMoneySerialId) {
        this.drawMoneySerialId = drawMoneySerialId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.DRAW_MONEY
     * 
     * @return the value of STAT_WITHDRAW.DRAW_MONEY
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public BigDecimal getDrawMoney() {
        return drawMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.DRAW_MONEY
     * 
     * @param drawMoney the value for STAT_WITHDRAW.DRAW_MONEY
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setDrawMoney(BigDecimal drawMoney) {
        this.drawMoney = drawMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.STATUS
     * 
     * @return the value of STAT_WITHDRAW.STATUS
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.STATUS
     * 
     * @param status the value for STAT_WITHDRAW.STATUS
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.UNIONPAY_ID
     * 
     * @return the value of STAT_WITHDRAW.UNIONPAY_ID
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public String getUnionpayId() {
        return unionpayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.UNIONPAY_ID
     * 
     * @param unionpayId the value for STAT_WITHDRAW.UNIONPAY_ID
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setUnionpayId(String unionpayId) {
        this.unionpayId = unionpayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.DRAW_BANK_NUM
     * 
     * @return the value of STAT_WITHDRAW.DRAW_BANK_NUM
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public String getDrawBankNum() {
        return drawBankNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.DRAW_BANK_NUM
     * 
     * @param drawBankNum the value for STAT_WITHDRAW.DRAW_BANK_NUM
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setDrawBankNum(String drawBankNum) {
        this.drawBankNum = drawBankNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.DRAW_NAME
     * 
     * @return the value of STAT_WITHDRAW.DRAW_NAME
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public String getDrawName() {
        return drawName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.DRAW_NAME
     * 
     * @param drawName the value for STAT_WITHDRAW.DRAW_NAME
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setDrawName(String drawName) {
        this.drawName = drawName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.ADD_TIME
     * 
     * @return the value of STAT_WITHDRAW.ADD_TIME
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.ADD_TIME
     * 
     * @param addTime the value for STAT_WITHDRAW.ADD_TIME
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW.JOB_STAT_TIME
     * 
     * @return the value of STAT_WITHDRAW.JOB_STAT_TIME
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public Date getJobStatTime() {
        return jobStatTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW.JOB_STAT_TIME
     * 
     * @param jobStatTime the value for STAT_WITHDRAW.JOB_STAT_TIME
     * @ibatorgenerated Sat Apr 02 15:30:14 CST 2011
     */
    public void setJobStatTime(Date jobStatTime) {
        this.jobStatTime = jobStatTime;
    }
}
