package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * StatWithdrawMonth.java
 * 
 * @author baojun
 */
public class StatWithdrawMonth {

    /** 提现申请时间 */
    private String sqTime;
    /** 证件号码 */
    private String idCard;
    /** 开发姓名 */
    private String realName;

    public String getSqTime() {
        return sqTime;
    }

    public void setSqTime(String sqTime) {
        this.sqTime = sqTime;
    }

    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.DRAW_SUM_ID
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 会员提现汇总表id
     */
    private Integer drawSumId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.DRAW_SUM_NUM
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 提现汇总流水号
     */
    private Integer drawSumNum;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.DRAW_USER_ID
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 提现人ID
     */
    private Integer drawUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.ENTRY_TIME
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 记录录入时间
     */
    private Date entryTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.HEAR_ID
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 受理人
     */
    private Integer hearId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.HEAR_REMARK
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 受理意见
     */
    private String hearRemark;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.START_TIME
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 开始时间
     */
    private Date startTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.END_TIME
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 结束时间
     */
    private Date endTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.TRADE_MONEY_TYPE
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 交易金类型
     */
    private String tradeMoneyType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.STATUS
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 受理状态
     */
    private String status;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.INCOME_TAX_ID
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 所得税计算ID
     */
    private String incomeTaxId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.JOB_TIME
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 JOB执行时间
     */
    private Date jobTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.UNIONPAY_ID
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 银联账号
     */
    private String unionpayId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.DRAW_NAME
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 提现人姓名
     */
    private String drawName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.DRAW_BANK_NUM
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 提现人开户行
     */
    private String drawBankNum;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.HEAR_NAME
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 受理人姓名
     */
    private String hearName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.CURRENCY
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 币种
     */
    private String currency;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_WITHDRAW_MONTH.WITHDRAW_MONEY
     * 
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011 提现额度
     */
    private BigDecimal withdrawMoney;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_SUM_ID
     * 
     * @return the value of STAT_WITHDRAW_MONTH.DRAW_SUM_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public Integer getDrawSumId() {
        return drawSumId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_SUM_ID
     * 
     * @param drawSumId the value for STAT_WITHDRAW_MONTH.DRAW_SUM_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setDrawSumId(Integer drawSumId) {
        this.drawSumId = drawSumId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_SUM_NUM
     * 
     * @return the value of STAT_WITHDRAW_MONTH.DRAW_SUM_NUM
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public Integer getDrawSumNum() {
        return drawSumNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_SUM_NUM
     * 
     * @param drawSumNum the value for STAT_WITHDRAW_MONTH.DRAW_SUM_NUM
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setDrawSumNum(Integer drawSumNum) {
        this.drawSumNum = drawSumNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_USER_ID
     * 
     * @return the value of STAT_WITHDRAW_MONTH.DRAW_USER_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public Integer getDrawUserId() {
        return drawUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_USER_ID
     * 
     * @param drawUserId the value for STAT_WITHDRAW_MONTH.DRAW_USER_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setDrawUserId(Integer drawUserId) {
        this.drawUserId = drawUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.ENTRY_TIME
     * 
     * @return the value of STAT_WITHDRAW_MONTH.ENTRY_TIME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.ENTRY_TIME
     * 
     * @param entryTime the value for STAT_WITHDRAW_MONTH.ENTRY_TIME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.HEAR_ID
     * 
     * @return the value of STAT_WITHDRAW_MONTH.HEAR_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public Integer getHearId() {
        return hearId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.HEAR_ID
     * 
     * @param hearId the value for STAT_WITHDRAW_MONTH.HEAR_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setHearId(Integer hearId) {
        this.hearId = hearId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.HEAR_REMARK
     * 
     * @return the value of STAT_WITHDRAW_MONTH.HEAR_REMARK
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getHearRemark() {
        return hearRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.HEAR_REMARK
     * 
     * @param hearRemark the value for STAT_WITHDRAW_MONTH.HEAR_REMARK
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setHearRemark(String hearRemark) {
        this.hearRemark = hearRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.START_TIME
     * 
     * @return the value of STAT_WITHDRAW_MONTH.START_TIME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.START_TIME
     * 
     * @param startTime the value for STAT_WITHDRAW_MONTH.START_TIME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.END_TIME
     * 
     * @return the value of STAT_WITHDRAW_MONTH.END_TIME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.END_TIME
     * 
     * @param endTime the value for STAT_WITHDRAW_MONTH.END_TIME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.TRADE_MONEY_TYPE
     * 
     * @return the value of STAT_WITHDRAW_MONTH.TRADE_MONEY_TYPE
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getTradeMoneyType() {
        return tradeMoneyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.TRADE_MONEY_TYPE
     * 
     * @param tradeMoneyType the value for STAT_WITHDRAW_MONTH.TRADE_MONEY_TYPE
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setTradeMoneyType(String tradeMoneyType) {
        this.tradeMoneyType = tradeMoneyType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.STATUS
     * 
     * @return the value of STAT_WITHDRAW_MONTH.STATUS
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.STATUS
     * 
     * @param status the value for STAT_WITHDRAW_MONTH.STATUS
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.INCOME_TAX_ID
     * 
     * @return the value of STAT_WITHDRAW_MONTH.INCOME_TAX_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getIncomeTaxId() {
        return incomeTaxId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.INCOME_TAX_ID
     * 
     * @param incomeTaxId the value for STAT_WITHDRAW_MONTH.INCOME_TAX_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setIncomeTaxId(String incomeTaxId) {
        this.incomeTaxId = incomeTaxId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.JOB_TIME
     * 
     * @return the value of STAT_WITHDRAW_MONTH.JOB_TIME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public Date getJobTime() {
        return jobTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.JOB_TIME
     * 
     * @param jobTime the value for STAT_WITHDRAW_MONTH.JOB_TIME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setJobTime(Date jobTime) {
        this.jobTime = jobTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.UNIONPAY_ID
     * 
     * @return the value of STAT_WITHDRAW_MONTH.UNIONPAY_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getUnionpayId() {
        return unionpayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.UNIONPAY_ID
     * 
     * @param unionpayId the value for STAT_WITHDRAW_MONTH.UNIONPAY_ID
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setUnionpayId(String unionpayId) {
        this.unionpayId = unionpayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_NAME
     * 
     * @return the value of STAT_WITHDRAW_MONTH.DRAW_NAME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getDrawName() {
        return drawName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_NAME
     * 
     * @param drawName the value for STAT_WITHDRAW_MONTH.DRAW_NAME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setDrawName(String drawName) {
        this.drawName = drawName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_BANK_NUM
     * 
     * @return the value of STAT_WITHDRAW_MONTH.DRAW_BANK_NUM
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getDrawBankNum() {
        return drawBankNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.DRAW_BANK_NUM
     * 
     * @param drawBankNum the value for STAT_WITHDRAW_MONTH.DRAW_BANK_NUM
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setDrawBankNum(String drawBankNum) {
        this.drawBankNum = drawBankNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.HEAR_NAME
     * 
     * @return the value of STAT_WITHDRAW_MONTH.HEAR_NAME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getHearName() {
        return hearName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.HEAR_NAME
     * 
     * @param hearName the value for STAT_WITHDRAW_MONTH.HEAR_NAME
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setHearName(String hearName) {
        this.hearName = hearName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.CURRENCY
     * 
     * @return the value of STAT_WITHDRAW_MONTH.CURRENCY
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.CURRENCY
     * 
     * @param currency the value for STAT_WITHDRAW_MONTH.CURRENCY
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_WITHDRAW_MONTH.WITHDRAW_MONEY
     * 
     * @return the value of STAT_WITHDRAW_MONTH.WITHDRAW_MONEY
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public BigDecimal getWithdrawMoney() {
        return withdrawMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_WITHDRAW_MONTH.WITHDRAW_MONEY
     * 
     * @param withdrawMoney the value for STAT_WITHDRAW_MONTH.WITHDRAW_MONEY
     * @ibatorgenerated Sun Jan 30 10:16:21 CST 2011
     */
    public void setWithdrawMoney(BigDecimal withdrawMoney) {
        this.withdrawMoney = withdrawMoney;
    }
}
