package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * StatAd.java
 * 
 * @author baojun
 */
public class StatAd {
    private String reqTime;
    private String inAdId;
    private Date jobStatTime;
    private String jobStatType;
    private String delFlag;
    private int startPag;
    private int endPag;
    private String flag;
    private String reqTimeEnd;
    private BigDecimal clickRate;

    /**
     * @return the clickRate
     */
    public BigDecimal getClickRate() {
        if (clickRate == null) {
            return new BigDecimal(0);
        }
        else {
            return clickRate;
        }
        // return clickRate;
    }

    /**
     * @param clickRate the clickRate to set
     */
    public void setClickRate(BigDecimal clickRate) {
        this.clickRate = clickRate;
    }

    /**
     * @return the reqTimeEnd
     */
    public String getReqTimeEnd() {
        return reqTimeEnd;
    }

    /**
     * @param reqTimeEnd the reqTimeEnd to set
     */
    public void setReqTimeEnd(String reqTimeEnd) {
        this.reqTimeEnd = reqTimeEnd;
    }

    /**
     * @return the flag
     */
    public String getFlag() {
        return flag;
    }

    /**
     * @param flag the flag to set
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * @return the startPag
     */
    public int getStartPag() {
        return startPag;
    }

    /**
     * @param startPag the startPag to set
     */
    public void setStartPag(int startPag) {
        this.startPag = startPag;
    }

    /**
     * @return the endPag
     */
    public int getEndPag() {
        return endPag;
    }

    /**
     * @param endPag the endPag to set
     */
    public void setEndPag(int endPag) {
        this.endPag = endPag;
    }

    /**
     * @return the delFlag
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * @param delFlag the delFlag to set
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * @return the jobStatTime
     */
    public Date getJobStatTime() {
        return jobStatTime;
    }

    /**
     * @param jobStatTime the jobStatTime to set
     */
    public void setJobStatTime(Date jobStatTime) {
        this.jobStatTime = jobStatTime;
    }

    /**
     * @return the jobStatType
     */
    public String getJobStatType() {
        return jobStatType;
    }

    /**
     * @param jobStatType the jobStatType to set
     */
    public void setJobStatType(String jobStatType) {
        this.jobStatType = jobStatType;
    }

    /**
     * @return the inAdId
     */
    public String getInAdId() {
        return inAdId;
    }

    /**
     * @param inAdId the inAdId to set
     */
    public void setInAdId(String inAdId) {
        this.inAdId = inAdId;
    }

    /**
     * @return the reqTime
     */
    public String getReqTime() {
        return reqTime;
    }

    /**
     * @param reqTime the reqTime to set
     */
    public void setReqTime(String reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AD.SHAT_AD_ID
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer shatAdId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_AD.AD_ID
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer adId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_AD.AD_NAME
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private String adName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AD.AD_GROUP_ID
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer adGroupId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AD.AD_GROUP_NAME
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private String adGroupName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AD.CAMPAIGN_ID
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer campaignId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AD.CAMPAIGN_NAME
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private String campaignName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AD.ADVERTISER_ID
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer advertiserId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_AD.SHOW_NUM
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer showNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_AD.CLICK_NUM
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer clickNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AD.SHOW_MONEY
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private BigDecimal showMoney;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AD.CLICK_MONEY
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private BigDecimal clickMoney;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_AD.ADD_TIME
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_AD.SHOW_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private String showType;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.SHAT_AD_ID
     * 
     * @return the value of STAT_AD.SHAT_AD_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getShatAdId() {
        return shatAdId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.SHAT_AD_ID
     * 
     * @param shatAdId the value for STAT_AD.SHAT_AD_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setShatAdId(Integer shatAdId) {
        this.shatAdId = shatAdId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.AD_ID
     * 
     * @return the value of STAT_AD.AD_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.AD_ID
     * 
     * @param adId the value for STAT_AD.AD_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.AD_NAME
     * 
     * @return the value of STAT_AD.AD_NAME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.AD_NAME
     * 
     * @param adName the value for STAT_AD.AD_NAME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAdName(String adName) {
        this.adName = adName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.AD_GROUP_ID
     * 
     * @return the value of STAT_AD.AD_GROUP_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getAdGroupId() {
        return adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.AD_GROUP_ID
     * 
     * @param adGroupId the value for STAT_AD.AD_GROUP_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAdGroupId(Integer adGroupId) {
        this.adGroupId = adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.AD_GROUP_NAME
     * 
     * @return the value of STAT_AD.AD_GROUP_NAME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public String getAdGroupName() {
        return adGroupName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.AD_GROUP_NAME
     * 
     * @param adGroupName the value for STAT_AD.AD_GROUP_NAME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAdGroupName(String adGroupName) {
        this.adGroupName = adGroupName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.CAMPAIGN_ID
     * 
     * @return the value of STAT_AD.CAMPAIGN_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.CAMPAIGN_ID
     * 
     * @param campaignId the value for STAT_AD.CAMPAIGN_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.CAMPAIGN_NAME
     * 
     * @return the value of STAT_AD.CAMPAIGN_NAME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public String getCampaignName() {
        return campaignName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.CAMPAIGN_NAME
     * 
     * @param campaignName the value for STAT_AD.CAMPAIGN_NAME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.ADVERTISER_ID
     * 
     * @return the value of STAT_AD.ADVERTISER_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getAdvertiserId() {
        return advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.ADVERTISER_ID
     * 
     * @param advertiserId the value for STAT_AD.ADVERTISER_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAdvertiserId(Integer advertiserId) {
        this.advertiserId = advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.SHOW_NUM
     * 
     * @return the value of STAT_AD.SHOW_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getShowNum() {
        return showNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.SHOW_NUM
     * 
     * @param showNum the value for STAT_AD.SHOW_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setShowNum(Integer showNum) {
        this.showNum = showNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.CLICK_NUM
     * 
     * @return the value of STAT_AD.CLICK_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.CLICK_NUM
     * 
     * @param clickNum the value for STAT_AD.CLICK_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.SHOW_MONEY
     * 
     * @return the value of STAT_AD.SHOW_MONEY
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public BigDecimal getShowMoney() {
        if (showMoney == null) {
            return new BigDecimal(0);
        }
        else {
            return showMoney;
        }
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.SHOW_MONEY
     * 
     * @param showMoney the value for STAT_AD.SHOW_MONEY
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setShowMoney(BigDecimal showMoney) {
        this.showMoney = showMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.CLICK_MONEY
     * 
     * @return the value of STAT_AD.CLICK_MONEY
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public BigDecimal getClickMoney() {
        if (clickMoney == null) {
            return new BigDecimal(0);
        }
        else {
            return clickMoney;
        }
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.CLICK_MONEY
     * 
     * @param clickMoney the value for STAT_AD.CLICK_MONEY
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setClickMoney(BigDecimal clickMoney) {
        this.clickMoney = clickMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.ADD_TIME
     * 
     * @return the value of STAT_AD.ADD_TIME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.ADD_TIME
     * 
     * @param addTime the value for STAT_AD.ADD_TIME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AD.SHOW_TYPE
     * 
     * @return the value of STAT_AD.SHOW_TYPE
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public String getShowType() {
        return showType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AD.SHOW_TYPE
     * 
     * @param showType the value for STAT_AD.SHOW_TYPE
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setShowType(String showType) {
        this.showType = showType;
    }
}
