package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * AccIncomePay.java
 * 
 * @author tangwenjun
 */
public class AccIncomePay {
    /**
     * 交易流水号
     */
    private Integer tradeId;

    /**
     * 金额
     */
    private BigDecimal money;

    /**
     * 交易类型
     */
    private String tradeType;

    /**
     * 请求时间
     */
    private Date reqTime;

    /**
     * 添加人
     */
    private String addOper;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     * 更新人
     */
    private String updOper;

    /**
     * 更新时间
     */
    private Date updTime;

    /**
     * 删除人
     */
    private String delOper;

    /**
     * 删除时间
     */
    private Date delTime;

    /**
     * 删除标记
     */
    private String delFlag;

    /**
     * 广告ID
     */
    private Integer adId;

    /**
     * 会员ID
     */
    private Long memberId;

    /**
     * 收支类型
     */
    private String incomePayType;

    /**
     * 受理状态
     */
    private String status;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.TRADE_ID
     * 
     * @return the value of ACC_INCOME_PAY.TRADE_ID
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.TRADE_ID
     * 
     * @param tradeId the value for ACC_INCOME_PAY.TRADE_ID
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.MONEY
     * 
     * @return the value of ACC_INCOME_PAY.MONEY
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.MONEY
     * 
     * @param money the value for ACC_INCOME_PAY.MONEY
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.TRADE_TYPE
     * 
     * @return the value of ACC_INCOME_PAY.TRADE_TYPE
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.TRADE_TYPE
     * 
     * @param tradeType the value for ACC_INCOME_PAY.TRADE_TYPE
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.REQ_TIME
     * 
     * @return the value of ACC_INCOME_PAY.REQ_TIME
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public Date getReqTime() {
        return reqTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.REQ_TIME
     * 
     * @param reqTime the value for ACC_INCOME_PAY.REQ_TIME
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setReqTime(Date reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.ADD_OPER
     * 
     * @return the value of ACC_INCOME_PAY.ADD_OPER
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public String getAddOper() {
        return addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.ADD_OPER
     * 
     * @param addOper the value for ACC_INCOME_PAY.ADD_OPER
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setAddOper(String addOper) {
        this.addOper = addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.ADD_TIME
     * 
     * @return the value of ACC_INCOME_PAY.ADD_TIME
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.ADD_TIME
     * 
     * @param addTime the value for ACC_INCOME_PAY.ADD_TIME
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.UPD_OPER
     * 
     * @return the value of ACC_INCOME_PAY.UPD_OPER
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public String getUpdOper() {
        return updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.UPD_OPER
     * 
     * @param updOper the value for ACC_INCOME_PAY.UPD_OPER
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setUpdOper(String updOper) {
        this.updOper = updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.UPD_TIME
     * 
     * @return the value of ACC_INCOME_PAY.UPD_TIME
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.UPD_TIME
     * 
     * @param updTime the value for ACC_INCOME_PAY.UPD_TIME
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.DEL_OPER
     * 
     * @return the value of ACC_INCOME_PAY.DEL_OPER
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public String getDelOper() {
        return delOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.DEL_OPER
     * 
     * @param delOper the value for ACC_INCOME_PAY.DEL_OPER
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setDelOper(String delOper) {
        this.delOper = delOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.DEL_TIME
     * 
     * @return the value of ACC_INCOME_PAY.DEL_TIME
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.DEL_TIME
     * 
     * @param delTime the value for ACC_INCOME_PAY.DEL_TIME
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.DEL_FLAG
     * 
     * @return the value of ACC_INCOME_PAY.DEL_FLAG
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.DEL_FLAG
     * 
     * @param delFlag the value for ACC_INCOME_PAY.DEL_FLAG
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.AD_ID
     * 
     * @return the value of ACC_INCOME_PAY.AD_ID
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.AD_ID
     * 
     * @param adId the value for ACC_INCOME_PAY.AD_ID
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.MEMBER_ID
     * 
     * @return the value of ACC_INCOME_PAY.MEMBER_ID
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.MEMBER_ID
     * 
     * @param memberId the value for ACC_INCOME_PAY.MEMBER_ID
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.INCOME_PAY_TYPE
     * 
     * @return the value of ACC_INCOME_PAY.INCOME_PAY_TYPE
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public String getIncomePayType() {
        return incomePayType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.INCOME_PAY_TYPE
     * 
     * @param incomePayType the value for ACC_INCOME_PAY.INCOME_PAY_TYPE
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setIncomePayType(String incomePayType) {
        this.incomePayType = incomePayType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ACC_INCOME_PAY.STATUS
     * 
     * @return the value of ACC_INCOME_PAY.STATUS
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ACC_INCOME_PAY.STATUS
     * 
     * @param status the value for ACC_INCOME_PAY.STATUS
     * @ibatorgenerated Mon Feb 21 09:46:52 CST 2011
     */
    public void setStatus(String status) {
        this.status = status;
    }
}
