package com.mitian.airad.model;

public class AdinfoView {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ADINFO_VIEW.AD_ID
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    private Integer adId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ADINFO_VIEW.AD_GROUP_ID
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    private String adType;

    /**
     * @return the adType
     */
    public String getAdType() {
        return adType;
    }

    /**
     * @param adType the adType to set
     */
    public void setAdType(String adType) {
        this.adType = adType;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ADINFO_VIEW.AD_GROUP_ID
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    private Integer adGroupId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ADINFO_VIEW.CAMPAIGN_ID
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    private Integer campaignId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ADINFO_VIEW.ADVERTISER_ID
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    private Integer advertiserId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * ADINFO_VIEW.AGENT_ID
     * 
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    private Integer agentId;

    private Long memberId;

    private String appCode;

    /**
     * @return the appCode
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * @param appCode the appCode to set
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * @return the memberId
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * @param memberId the memberId to set
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ADINFO_VIEW.AD_ID
     * 
     * @return the value of ADINFO_VIEW.AD_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ADINFO_VIEW.AD_ID
     * 
     * @param adId the value for ADINFO_VIEW.AD_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ADINFO_VIEW.AD_GROUP_ID
     * 
     * @return the value of ADINFO_VIEW.AD_GROUP_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public Integer getAdGroupId() {
        return adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ADINFO_VIEW.AD_GROUP_ID
     * 
     * @param adGroupId the value for ADINFO_VIEW.AD_GROUP_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public void setAdGroupId(Integer adGroupId) {
        this.adGroupId = adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ADINFO_VIEW.CAMPAIGN_ID
     * 
     * @return the value of ADINFO_VIEW.CAMPAIGN_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public Integer getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ADINFO_VIEW.CAMPAIGN_ID
     * 
     * @param campaignId the value for ADINFO_VIEW.CAMPAIGN_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ADINFO_VIEW.ADVERTISER_ID
     * 
     * @return the value of ADINFO_VIEW.ADVERTISER_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public Integer getAdvertiserId() {
        return advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ADINFO_VIEW.ADVERTISER_ID
     * 
     * @param advertiserId the value for ADINFO_VIEW.ADVERTISER_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public void setAdvertiserId(Integer advertiserId) {
        this.advertiserId = advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * ADINFO_VIEW.AGENT_ID
     * 
     * @return the value of ADINFO_VIEW.AGENT_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * ADINFO_VIEW.AGENT_ID
     * 
     * @param agentId the value for ADINFO_VIEW.AGENT_ID
     * @ibatorgenerated Tue Feb 22 14:56:16 CST 2011
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }
}
