package com.mitian.airad.model;

import java.util.Date;

public class CoreClient {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.CLIENT_ID
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private Integer clientId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.DEVICE_TYPE
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String deviceType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.DEVICE_NAME
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String deviceName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.SIM_CARD
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String simCard;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CORE_CLIENT.S_ID
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String sId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.SYSTEM_VERSION
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String systemVersion;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.APP_CODE
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String appCode;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.APP_NAME
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String appName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.OPERATORS
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String operators;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.SDK_VERSION
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String sdkVersion;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.REQ_TIME
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private Date reqTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_CLIENT.SYSTEM
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String system;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CORE_CLIENT.PHONE
     * 
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    private String phone;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.CLIENT_ID
     * 
     * @return the value of CORE_CLIENT.CLIENT_ID
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.CLIENT_ID
     * 
     * @param clientId the value for CORE_CLIENT.CLIENT_ID
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.DEVICE_TYPE
     * 
     * @return the value of CORE_CLIENT.DEVICE_TYPE
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.DEVICE_TYPE
     * 
     * @param deviceType the value for CORE_CLIENT.DEVICE_TYPE
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.DEVICE_NAME
     * 
     * @return the value of CORE_CLIENT.DEVICE_NAME
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.DEVICE_NAME
     * 
     * @param deviceName the value for CORE_CLIENT.DEVICE_NAME
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.SIM_CARD
     * 
     * @return the value of CORE_CLIENT.SIM_CARD
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getSimCard() {
        return simCard;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.SIM_CARD
     * 
     * @param simCard the value for CORE_CLIENT.SIM_CARD
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setSimCard(String simCard) {
        this.simCard = simCard;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.S_ID
     * 
     * @return the value of CORE_CLIENT.S_ID
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.S_ID
     * 
     * @param sId the value for CORE_CLIENT.S_ID
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setsId(String sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.SYSTEM_VERSION
     * 
     * @return the value of CORE_CLIENT.SYSTEM_VERSION
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getSystemVersion() {
        return systemVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.SYSTEM_VERSION
     * 
     * @param systemVersion the value for CORE_CLIENT.SYSTEM_VERSION
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setSystemVersion(String systemVersion) {
        this.systemVersion = systemVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.APP_CODE
     * 
     * @return the value of CORE_CLIENT.APP_CODE
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.APP_CODE
     * 
     * @param appCode the value for CORE_CLIENT.APP_CODE
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.APP_NAME
     * 
     * @return the value of CORE_CLIENT.APP_NAME
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.APP_NAME
     * 
     * @param appName the value for CORE_CLIENT.APP_NAME
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.OPERATORS
     * 
     * @return the value of CORE_CLIENT.OPERATORS
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getOperators() {
        return operators;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.OPERATORS
     * 
     * @param operators the value for CORE_CLIENT.OPERATORS
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setOperators(String operators) {
        this.operators = operators;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.SDK_VERSION
     * 
     * @return the value of CORE_CLIENT.SDK_VERSION
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getSdkVersion() {
        return sdkVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.SDK_VERSION
     * 
     * @param sdkVersion the value for CORE_CLIENT.SDK_VERSION
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setSdkVersion(String sdkVersion) {
        this.sdkVersion = sdkVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.REQ_TIME
     * 
     * @return the value of CORE_CLIENT.REQ_TIME
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public Date getReqTime() {
        return reqTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.REQ_TIME
     * 
     * @param reqTime the value for CORE_CLIENT.REQ_TIME
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setReqTime(Date reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.SYSTEM
     * 
     * @return the value of CORE_CLIENT.SYSTEM
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.SYSTEM
     * 
     * @param system the value for CORE_CLIENT.SYSTEM
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setSystem(String system) {
        this.system = system;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_CLIENT.PHONE
     * 
     * @return the value of CORE_CLIENT.PHONE
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_CLIENT.PHONE
     * 
     * @param phone the value for CORE_CLIENT.PHONE
     * @ibatorgenerated Sat Feb 19 17:50:03 CST 2011
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}
