package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

public class CoreApp {

    /** 应用id not null */
    private Integer appId;
    /** 会员id not null */
    private Long memberId;
    /** 应用名称 */
    private String appName;
    /** 分类 */
    private String appType;
    /** 使用平台 */
    private String appPlatformType;
    /** 用户年龄段 */
    private String userAgePag;
    /** 下载地址 */
    private String downUrl;
    /** 描述 */
    private String appDesc;
    /** 状态 */
    private String appStatus;
    /** 审核/草稿标志 */
    private String flag;
    /** 冻结标志 */
    private String blocking;
    /** 添加人 */
    private String addOper;
    /** 更新时间 */
    private Date addTime;
    /** 更新人 */
    private String updOper;
    /** 更新时间 */
    private Date updTime;
    /** 删除人 */
    private String delOper;
    /** 删除时间 */
    private Date delTime;
    /** 删除标志 */
    private String delFlag;
    /** 用户性别 */
    private String userSex;
    /** 用户群体 */
    private String userGroup;
    private String sendScope;
    private String identiCode;
    /** admob的publishcode */
    private String admobCode;
    private String pubOutside;
    /** 发布Id（唯一） */
    private String appCode;
    private String appTypeMpid;
    /** 点击数 */
    private Integer clickNum;
    /** 展示数 */
    private Integer showNum;
    /** 收益 */
    private BigDecimal offer;
    /** 请求数 */
    private Integer maxNum;
    /** 投放率 */
    private BigDecimal putRate;
    /** 点击率 */
    private BigDecimal clickRate;
    /** 当天添加的应用数 */
    private int count;
    /** 统计结束时间 */
    private Date reportEndTime;
    /** 统计开始时间 */
    private Date reportStartTime;

    /**
     * 会员
     */
    private String email;

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.APP_ID
     * 
     * @return the value of CORE_APP.APP_ID
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.APP_ID
     * 
     * @param appId the value for CORE_APP.APP_ID
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.MEMBER_ID
     * 
     * @return the value of CORE_APP.MEMBER_ID
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.MEMBER_ID
     * 
     * @param memberId the value for CORE_APP.MEMBER_ID
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.APP_NAME
     * 
     * @return the value of CORE_APP.APP_NAME
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.APP_NAME
     * 
     * @param appName the value for CORE_APP.APP_NAME
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.APP_TYPE
     * 
     * @return the value of CORE_APP.APP_TYPE
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.APP_TYPE
     * 
     * @param appType the value for CORE_APP.APP_TYPE
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setAppType(String appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.APP_PLATFORM_TYPE
     * 
     * @return the value of CORE_APP.APP_PLATFORM_TYPE
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getAppPlatformType() {
        return appPlatformType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.APP_PLATFORM_TYPE
     * 
     * @param appPlatformType the value for CORE_APP.APP_PLATFORM_TYPE
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setAppPlatformType(String appPlatformType) {
        this.appPlatformType = appPlatformType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.USER_GROUP
     * 
     * @return the value of CORE_APP.USER_GROUP
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getUserGroup() {
        return userGroup;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.USER_GROUP
     * 
     * @param userGroup the value for CORE_APP.USER_GROUP
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setUserGroup(String userGroup) {
        this.userGroup = userGroup;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.USER_AGE_PAG
     * 
     * @return the value of CORE_APP.USER_AGE_PAG
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getUserAgePag() {
        return userAgePag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.USER_AGE_PAG
     * 
     * @param userAgePag the value for CORE_APP.USER_AGE_PAG
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setUserAgePag(String userAgePag) {
        this.userAgePag = userAgePag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.DOWN_URL
     * 
     * @return the value of CORE_APP.DOWN_URL
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getDownUrl() {
        return downUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.DOWN_URL
     * 
     * @param downUrl the value for CORE_APP.DOWN_URL
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setDownUrl(String downUrl) {
        this.downUrl = downUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.SEND_SCOPE
     * 
     * @return the value of CORE_APP.SEND_SCOPE
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getSendScope() {
        return sendScope;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.SEND_SCOPE
     * 
     * @param sendScope the value for CORE_APP.SEND_SCOPE
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setSendScope(String sendScope) {
        this.sendScope = sendScope;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.IDENTI_CODE
     * 
     * @return the value of CORE_APP.IDENTI_CODE
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getIdentiCode() {
        return identiCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.IDENTI_CODE
     * 
     * @param identiCode the value for CORE_APP.IDENTI_CODE
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setIdentiCode(String identiCode) {
        this.identiCode = identiCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.APP_DESC
     * 
     * @return the value of CORE_APP.APP_DESC
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getAppDesc() {
        return appDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.APP_DESC
     * 
     * @param appDesc the value for CORE_APP.APP_DESC
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setAppDesc(String appDesc) {
        this.appDesc = appDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.APP_STATUS
     * 
     * @return the value of CORE_APP.APP_STATUS
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.APP_STATUS
     * 
     * @param appStatus the value for CORE_APP.APP_STATUS
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.FLAG
     * 
     * @return the value of CORE_APP.FLAG
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.FLAG
     * 
     * @param flag the value for CORE_APP.FLAG
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.BLOCKING
     * 
     * @return the value of CORE_APP.BLOCKING
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getBlocking() {
        return blocking;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.BLOCKING
     * 
     * @param blocking the value for CORE_APP.BLOCKING
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setBlocking(String blocking) {
        this.blocking = blocking;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.ADD_OPER
     * 
     * @return the value of CORE_APP.ADD_OPER
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getAddOper() {
        return addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.ADD_OPER
     * 
     * @param addOper the value for CORE_APP.ADD_OPER
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setAddOper(String addOper) {
        this.addOper = addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.ADD_TIME
     * 
     * @return the value of CORE_APP.ADD_TIME
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.ADD_TIME
     * 
     * @param addTime the value for CORE_APP.ADD_TIME
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.UPD_OPER
     * 
     * @return the value of CORE_APP.UPD_OPER
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getUpdOper() {
        return updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.UPD_OPER
     * 
     * @param updOper the value for CORE_APP.UPD_OPER
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setUpdOper(String updOper) {
        this.updOper = updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.UPD_TIME
     * 
     * @return the value of CORE_APP.UPD_TIME
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.UPD_TIME
     * 
     * @param updTime the value for CORE_APP.UPD_TIME
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.DEL_OPER
     * 
     * @return the value of CORE_APP.DEL_OPER
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getDelOper() {
        return delOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.DEL_OPER
     * 
     * @param delOper the value for CORE_APP.DEL_OPER
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setDelOper(String delOper) {
        this.delOper = delOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.DEL_TIME
     * 
     * @return the value of CORE_APP.DEL_TIME
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.DEL_TIME
     * 
     * @param delTime the value for CORE_APP.DEL_TIME
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_APP.DEL_FLAG
     * 
     * @return the value of CORE_APP.DEL_FLAG
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_APP.DEL_FLAG
     * 
     * @param delFlag the value for CORE_APP.DEL_FLAG
     * @ibatorgenerated Thu Jan 20 16:39:10 CST 2011
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * @return the userSex
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * @param userSex the userSex to set
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * @return the admobCode
     */
    public String getAdmobCode() {
        return admobCode;
    }

    /**
     * @param admobCode the admobCode to set
     */
    public void setAdmobCode(String admobCode) {
        this.admobCode = admobCode;
    }

    /**
     * @return the appCode
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * @param appCode the appCode to set
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * @return the appTypeMpid
     */
    public String getAppTypeMpid() {
        return appTypeMpid;
    }

    /**
     * @param appTypeMpid the appTypeMpid to set
     */
    public void setAppTypeMpid(String appTypeMpid) {
        this.appTypeMpid = appTypeMpid;
    }

    /**
     * @return the pubOutside
     */
    public String getPubOutside() {
        return pubOutside;
    }

    /**
     * @param pubOutside the pubOutside to set
     */
    public void setPubOutside(String pubOutside) {
        this.pubOutside = pubOutside;
    }

    /**
     * @return the clickNum
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * @param clickNum the clickNum to set
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    /**
     * @return the showNum
     */
    public Integer getShowNum() {
        return showNum;
    }

    /**
     * @param showNum the showNum to set
     */
    public void setShowNum(Integer showNum) {
        this.showNum = showNum;
    }

    /**
     * @return the offer
     */
    public BigDecimal getOffer() {
        return offer;
    }

    /**
     * @param offer the offer to set
     */
    public void setOffer(BigDecimal offer) {
        this.offer = offer;
    }

    /**
     * @return the putRate
     */
    public BigDecimal getPutRate() {
        return putRate;
    }

    /**
     * @param putRate the putRate to set
     */
    public void setPutRate(BigDecimal putRate) {
        this.putRate = putRate;
    }

    /**
     * @return the clickRate
     */
    public BigDecimal getClickRate() {
        return clickRate;
    }

    /**
     * @param clickRate the clickRate to set
     */
    public void setClickRate(BigDecimal clickRate) {
        this.clickRate = clickRate;
    }

    /**
     * @return the maxNum
     */
    public Integer getMaxNum() {
        return maxNum;
    }

    /**
     * @param maxNum the maxNum to set
     */
    public void setMaxNum(Integer maxNum) {
        this.maxNum = maxNum;
    }

    /**
     * @return the count
     */
    public int getCount() {
        return count;
    }

    /**
     * @param count the count to set
     */
    public void setCount(int count) {
        this.count = count;
    }

    /**
     * @return the reportEndTime
     */
    public Date getReportEndTime() {
        return reportEndTime;
    }

    /**
     * @param reportEndTime the reportEndTime to set
     */
    public void setReportEndTime(Date reportEndTime) {
        this.reportEndTime = reportEndTime;
    }

    /**
     * @return the reportStartTime
     */
    public Date getReportStartTime() {
        return reportStartTime;
    }

    /**
     * @param reportStartTime the reportStartTime to set
     */
    public void setReportStartTime(Date reportStartTime) {
        this.reportStartTime = reportStartTime;
    }

}
