package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

public class StatAgent {
    private String reqTime;
    private String inAdvertiserId;
    private String reqTimeEnd;

    /**
     * @return the reqTimeEnd
     */
    public String getReqTimeEnd() {
        return reqTimeEnd;
    }

    /**
     * @param reqTimeEnd the reqTimeEnd to set
     */
    public void setReqTimeEnd(String reqTimeEnd) {
        this.reqTimeEnd = reqTimeEnd;
    }

    private Date jobStatTime;
    private String jobStatType;
    private int startPag;
    private int endPag;
    private String flag;

    /**
     * @return the flag
     */
    public String getFlag() {
        return flag;
    }

    /**
     * @param flag the flag to set
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * @return the startPag
     */
    public int getStartPag() {
        return startPag;
    }

    /**
     * @param startPag the startPag to set
     */
    public void setStartPag(int startPag) {
        this.startPag = startPag;
    }

    /**
     * @return the endPag
     */
    public int getEndPag() {
        return endPag;
    }

    /**
     * @param endPag the endPag to set
     */
    public void setEndPag(int endPag) {
        this.endPag = endPag;
    }

    /**
     * @return the jobStatTime
     */
    public Date getJobStatTime() {
        return jobStatTime;
    }

    /**
     * @param jobStatTime the jobStatTime to set
     */
    public void setJobStatTime(Date jobStatTime) {
        this.jobStatTime = jobStatTime;
    }

    /**
     * @return the jobStatType
     */
    public String getJobStatType() {
        return jobStatType;
    }

    /**
     * @param jobStatType the jobStatType to set
     */
    public void setJobStatType(String jobStatType) {
        this.jobStatType = jobStatType;
    }

    /**
     * @return the inAdvertiserId
     */
    public String getInAdvertiserId() {
        return inAdvertiserId;
    }

    /**
     * @param inAdvertiserId the inAdvertiserId to set
     */
    public void setInAdvertiserId(String inAdvertiserId) {
        this.inAdvertiserId = inAdvertiserId;
    }

    /**
     * @return the reqTime
     */
    public String getReqTime() {
        return reqTime;
    }

    /**
     * @param reqTime the reqTime to set
     */
    public void setReqTime(String reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.SHAT_ANGEN_ID
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private Integer shatAngenId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.ADVERTISER_ID
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private Integer advertiserId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.ADVERTISER_NAME
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private String advertiserName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.AD_NAME
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private String adName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.AGENT_ID
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private Integer agentId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_AGENT.AD_ID
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private Integer adId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.SHOW_NUM
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private Integer showNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.CLICK_NUM
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private Integer clickNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_AGENT.OFFER
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private BigDecimal offer;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.ADD_TIME
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_AGENT.CREATE_TIME
     * 
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    private Date createTime;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.SHAT_ANGEN_ID
     * 
     * @return the value of STAT_AGENT.SHAT_ANGEN_ID
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public Integer getShatAngenId() {
        return shatAngenId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.SHAT_ANGEN_ID
     * 
     * @param shatAngenId the value for STAT_AGENT.SHAT_ANGEN_ID
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setShatAngenId(Integer shatAngenId) {
        this.shatAngenId = shatAngenId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.ADVERTISER_ID
     * 
     * @return the value of STAT_AGENT.ADVERTISER_ID
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public Integer getAdvertiserId() {
        return advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.ADVERTISER_ID
     * 
     * @param advertiserId the value for STAT_AGENT.ADVERTISER_ID
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setAdvertiserId(Integer advertiserId) {
        this.advertiserId = advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.ADVERTISER_NAME
     * 
     * @return the value of STAT_AGENT.ADVERTISER_NAME
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public String getAdvertiserName() {
        return advertiserName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.ADVERTISER_NAME
     * 
     * @param advertiserName the value for STAT_AGENT.ADVERTISER_NAME
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setAdvertiserName(String advertiserName) {
        this.advertiserName = advertiserName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.AD_NAME
     * 
     * @return the value of STAT_AGENT.AD_NAME
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.AD_NAME
     * 
     * @param adName the value for STAT_AGENT.AD_NAME
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setAdName(String adName) {
        this.adName = adName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.AGENT_ID
     * 
     * @return the value of STAT_AGENT.AGENT_ID
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.AGENT_ID
     * 
     * @param agentId the value for STAT_AGENT.AGENT_ID
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.AD_ID
     * 
     * @return the value of STAT_AGENT.AD_ID
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.AD_ID
     * 
     * @param adId the value for STAT_AGENT.AD_ID
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.SHOW_NUM
     * 
     * @return the value of STAT_AGENT.SHOW_NUM
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public Integer getShowNum() {
        return showNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.SHOW_NUM
     * 
     * @param showNum the value for STAT_AGENT.SHOW_NUM
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setShowNum(Integer showNum) {
        this.showNum = showNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.CLICK_NUM
     * 
     * @return the value of STAT_AGENT.CLICK_NUM
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.CLICK_NUM
     * 
     * @param clickNum the value for STAT_AGENT.CLICK_NUM
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.OFFER
     * 
     * @return the value of STAT_AGENT.OFFER
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public BigDecimal getOffer() {
        return offer;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.OFFER
     * 
     * @param offer the value for STAT_AGENT.OFFER
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setOffer(BigDecimal offer) {
        this.offer = offer;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.ADD_TIME
     * 
     * @return the value of STAT_AGENT.ADD_TIME
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.ADD_TIME
     * 
     * @param addTime the value for STAT_AGENT.ADD_TIME
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_AGENT.CREATE_TIME
     * 
     * @return the value of STAT_AGENT.CREATE_TIME
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_AGENT.CREATE_TIME
     * 
     * @param createTime the value for STAT_AGENT.CREATE_TIME
     * @ibatorgenerated Thu Mar 10 14:17:51 CST 2011
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
