package com.mitian.airad.model;

import java.util.Date;

public class BssUserInfo {

    /** 添加时间 */
    private String addT;
    /** 更新时间 */
    private String updateT;

    public String getAddT() {
        return addT;
    }

    public void setAddT(String addT) {
        this.addT = addT;
    }

    public String getUpdateT() {
        return updateT;
    }

    public void setUpdateT(String updateT) {
        this.updateT = updateT;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.USER_ID
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.USER_NAME
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.LOGIN_NAME
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private String loginName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.PASSWORD
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.ADDRESS
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private String address;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.PHONE
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private String phone;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.DEPARTMENT
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private String department;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.ROLE
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private String role;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.ADD_TIME
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.ADD_OPER
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private Integer addOper;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.UPD_TIME
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private Date updTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.UPD_OPER
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private Integer updOper;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * BSS_USER_INFO.USER_STATUS
     * 
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    private String userStatus;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.USER_ID
     * 
     * @return the value of BSS_USER_INFO.USER_ID
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.USER_ID
     * 
     * @param userId the value for BSS_USER_INFO.USER_ID
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.USER_NAME
     * 
     * @return the value of BSS_USER_INFO.USER_NAME
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.USER_NAME
     * 
     * @param userName the value for BSS_USER_INFO.USER_NAME
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.LOGIN_NAME
     * 
     * @return the value of BSS_USER_INFO.LOGIN_NAME
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.LOGIN_NAME
     * 
     * @param loginName the value for BSS_USER_INFO.LOGIN_NAME
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.PASSWORD
     * 
     * @return the value of BSS_USER_INFO.PASSWORD
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.PASSWORD
     * 
     * @param password the value for BSS_USER_INFO.PASSWORD
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.ADDRESS
     * 
     * @return the value of BSS_USER_INFO.ADDRESS
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.ADDRESS
     * 
     * @param address the value for BSS_USER_INFO.ADDRESS
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.PHONE
     * 
     * @return the value of BSS_USER_INFO.PHONE
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.PHONE
     * 
     * @param phone the value for BSS_USER_INFO.PHONE
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.DEPARTMENT
     * 
     * @return the value of BSS_USER_INFO.DEPARTMENT
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.DEPARTMENT
     * 
     * @param department the value for BSS_USER_INFO.DEPARTMENT
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.ROLE
     * 
     * @return the value of BSS_USER_INFO.ROLE
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.ROLE
     * 
     * @param role the value for BSS_USER_INFO.ROLE
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.ADD_TIME
     * 
     * @return the value of BSS_USER_INFO.ADD_TIME
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.ADD_TIME
     * 
     * @param addTime the value for BSS_USER_INFO.ADD_TIME
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.ADD_OPER
     * 
     * @return the value of BSS_USER_INFO.ADD_OPER
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public Integer getAddOper() {
        return addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.ADD_OPER
     * 
     * @param addOper the value for BSS_USER_INFO.ADD_OPER
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setAddOper(Integer addOper) {
        this.addOper = addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.UPD_TIME
     * 
     * @return the value of BSS_USER_INFO.UPD_TIME
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.UPD_TIME
     * 
     * @param updTime the value for BSS_USER_INFO.UPD_TIME
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.UPD_OPER
     * 
     * @return the value of BSS_USER_INFO.UPD_OPER
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public Integer getUpdOper() {
        return updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.UPD_OPER
     * 
     * @param updOper the value for BSS_USER_INFO.UPD_OPER
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setUpdOper(Integer updOper) {
        this.updOper = updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * BSS_USER_INFO.USER_STATUS
     * 
     * @return the value of BSS_USER_INFO.USER_STATUS
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * BSS_USER_INFO.USER_STATUS
     * 
     * @param userStatus the value for BSS_USER_INFO.USER_STATUS
     * @ibatorgenerated Fri Mar 11 16:21:57 CST 2011
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }
}
