package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

public class CoreMoneyCount {
    /**
     * id
     */
    private Integer id;

    /**
     * 流水号
     */
    private Integer serialId;

    /**
     * 会员id
     */
    private Long memberId;

    /**
     *跟新时间
     */
    private Date updTime;

    /**
     * 转换金额
     */
    private BigDecimal rechargeCount;

    /**
     * 支出金额
     */
    private BigDecimal payCount;

    /**
     * 收入金额
     */
    private BigDecimal incomeCount;

    /**
     * 给广告商充值金额
     */
    private BigDecimal agentCount;

    /**
     * 状态
     */
    private String status;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.ID
     * 
     * @return the value of CORE_MONEY_COUNT.ID
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.ID
     * 
     * @param id the value for CORE_MONEY_COUNT.ID
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.SERIAL_ID
     * 
     * @return the value of CORE_MONEY_COUNT.SERIAL_ID
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public Integer getSerialId() {
        return serialId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.SERIAL_ID
     * 
     * @param serialId the value for CORE_MONEY_COUNT.SERIAL_ID
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setSerialId(Integer serialId) {
        this.serialId = serialId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.MEMBER_ID
     * 
     * @return the value of CORE_MONEY_COUNT.MEMBER_ID
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.MEMBER_ID
     * 
     * @param memberId the value for CORE_MONEY_COUNT.MEMBER_ID
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.UPD_TIME
     * 
     * @return the value of CORE_MONEY_COUNT.UPD_TIME
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.UPD_TIME
     * 
     * @param updTime the value for CORE_MONEY_COUNT.UPD_TIME
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.RECHARGE_COUNT
     * 
     * @return the value of CORE_MONEY_COUNT.RECHARGE_COUNT
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public BigDecimal getRechargeCount() {
        return rechargeCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.RECHARGE_COUNT
     * 
     * @param rechargeCount the value for CORE_MONEY_COUNT.RECHARGE_COUNT
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setRechargeCount(BigDecimal rechargeCount) {
        this.rechargeCount = rechargeCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.PAY_COUNT
     * 
     * @return the value of CORE_MONEY_COUNT.PAY_COUNT
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public BigDecimal getPayCount() {
        return payCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.PAY_COUNT
     * 
     * @param payCount the value for CORE_MONEY_COUNT.PAY_COUNT
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setPayCount(BigDecimal payCount) {
        this.payCount = payCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.INCOME_COUNT
     * 
     * @return the value of CORE_MONEY_COUNT.INCOME_COUNT
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public BigDecimal getIncomeCount() {
        return incomeCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.INCOME_COUNT
     * 
     * @param incomeCount the value for CORE_MONEY_COUNT.INCOME_COUNT
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setIncomeCount(BigDecimal incomeCount) {
        this.incomeCount = incomeCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.AGENT_COUNT
     * 
     * @return the value of CORE_MONEY_COUNT.AGENT_COUNT
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public BigDecimal getAgentCount() {
        return agentCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.AGENT_COUNT
     * 
     * @param agentCount the value for CORE_MONEY_COUNT.AGENT_COUNT
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setAgentCount(BigDecimal agentCount) {
        this.agentCount = agentCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_MONEY_COUNT.STATUS
     * 
     * @return the value of CORE_MONEY_COUNT.STATUS
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_MONEY_COUNT.STATUS
     * 
     * @param status the value for CORE_MONEY_COUNT.STATUS
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void setStatus(String status) {
        this.status = status;
    }
}
