package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class CoreAdGroup {

    /** 点击数 */
    private Integer clickNum;
    /** 展示数 */
    private Integer showNum;
    /** 点击率 */
    private BigDecimal clickRate;
    /** 成本 */
    private BigDecimal cost;
    /** 平均点击成本 */
    private BigDecimal avgClick;
    /** 统计时间 */
    private Date statisticTime;
    /** 平台个数 */
    private Integer platformNumber;
    /** 系统个数 */
    private Integer osNumber;
    /** 平添描述 */
    private String adLoclTypeTitle;
    /** 广告组下广告数量 */
    private int cnt;
    /**
     * 冻结的广告数
     */
    private String blockingCount;
    /**
     * 发布的广告数
     */
    private String issuCount;
    /**
     * 暂停的广告数
     */
    private String suspendCount;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_GROUP_ID
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private Integer adGroupId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.CAMPAIGN_ID
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private Integer campaignId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_GROUP_NAME
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adGroupName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_TAG_TYPE
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adTagType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_LOCL_TYPE
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adLoclType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_LOCL_INFO
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adLoclInfo;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_FLOW_INFO
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adFlowInfo;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.CHANGCE_INFO
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String changceInfo;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_TAG_SEX
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adTagSex;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_TAG_AGE
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adTagAge;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_TAG_SOFT_TYPE
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adTagSoftType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_TAG_SP
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adTagSp;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.BLOCKING
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String blocking;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.SUSPEND_TYPE
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String suspendType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.ADD_OPER
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String addOper;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.ADD_TIME
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private Date addTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.UPD_OPER
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String updOper;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.UPD_TIME
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private Date updTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.DEL_OPER
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String delOper;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.DEL_TIME
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private Date delTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.DEL_FLAG
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String delFlag;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.MEMBER_ID
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private Long memberId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_AD_GROUP.AD_TAG_SP_VS
     * 
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    private String adTagSpVs;
    /** 开始时间 */
    private Date startTime;
    /** 结束时间 */
    private Date endTime;
    /** 广告列表 */
    private List<CoreAdvertiser> coreAdvertisers;
    // 广告活动名称
    private String campaignName;
    /** 返回的活动组ID主健 wendong.Gao */
    private Long id;//

    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the startTime
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * @param startTime the startTime to set
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * @return the endTime
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * @param endTime the endTime to set
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * @return the coreAdvertisers
     */
    public List<CoreAdvertiser> getCoreAdvertisers() {
        return coreAdvertisers;
    }

    /**
     * @param coreAdvertisers the coreAdvertisers to set
     */
    public void setCoreAdvertisers(List<CoreAdvertiser> coreAdvertisers) {
        this.coreAdvertisers = coreAdvertisers;
    }

    /**
     * @return the campaignName
     */
    public String getCampaignName() {
        return campaignName;
    }

    /**
     * @param campaignName the campaignName to set
     */
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_GROUP_ID
     * 
     * @return the value of CORE_AD_GROUP.AD_GROUP_ID
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public Integer getAdGroupId() {
        return adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_GROUP_ID
     * 
     * @param adGroupId the value for CORE_AD_GROUP.AD_GROUP_ID
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdGroupId(Integer adGroupId) {
        this.adGroupId = adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.CAMPAIGN_ID
     * 
     * @return the value of CORE_AD_GROUP.CAMPAIGN_ID
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public Integer getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.CAMPAIGN_ID
     * 
     * @param campaignId the value for CORE_AD_GROUP.CAMPAIGN_ID
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_GROUP_NAME
     * 
     * @return the value of CORE_AD_GROUP.AD_GROUP_NAME
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdGroupName() {
        return adGroupName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_GROUP_NAME
     * 
     * @param adGroupName the value for CORE_AD_GROUP.AD_GROUP_NAME
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdGroupName(String adGroupName) {
        this.adGroupName = adGroupName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_TAG_TYPE
     * 
     * @return the value of CORE_AD_GROUP.AD_TAG_TYPE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdTagType() {
        return adTagType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_TAG_TYPE
     * 
     * @param adTagType the value for CORE_AD_GROUP.AD_TAG_TYPE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdTagType(String adTagType) {
        this.adTagType = adTagType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_LOCL_TYPE
     * 
     * @return the value of CORE_AD_GROUP.AD_LOCL_TYPE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdLoclType() {
        return adLoclType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_LOCL_TYPE
     * 
     * @param adLoclType the value for CORE_AD_GROUP.AD_LOCL_TYPE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdLoclType(String adLoclType) {
        this.adLoclType = adLoclType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_LOCL_INFO
     * 
     * @return the value of CORE_AD_GROUP.AD_LOCL_INFO
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdLoclInfo() {
        return adLoclInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_LOCL_INFO
     * 
     * @param adLoclInfo the value for CORE_AD_GROUP.AD_LOCL_INFO
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdLoclInfo(String adLoclInfo) {
        this.adLoclInfo = adLoclInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_FLOW_INFO
     * 
     * @return the value of CORE_AD_GROUP.AD_FLOW_INFO
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdFlowInfo() {
        return adFlowInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_FLOW_INFO
     * 
     * @param adFlowInfo the value for CORE_AD_GROUP.AD_FLOW_INFO
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdFlowInfo(String adFlowInfo) {
        this.adFlowInfo = adFlowInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.CHANGCE_INFO
     * 
     * @return the value of CORE_AD_GROUP.CHANGCE_INFO
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getChangceInfo() {
        return changceInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.CHANGCE_INFO
     * 
     * @param changceInfo the value for CORE_AD_GROUP.CHANGCE_INFO
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setChangceInfo(String changceInfo) {
        this.changceInfo = changceInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_TAG_SEX
     * 
     * @return the value of CORE_AD_GROUP.AD_TAG_SEX
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdTagSex() {
        return adTagSex;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_TAG_SEX
     * 
     * @param adTagSex the value for CORE_AD_GROUP.AD_TAG_SEX
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdTagSex(String adTagSex) {
        this.adTagSex = adTagSex;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_TAG_AGE
     * 
     * @return the value of CORE_AD_GROUP.AD_TAG_AGE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdTagAge() {
        return adTagAge;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_TAG_AGE
     * 
     * @param adTagAge the value for CORE_AD_GROUP.AD_TAG_AGE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdTagAge(String adTagAge) {
        this.adTagAge = adTagAge;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_TAG_SOFT_TYPE
     * 
     * @return the value of CORE_AD_GROUP.AD_TAG_SOFT_TYPE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdTagSoftType() {
        return adTagSoftType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_TAG_SOFT_TYPE
     * 
     * @param adTagSoftType the value for CORE_AD_GROUP.AD_TAG_SOFT_TYPE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdTagSoftType(String adTagSoftType) {
        this.adTagSoftType = adTagSoftType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_TAG_SP
     * 
     * @return the value of CORE_AD_GROUP.AD_TAG_SP
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdTagSp() {
        return adTagSp;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_TAG_SP
     * 
     * @param adTagSp the value for CORE_AD_GROUP.AD_TAG_SP
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdTagSp(String adTagSp) {
        this.adTagSp = adTagSp;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.BLOCKING
     * 
     * @return the value of CORE_AD_GROUP.BLOCKING
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getBlocking() {
        return blocking;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.BLOCKING
     * 
     * @param blocking the value for CORE_AD_GROUP.BLOCKING
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setBlocking(String blocking) {
        this.blocking = blocking;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.SUSPEND_TYPE
     * 
     * @return the value of CORE_AD_GROUP.SUSPEND_TYPE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getSuspendType() {
        return suspendType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.SUSPEND_TYPE
     * 
     * @param suspendType the value for CORE_AD_GROUP.SUSPEND_TYPE
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setSuspendType(String suspendType) {
        this.suspendType = suspendType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.ADD_OPER
     * 
     * @return the value of CORE_AD_GROUP.ADD_OPER
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAddOper() {
        return addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.ADD_OPER
     * 
     * @param addOper the value for CORE_AD_GROUP.ADD_OPER
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAddOper(String addOper) {
        this.addOper = addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.ADD_TIME
     * 
     * @return the value of CORE_AD_GROUP.ADD_TIME
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.ADD_TIME
     * 
     * @param addTime the value for CORE_AD_GROUP.ADD_TIME
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.UPD_OPER
     * 
     * @return the value of CORE_AD_GROUP.UPD_OPER
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getUpdOper() {
        return updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.UPD_OPER
     * 
     * @param updOper the value for CORE_AD_GROUP.UPD_OPER
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setUpdOper(String updOper) {
        this.updOper = updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.UPD_TIME
     * 
     * @return the value of CORE_AD_GROUP.UPD_TIME
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.UPD_TIME
     * 
     * @param updTime the value for CORE_AD_GROUP.UPD_TIME
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.DEL_OPER
     * 
     * @return the value of CORE_AD_GROUP.DEL_OPER
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getDelOper() {
        return delOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.DEL_OPER
     * 
     * @param delOper the value for CORE_AD_GROUP.DEL_OPER
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setDelOper(String delOper) {
        this.delOper = delOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.DEL_TIME
     * 
     * @return the value of CORE_AD_GROUP.DEL_TIME
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.DEL_TIME
     * 
     * @param delTime the value for CORE_AD_GROUP.DEL_TIME
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.DEL_FLAG
     * 
     * @return the value of CORE_AD_GROUP.DEL_FLAG
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.DEL_FLAG
     * 
     * @param delFlag the value for CORE_AD_GROUP.DEL_FLAG
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.MEMBER_ID
     * 
     * @return the value of CORE_AD_GROUP.MEMBER_ID
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.MEMBER_ID
     * 
     * @param memberId the value for CORE_AD_GROUP.MEMBER_ID
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_AD_GROUP.AD_TAG_SP_VS
     * 
     * @return the value of CORE_AD_GROUP.AD_TAG_SP_VS
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public String getAdTagSpVs() {
        return adTagSpVs;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_AD_GROUP.AD_TAG_SP_VS
     * 
     * @param adTagSpVs the value for CORE_AD_GROUP.AD_TAG_SP_VS
     * @ibatorgenerated Tue Jan 25 17:28:52 CST 2011
     */
    public void setAdTagSpVs(String adTagSpVs) {
        this.adTagSpVs = adTagSpVs;
    }

    /**
     * @return the clickNum
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * @param clickNum the clickNum to set
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    /**
     * @return the showNum
     */
    public Integer getShowNum() {
        return showNum;
    }

    /**
     * @param showNum the showNum to set
     */
    public void setShowNum(Integer showNum) {
        this.showNum = showNum;
    }

    /**
     * @return the clickRate
     */
    public BigDecimal getClickRate() {
        return clickRate;
    }

    /**
     * @param clickRate the clickRate to set
     */
    public void setClickRate(BigDecimal clickRate) {
        this.clickRate = clickRate;
    }

    /**
     * @return the cost
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * @param cost the cost to set
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * @return the avgClick
     */
    public BigDecimal getAvgClick() {
        return avgClick;
    }

    /**
     * @param avgClick the avgClick to set
     */
    public void setAvgClick(BigDecimal avgClick) {
        this.avgClick = avgClick;
    }

    /**
     * @return the statisticTime
     */
    public Date getStatisticTime() {
        return statisticTime;
    }

    /**
     * @param statisticTime the statisticTime to set
     */
    public void setStatisticTime(Date statisticTime) {
        this.statisticTime = statisticTime;
    }

    /**
     * @param platformNumber the platformNumber to set
     */
    public void setPlatformNumber(Integer platformNumber) {
        this.platformNumber = platformNumber;
    }

    /**
     * @return the platformNumber
     */
    public Integer getPlatformNumber() {
        return platformNumber;
    }

    /**
     * @param osNumber the osNumber to set
     */
    public void setOsNumber(Integer osNumber) {
        this.osNumber = osNumber;
    }

    /**
     * @return the osNumber
     */
    public Integer getOsNumber() {
        return osNumber;
    }

    /**
     * @param adLoclTypeTitle the adLoclTypeTitle to set
     */
    public void setAdLoclTypeTitle(String adLoclTypeTitle) {
        this.adLoclTypeTitle = adLoclTypeTitle;
    }

    /**
     * @return the adLoclTypeTitle
     */
    public String getAdLoclTypeTitle() {
        return adLoclTypeTitle;
    }

    /**
     * @return the cnt
     */
    public int getCnt() {
        return cnt;
    }

    /**
     * @param cnt the cnt to set
     */
    public void setCnt(int cnt) {
        this.cnt = cnt;
    }

    /**
     * @return the blockingCount
     */
    public String getBlockingCount() {
        return blockingCount;
    }

    /**
     * @param blockingCount the blockingCount to set
     */
    public void setBlockingCount(String blockingCount) {
        this.blockingCount = blockingCount;
    }

    /**
     * @return the issuCount
     */
    public String getIssuCount() {
        return issuCount;
    }

    /**
     * @param issuCount the issuCount to set
     */
    public void setIssuCount(String issuCount) {
        this.issuCount = issuCount;
    }

    /**
     * @return the suspendCount
     */
    public String getSuspendCount() {
        return suspendCount;
    }

    /**
     * @param suspendCount the suspendCount to set
     */
    public void setSuspendCount(String suspendCount) {
        this.suspendCount = suspendCount;
    }

}
