package com.mitian.airad.model;

public class LibImg {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LIB_IMG.IMG_ID
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private Integer imgId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LIB_IMG.REL_ID
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private Integer relId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_IMG.SOURCE_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private Integer sourceType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LIB_IMG.IMG_NAME
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private String imgName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LIB_IMG.IMG_TYPE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private Integer imgType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_IMG.IMG_HEIGHT
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private Integer imgHeight;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LIB_IMG.IMG_WIDE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private Integer imgWide;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LIB_IMG.IMG_CODE
     * 
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    private byte[] imgCode;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG.IMG_ID
     * 
     * @return the value of LIB_IMG.IMG_ID
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG.IMG_ID
     * 
     * @param imgId the value for LIB_IMG.IMG_ID
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG.REL_ID
     * 
     * @return the value of LIB_IMG.REL_ID
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public Integer getRelId() {
        return relId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG.REL_ID
     * 
     * @param relId the value for LIB_IMG.REL_ID
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setRelId(Integer relId) {
        this.relId = relId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG.SOURCE_TYPE
     * 
     * @return the value of LIB_IMG.SOURCE_TYPE
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG.SOURCE_TYPE
     * 
     * @param sourceType the value for LIB_IMG.SOURCE_TYPE
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG.IMG_NAME
     * 
     * @return the value of LIB_IMG.IMG_NAME
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG.IMG_NAME
     * 
     * @param imgName the value for LIB_IMG.IMG_NAME
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG.IMG_TYPE
     * 
     * @return the value of LIB_IMG.IMG_TYPE
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public Integer getImgType() {
        return imgType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG.IMG_TYPE
     * 
     * @param imgType the value for LIB_IMG.IMG_TYPE
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgType(Integer imgType) {
        this.imgType = imgType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG.IMG_HEIGHT
     * 
     * @return the value of LIB_IMG.IMG_HEIGHT
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public Integer getImgHeight() {
        return imgHeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG.IMG_HEIGHT
     * 
     * @param imgHeight the value for LIB_IMG.IMG_HEIGHT
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgHeight(Integer imgHeight) {
        this.imgHeight = imgHeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG.IMG_WIDE
     * 
     * @return the value of LIB_IMG.IMG_WIDE
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public Integer getImgWide() {
        return imgWide;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG.IMG_WIDE
     * 
     * @param imgWide the value for LIB_IMG.IMG_WIDE
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgWide(Integer imgWide) {
        this.imgWide = imgWide;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_IMG.IMG_CODE
     * 
     * @return the value of LIB_IMG.IMG_CODE
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public byte[] getImgCode() {
        return imgCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_IMG.IMG_CODE
     * 
     * @param imgCode the value for LIB_IMG.IMG_CODE
     * @ibatorgenerated Thu Mar 10 16:04:14 CST 2011
     */
    public void setImgCode(byte[] imgCode) {
        this.imgCode = imgCode;
    }

}
