package com.mitian.airad.model;

import java.util.Date;

public class ReqAppOnlineTime {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_APP_ONLINE_TIME.APP_ONLINE_ID
     * 
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    private Integer appOnlineId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_APP_ONLINE_TIME.APP_START_TIME
     * 
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    private Date appStartTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_APP_ONLINE_TIME.APP_END_TIME
     * 
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    private Date appEndTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_APP_ONLINE_TIME.SOLE_ID
     * 
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    private String soleId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_APP_ONLINE_TIME.APP_CODE
     * 
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    private String appCode;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_APP_ONLINE_TIME.STATE
     * 
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    private String state;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_APP_ONLINE_TIME.OS_TYPE
     * 
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    private String osType;

    /**
     * ip地址
     */
    private String appOnlineIp;

    /**
     * 浏览器
     */
    private String appOnlineUserAgent;

    /**
     * 屏幕高度
     */
    private String deviceScreenWidth;

    /**
     * 屏幕宽度
     */
    private String deviceScreenHeight;

    public String getDeviceScreenWidth() {
        return deviceScreenWidth;
    }

    public void setDeviceScreenWidth(String deviceScreenWidth) {
        this.deviceScreenWidth = deviceScreenWidth;
    }

    public String getDeviceScreenHeight() {
        return deviceScreenHeight;
    }

    public void setDeviceScreenHeight(String deviceScreenHeight) {
        this.deviceScreenHeight = deviceScreenHeight;
    }

    public String getAppOnlineIp() {
        return appOnlineIp;
    }

    public void setAppOnlineIp(String appOnlineIp) {
        this.appOnlineIp = appOnlineIp;
    }

    public String getAppOnlineUserAgent() {
        return appOnlineUserAgent;
    }

    public void setAppOnlineUserAgent(String appOnlineUserAgent) {
        this.appOnlineUserAgent = appOnlineUserAgent;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_APP_ONLINE_TIME.APP_ONLINE_ID
     * 
     * @return the value of REQ_APP_ONLINE_TIME.APP_ONLINE_ID
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public Integer getAppOnlineId() {
        return appOnlineId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_APP_ONLINE_TIME.APP_ONLINE_ID
     * 
     * @param appOnlineId the value for REQ_APP_ONLINE_TIME.APP_ONLINE_ID
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public void setAppOnlineId(Integer appOnlineId) {
        this.appOnlineId = appOnlineId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_APP_ONLINE_TIME.APP_START_TIME
     * 
     * @return the value of REQ_APP_ONLINE_TIME.APP_START_TIME
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public Date getAppStartTime() {
        return appStartTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_APP_ONLINE_TIME.APP_START_TIME
     * 
     * @param appStartTime the value for REQ_APP_ONLINE_TIME.APP_START_TIME
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public void setAppStartTime(Date appStartTime) {
        this.appStartTime = appStartTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_APP_ONLINE_TIME.APP_END_TIME
     * 
     * @return the value of REQ_APP_ONLINE_TIME.APP_END_TIME
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public Date getAppEndTime() {
        return appEndTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_APP_ONLINE_TIME.APP_END_TIME
     * 
     * @param appEndTime the value for REQ_APP_ONLINE_TIME.APP_END_TIME
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public void setAppEndTime(Date appEndTime) {
        this.appEndTime = appEndTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_APP_ONLINE_TIME.SOLE_ID
     * 
     * @return the value of REQ_APP_ONLINE_TIME.SOLE_ID
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public String getSoleId() {
        return soleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_APP_ONLINE_TIME.SOLE_ID
     * 
     * @param soleId the value for REQ_APP_ONLINE_TIME.SOLE_ID
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public void setSoleId(String soleId) {
        this.soleId = soleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_APP_ONLINE_TIME.APP_CODE
     * 
     * @return the value of REQ_APP_ONLINE_TIME.APP_CODE
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_APP_ONLINE_TIME.APP_CODE
     * 
     * @param appCode the value for REQ_APP_ONLINE_TIME.APP_CODE
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_APP_ONLINE_TIME.STATE
     * 
     * @return the value of REQ_APP_ONLINE_TIME.STATE
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_APP_ONLINE_TIME.STATE
     * 
     * @param state the value for REQ_APP_ONLINE_TIME.STATE
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_APP_ONLINE_TIME.OS_TYPE
     * 
     * @return the value of REQ_APP_ONLINE_TIME.OS_TYPE
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public String getOsType() {
        return osType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_APP_ONLINE_TIME.OS_TYPE
     * 
     * @param osType the value for REQ_APP_ONLINE_TIME.OS_TYPE
     * @ibatorgenerated Tue Mar 01 16:26:22 CST 2011
     */
    public void setOsType(String osType) {
        this.osType = osType;
    }
}
