package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

public class ReqWapRich {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.GUIDE_ID
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Integer guideId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.REQ_TIME
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Date reqTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.PROVINCE
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Short province;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REQ_WAP_RICH.CITY
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Short city;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REQ_WAP_RICH.AREA
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Short area;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.REQ_TYPE
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String reqType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.OFFER
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private BigDecimal offer;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.CAMPAIGN_ID
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Integer campaignId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.AD_GROUP_ID
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Integer adGroupId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.AD_ID
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Integer adId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.ADVERTISER_ID
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Integer advertiserId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.DEV_ID
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Integer devId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.AGENT_ID
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private Integer agentId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REQ_WAP_RICH.FLAG
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String flag;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.APP_CODE
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String appCode;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.DEVICE_SCREEN_WIDTH
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String deviceScreenWidth;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.DEVICE_SCREEN_HEIGHT
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String deviceScreenHeight;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.AD_CONTENT_ONLINE_IP
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String adContentOnlineIp;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.AD_CONTENT_ONLINE_USER_AGENT
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String adContentOnlineUserAgent;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.LATITUDE
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String latitude;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * REQ_WAP_RICH.LONGITUDE
     * 
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    private String longitude;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.GUIDE_ID
     * 
     * @return the value of REQ_WAP_RICH.GUIDE_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Integer getGuideId() {
        return guideId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.GUIDE_ID
     * 
     * @param guideId the value for REQ_WAP_RICH.GUIDE_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setGuideId(Integer guideId) {
        this.guideId = guideId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.REQ_TIME
     * 
     * @return the value of REQ_WAP_RICH.REQ_TIME
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Date getReqTime() {
        return reqTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.REQ_TIME
     * 
     * @param reqTime the value for REQ_WAP_RICH.REQ_TIME
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setReqTime(Date reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.PROVINCE
     * 
     * @return the value of REQ_WAP_RICH.PROVINCE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Short getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.PROVINCE
     * 
     * @param province the value for REQ_WAP_RICH.PROVINCE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setProvince(Short province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.CITY
     * 
     * @return the value of REQ_WAP_RICH.CITY
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Short getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.CITY
     * 
     * @param city the value for REQ_WAP_RICH.CITY
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setCity(Short city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.AREA
     * 
     * @return the value of REQ_WAP_RICH.AREA
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Short getArea() {
        return area;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.AREA
     * 
     * @param area the value for REQ_WAP_RICH.AREA
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setArea(Short area) {
        this.area = area;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.REQ_TYPE
     * 
     * @return the value of REQ_WAP_RICH.REQ_TYPE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getReqType() {
        return reqType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.REQ_TYPE
     * 
     * @param reqType the value for REQ_WAP_RICH.REQ_TYPE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setReqType(String reqType) {
        this.reqType = reqType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.OFFER
     * 
     * @return the value of REQ_WAP_RICH.OFFER
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public BigDecimal getOffer() {
        return offer;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.OFFER
     * 
     * @param offer the value for REQ_WAP_RICH.OFFER
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setOffer(BigDecimal offer) {
        this.offer = offer;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.CAMPAIGN_ID
     * 
     * @return the value of REQ_WAP_RICH.CAMPAIGN_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Integer getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.CAMPAIGN_ID
     * 
     * @param campaignId the value for REQ_WAP_RICH.CAMPAIGN_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.AD_GROUP_ID
     * 
     * @return the value of REQ_WAP_RICH.AD_GROUP_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Integer getAdGroupId() {
        return adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.AD_GROUP_ID
     * 
     * @param adGroupId the value for REQ_WAP_RICH.AD_GROUP_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setAdGroupId(Integer adGroupId) {
        this.adGroupId = adGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.AD_ID
     * 
     * @return the value of REQ_WAP_RICH.AD_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.AD_ID
     * 
     * @param adId the value for REQ_WAP_RICH.AD_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.ADVERTISER_ID
     * 
     * @return the value of REQ_WAP_RICH.ADVERTISER_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Integer getAdvertiserId() {
        return advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.ADVERTISER_ID
     * 
     * @param advertiserId the value for REQ_WAP_RICH.ADVERTISER_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setAdvertiserId(Integer advertiserId) {
        this.advertiserId = advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.DEV_ID
     * 
     * @return the value of REQ_WAP_RICH.DEV_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Integer getDevId() {
        return devId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.DEV_ID
     * 
     * @param devId the value for REQ_WAP_RICH.DEV_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setDevId(Integer devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.AGENT_ID
     * 
     * @return the value of REQ_WAP_RICH.AGENT_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.AGENT_ID
     * 
     * @param agentId the value for REQ_WAP_RICH.AGENT_ID
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.FLAG
     * 
     * @return the value of REQ_WAP_RICH.FLAG
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.FLAG
     * 
     * @param flag the value for REQ_WAP_RICH.FLAG
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.APP_CODE
     * 
     * @return the value of REQ_WAP_RICH.APP_CODE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.APP_CODE
     * 
     * @param appCode the value for REQ_WAP_RICH.APP_CODE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.DEVICE_SCREEN_WIDTH
     * 
     * @return the value of REQ_WAP_RICH.DEVICE_SCREEN_WIDTH
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getDeviceScreenWidth() {
        return deviceScreenWidth;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.DEVICE_SCREEN_WIDTH
     * 
     * @param deviceScreenWidth the value for REQ_WAP_RICH.DEVICE_SCREEN_WIDTH
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setDeviceScreenWidth(String deviceScreenWidth) {
        this.deviceScreenWidth = deviceScreenWidth;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.DEVICE_SCREEN_HEIGHT
     * 
     * @return the value of REQ_WAP_RICH.DEVICE_SCREEN_HEIGHT
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getDeviceScreenHeight() {
        return deviceScreenHeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.DEVICE_SCREEN_HEIGHT
     * 
     * @param deviceScreenHeight the value for REQ_WAP_RICH.DEVICE_SCREEN_HEIGHT
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setDeviceScreenHeight(String deviceScreenHeight) {
        this.deviceScreenHeight = deviceScreenHeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.AD_CONTENT_ONLINE_IP
     * 
     * @return the value of REQ_WAP_RICH.AD_CONTENT_ONLINE_IP
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getAdContentOnlineIp() {
        return adContentOnlineIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.AD_CONTENT_ONLINE_IP
     * 
     * @param adContentOnlineIp the value for REQ_WAP_RICH.AD_CONTENT_ONLINE_IP
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setAdContentOnlineIp(String adContentOnlineIp) {
        this.adContentOnlineIp = adContentOnlineIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.AD_CONTENT_ONLINE_USER_AGENT
     * 
     * @return the value of REQ_WAP_RICH.AD_CONTENT_ONLINE_USER_AGENT
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getAdContentOnlineUserAgent() {
        return adContentOnlineUserAgent;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.AD_CONTENT_ONLINE_USER_AGENT
     * 
     * @param adContentOnlineUserAgent the value for REQ_WAP_RICH.AD_CONTENT_ONLINE_USER_AGENT
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setAdContentOnlineUserAgent(String adContentOnlineUserAgent) {
        this.adContentOnlineUserAgent = adContentOnlineUserAgent;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.LATITUDE
     * 
     * @return the value of REQ_WAP_RICH.LATITUDE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.LATITUDE
     * 
     * @param latitude the value for REQ_WAP_RICH.LATITUDE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * REQ_WAP_RICH.LONGITUDE
     * 
     * @return the value of REQ_WAP_RICH.LONGITUDE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * REQ_WAP_RICH.LONGITUDE
     * 
     * @param longitude the value for REQ_WAP_RICH.LONGITUDE
     * @ibatorgenerated Fri Mar 18 17:22:15 CST 2011
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
}
