package com.mitian.airad.model;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

public class StatApp {
    // 自定义
    private String reqTime;
    private String reqTimeEnd;

    /**
     * @return the reqTimeEnd
     */
    public String getReqTimeEnd() {
        return reqTimeEnd;
    }

    /**
     * @param reqTimeEnd the reqTimeEnd to set
     */
    public void setReqTimeEnd(String reqTimeEnd) {
        this.reqTimeEnd = reqTimeEnd;
    }
    private String inAppCode;
    // 表中的字段
    private Date jobStatTime;
    private String jobStatType;
    private int startPag;
    private int endPag;
    private String flag;

    /**
     * @return the flag
     */
    public String getFlag() {
        return flag;
    }

    /**
     * @param flag the flag to set
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * @return the startPag
     */
    public int getStartPag() {
        return startPag;
    }

    /**
     * @param startPag the startPag to set
     */
    public void setStartPag(int startPag) {
        this.startPag = startPag;
    }

    /**
     * @return the endPag
     */
    public int getEndPag() {
        return endPag;
    }

    /**
     * @param endPag the endPag to set
     */
    public void setEndPag(int endPag) {
        this.endPag = endPag;
    }

    /**
     * @return the jobStatTime
     */
    public Date getJobStatTime() {
        return jobStatTime;
    }

    /**
     * @param jobStatTime the jobStatTime to set
     */
    public void setJobStatTime(Date jobStatTime) {
        this.jobStatTime = jobStatTime;
    }

    /**
     * @return the jobStatType
     */
    public String getJobStatType() {
        return jobStatType;
    }

    /**
     * @param jobStatType the jobStatType to set
     */
    public void setJobStatType(String jobStatType) {
        this.jobStatType = jobStatType;
    }

    /**
     * @return the inAppCode
     */
    public String getInAppCode() {
        return inAppCode;
    }

    /**
     * @param inAppCode the inAppCode to set
     */
    public void setInAppCode(String inAppCode) {
        this.inAppCode = inAppCode;
    }

    /**
     * @param reqTime the reqTime to set
     */
    public void setReqTime(String reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * @return the reqTime
     */
    public String getReqTime() {
        return reqTime;
    }
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_APP.SHAT_APP_ID
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer shatAppId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.APP_ID
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer appId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.APP_CODE
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private String appCode;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.APP_NAME
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private String appName;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.SHOW_NUM
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer showNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_APP.CLICK_NUM
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer clickNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.MAX_NUM
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer maxNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.AD_NUM
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Integer adNum;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.OFFER
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private BigDecimal offer;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.ADD_TIME
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * STAT_APP.CLICK_RATE
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private BigDecimal clickRate;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column STAT_APP.PUT_RATE
     * 
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    private BigDecimal putRate;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.SHAT_APP_ID
     * 
     * @return the value of STAT_APP.SHAT_APP_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getShatAppId() {
        return shatAppId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.SHAT_APP_ID
     * 
     * @param shatAppId the value for STAT_APP.SHAT_APP_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setShatAppId(Integer shatAppId) {
        this.shatAppId = shatAppId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.APP_ID
     * 
     * @return the value of STAT_APP.APP_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.APP_ID
     * 
     * @param appId the value for STAT_APP.APP_ID
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.APP_CODE
     * 
     * @return the value of STAT_APP.APP_CODE
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.APP_CODE
     * 
     * @param appCode the value for STAT_APP.APP_CODE
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.APP_NAME
     * 
     * @return the value of STAT_APP.APP_NAME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.APP_NAME
     * 
     * @param appName the value for STAT_APP.APP_NAME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.SHOW_NUM
     * 
     * @return the value of STAT_APP.SHOW_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getShowNum() {
        return showNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.SHOW_NUM
     * 
     * @param showNum the value for STAT_APP.SHOW_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setShowNum(Integer showNum) {
        this.showNum = showNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.CLICK_NUM
     * 
     * @return the value of STAT_APP.CLICK_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.CLICK_NUM
     * 
     * @param clickNum the value for STAT_APP.CLICK_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.MAX_NUM
     * 
     * @return the value of STAT_APP.MAX_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getMaxNum() {
        return maxNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.MAX_NUM
     * 
     * @param maxNum the value for STAT_APP.MAX_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setMaxNum(Integer maxNum) {
        this.maxNum = maxNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.AD_NUM
     * 
     * @return the value of STAT_APP.AD_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Integer getAdNum() {
        return adNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.AD_NUM
     * 
     * @param adNum the value for STAT_APP.AD_NUM
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAdNum(Integer adNum) {
        this.adNum = adNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.OFFER
     * 
     * @return the value of STAT_APP.OFFER
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public BigDecimal getOffer() {
        if (offer == null) {
            return new BigDecimal(0);
        }
        else {
            return offer;
        }
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.OFFER
     * 
     * @param offer the value for STAT_APP.OFFER
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setOffer(BigDecimal offer) {
        this.offer = offer;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.ADD_TIME
     * 
     * @return the value of STAT_APP.ADD_TIME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.ADD_TIME
     * 
     * @param addTime the value for STAT_APP.ADD_TIME
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.CLICK_RATE
     * 
     * @return the value of STAT_APP.CLICK_RATE
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public BigDecimal getClickRate() {
        if (clickRate == null) {
            return new BigDecimal(0);
        }
        else {
            return clickRate;
        }
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.CLICK_RATE
     * 
     * @param clickRate the value for STAT_APP.CLICK_RATE
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setClickRate(BigDecimal clickRate) {
        this.clickRate = clickRate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * STAT_APP.PUT_RATE
     * 
     * @return the value of STAT_APP.PUT_RATE
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public BigDecimal getPutRate() {
        if (putRate == null) {
            return new BigDecimal(0);
        }
        else {
            return putRate;
        }
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * STAT_APP.PUT_RATE
     * 
     * @param putRate the value for STAT_APP.PUT_RATE
     * @ibatorgenerated Thu Mar 10 10:17:28 CST 2011
     */
    public void setPutRate(BigDecimal putRate) {
        this.putRate = putRate;
    }

    public String toLogString() {
        return ReflectionToStringBuilder.toString(this);
    }
}
