package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.AdminUserInfoDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.AdminUserInfo;

@Repository
public class AdminUserInfoDAOImpl extends CustomSqlMapClientDaoSupport implements AdminUserInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_INFO
     * 
     * @ibatorgenerated Thu Mar 03 15:02:41 CST 2011
     */
    public AdminUserInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_INFO
     * 
     * @ibatorgenerated Thu Mar 03 15:02:41 CST 2011
     */
    public void insert(AdminUserInfo record) {
        getSqlMapClientTemplate().insert("ADMIN_USER_INFO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ADMIN_USER_INFO
     * 
     * @ibatorgenerated Thu Mar 03 15:02:41 CST 2011
     */
    public void insertSelective(AdminUserInfo record) {
        getSqlMapClientTemplate().insert("ADMIN_USER_INFO.ibatorgenerated_insertSelective", record);
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.AdminUserInfoDAO#queryAdminUser(java.lang.String, java.lang.String)
     */
    public AdminUserInfo queryAdminUser(String name, String pwd) {
        AdminUserInfo key = new AdminUserInfo();
        key.setPassword(pwd);
        key.setUserName(name);
        AdminUserInfo adminUserInfo =
                (AdminUserInfo) getSqlMapClientTemplate().queryForObject("ADMIN_USER_INFO.selectadminUserByNameAndPwd",
                        key);
        return adminUserInfo;
    }
}
