package com.mitian.airad.dao.impl;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.CoreMoneyCountDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.CoreMoneyCount;

@Repository
public class CoreMoneyCountDAOImpl extends CustomSqlMapClientDaoSupport implements CoreMoneyCountDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_MONEY_COUNT
     * 
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public CoreMoneyCountDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_MONEY_COUNT
     * 
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        CoreMoneyCount key = new CoreMoneyCount();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("CORE_MONEY_COUNT.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_MONEY_COUNT
     * 
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void insert(CoreMoneyCount record) {
        getSqlMapClientTemplate().insert("CORE_MONEY_COUNT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_MONEY_COUNT
     * 
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public void insertSelective(CoreMoneyCount record) {
        getSqlMapClientTemplate().insert("CORE_MONEY_COUNT.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_MONEY_COUNT
     * 
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public CoreMoneyCount selectByPrimaryKey(Integer id) {
        CoreMoneyCount key = new CoreMoneyCount();
        key.setId(id);
        CoreMoneyCount record =
                (CoreMoneyCount) getSqlMapClientTemplate().queryForObject(
                        "CORE_MONEY_COUNT.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_MONEY_COUNT
     * 
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public int updateByPrimaryKeySelective(CoreMoneyCount record) {
        int rows =
                getSqlMapClientTemplate()
                        .update("CORE_MONEY_COUNT.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_MONEY_COUNT
     * 
     * @ibatorgenerated Sun Jan 30 16:16:01 CST 2011
     */
    public int updateByPrimaryKey(CoreMoneyCount record) {
        int rows = getSqlMapClientTemplate().update("CORE_MONEY_COUNT.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.CoreMoneyCountDAO#selectByMemberId(int)
     */
    public CoreMoneyCount selectByMemberId(Long memberId) {
        return (CoreMoneyCount) getSqlMapClientTemplate().queryForObject("CORE_MONEY_COUNT.selectByMemberId", memberId);
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.CoreMoneyCountDAO#selectByIdList(java.util.List)
     */
    public List<CoreMoneyCount> selectByIdList(List<Long> idList) {
        // TODO 待实现
        return null;
    }
}
