package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.CoreBannerDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.CoreBanner;

@Repository
public class CoreBannerDAOImpl extends CustomSqlMapClientDaoSupport implements CoreBannerDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_BANNER
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public CoreBannerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_BANNER
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public int deleteByPrimaryKey(Integer bannerId, Long memberId) {
        CoreBanner key = new CoreBanner();
        key.setBannerId(bannerId);
        key.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().delete("CORE_BANNER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_BANNER
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public int insert(CoreBanner record, Long memberId) {
        record.setMemberId(memberId);
        return (Integer) getSqlMapClientTemplate().insert("CORE_BANNER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_BANNER
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public int insertSelective(CoreBanner record, Long memberId) {
        record.setMemberId(memberId);
        return (Integer) getSqlMapClientTemplate().insert("CORE_BANNER.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_BANNER
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public CoreBanner selectByPrimaryKey(Integer bannerId, Long memberId) {
        CoreBanner key = new CoreBanner();
        key.setMemberId(memberId);
        key.setBannerId(bannerId);
        CoreBanner record =
                (CoreBanner) getSqlMapClientTemplate().queryForObject("CORE_BANNER.ibatorgenerated_selectByPrimaryKey",
                        key);
        return record;
    }

    /*
     * (non-Javadoc)
     * @see com.mitian.airad.dao.CoreBannerDAO#selectBannerByAdId(java.lang.Integer) 根据广告id查询banner信息
     */
    public CoreBanner selectBannerByAdId(Integer adId, Long memberId) {
        CoreBanner key = new CoreBanner();
        key.setAdId(adId);
        key.setMemberId(memberId);
        CoreBanner record =
                (CoreBanner) getSqlMapClientTemplate().queryForObject("CORE_BANNER.selectBannerByAdId", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_BANNER
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public int updateByPrimaryKeySelective(CoreBanner record, Long memberId) {
        record.setMemberId(memberId);
        int rows = getSqlMapClientTemplate().update("CORE_BANNER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table CORE_BANNER
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public int updateByPrimaryKey(CoreBanner record, Long memberId) {
        record.setMemberId(memberId);
        return getSqlMapClientTemplate().update("CORE_BANNER.ibatorgenerated_updateByPrimaryKey", record);
    }

}
