package com.mitian.airad.dao.impl;

import com.mitian.airad.dao.MemberImgsDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.MemberImgsKey;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class MemberImgsDAOImpl extends CustomSqlMapClientDaoSupport implements MemberImgsDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEMBER_IMGS
     * 
     * @ibatorgenerated Mon Feb 28 15:31:43 CST 2011
     */
    public MemberImgsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEMBER_IMGS
     * 
     * @ibatorgenerated Mon Feb 28 15:31:43 CST 2011
     */
    public int deleteByPrimaryKey(MemberImgsKey key) {
        int rows = getSqlMapClientTemplate().delete("MEMBER_IMGS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEMBER_IMGS
     * 
     * @ibatorgenerated Mon Feb 28 15:31:43 CST 2011
     */
    public void insert(MemberImgsKey record) {
        getSqlMapClientTemplate().insert("MEMBER_IMGS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEMBER_IMGS
     * 
     * @ibatorgenerated Mon Feb 28 15:31:43 CST 2011
     */
    public void insertSelective(MemberImgsKey record) {
        getSqlMapClientTemplate().insert("MEMBER_IMGS.ibatorgenerated_insertSelective", record);
    }
}
