package com.mitian.airad.dao.impl;

import org.springframework.stereotype.Repository;

import com.mitian.airad.dao.ReqAdOnlineTimeDAO;
import com.mitian.airad.dao.support.CustomSqlMapClientDaoSupport;
import com.mitian.airad.model.ReqAdOnlineTime;

@Repository
public class ReqAdOnlineTimeDAOImpl extends CustomSqlMapClientDaoSupport implements ReqAdOnlineTimeDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_AD_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public ReqAdOnlineTimeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_AD_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public int deleteByPrimaryKey(Integer adOnlineId) {
        ReqAdOnlineTime key = new ReqAdOnlineTime();
        key.setAdOnlineId(adOnlineId);
        int rows = getSqlMapClientTemplate().delete("REQ_AD_ONLINE_TIME.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_AD_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public void insert(ReqAdOnlineTime record) {
        getSqlMapClientTemplate().insert("REQ_AD_ONLINE_TIME.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_AD_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public void insertSelective(ReqAdOnlineTime record) {
        getSqlMapClientTemplate().insert("REQ_AD_ONLINE_TIME.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_AD_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public ReqAdOnlineTime selectByPrimaryKey(Integer adOnlineId) {
        ReqAdOnlineTime key = new ReqAdOnlineTime();
        key.setAdOnlineId(adOnlineId);
        ReqAdOnlineTime record =
                (ReqAdOnlineTime) getSqlMapClientTemplate().queryForObject(
                        "REQ_AD_ONLINE_TIME.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_AD_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public int updateByPrimaryKeySelective(ReqAdOnlineTime record) {
        int rows =
                getSqlMapClientTemplate().update("REQ_AD_ONLINE_TIME.ibatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table
     * REQ_AD_ONLINE_TIME
     * 
     * @ibatorgenerated Mon Feb 21 18:54:14 CST 2011
     */
    public int updateByPrimaryKey(ReqAdOnlineTime record) {
        int rows = getSqlMapClientTemplate().update("REQ_AD_ONLINE_TIME.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * 根据条件查询是否存在这个对象
     */
    public ReqAdOnlineTime selectByAdIdAndAppCodeAndSoleId(ReqAdOnlineTime adtime) {
        ReqAdOnlineTime reqAdOnlineTime =
                (ReqAdOnlineTime) getSqlMapClientTemplate().queryForObject(
                        "REQ_AD_ONLINE_TIME.selectByAdIdAndAppCodeAndSoleId", adtime);
        return reqAdOnlineTime;
    }
}
