package com.mitian.airad.dao.impl;

import com.mitian.airad.dao.StatAgentViewDAO;
import com.mitian.airad.model.StatAgentView;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class StatAgentViewDAOImpl extends SqlMapClientDaoSupport implements StatAgentViewDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AGENT_VIEW
     * 
     * @ibatorgenerated Mon Mar 07 10:07:05 CST 2011
     */
    public StatAgentViewDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AGENT_VIEW
     * 
     * @ibatorgenerated Mon Mar 07 10:07:05 CST 2011
     */
    public void insert(StatAgentView record) {
        getSqlMapClientTemplate().insert("STAT_AGENT_VIEW.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_AGENT_VIEW
     * 
     * @ibatorgenerated Mon Mar 07 10:07:05 CST 2011
     */
    public void insertSelective(StatAgentView record) {
        getSqlMapClientTemplate().insert("STAT_AGENT_VIEW.ibatorgenerated_insertSelective", record);
    }
}
