package com.mitian.airad.dao.impl;

import com.mitian.airad.dao.StatAdvertiserDAO;
import com.mitian.airad.model.StatAdvertiser;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class StatAdvertiserDAOImpl extends SqlMapClientDaoSupport implements StatAdvertiserDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_ADVERTISER
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public StatAdvertiserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_ADVERTISER
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public int deleteByPrimaryKey(Integer shatAngenId) {
        StatAdvertiser key = new StatAdvertiser();
        key.setShatAngenId(shatAngenId);
        int rows = getSqlMapClientTemplate().delete("STAT_ADVERTISER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_ADVERTISER
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public void insert(StatAdvertiser record) {
        getSqlMapClientTemplate().insert("STAT_ADVERTISER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_ADVERTISER
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public void insertSelective(StatAdvertiser record) {
        getSqlMapClientTemplate().insert("STAT_ADVERTISER.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_ADVERTISER
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public StatAdvertiser selectByPrimaryKey(Integer shatAngenId) {
        StatAdvertiser key = new StatAdvertiser();
        key.setShatAngenId(shatAngenId);
        StatAdvertiser record =
                (StatAdvertiser) getSqlMapClientTemplate().queryForObject(
                        "STAT_ADVERTISER.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_ADVERTISER
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public int updateByPrimaryKeySelective(StatAdvertiser record) {
        int rows =
                getSqlMapClientTemplate().update("STAT_ADVERTISER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table STAT_ADVERTISER
     * 
     * @ibatorgenerated Tue Feb 15 13:33:26 CST 2011
     */
    public int updateByPrimaryKey(StatAdvertiser record) {
        int rows = getSqlMapClientTemplate().update("STAT_ADVERTISER.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}
