package com.mitian.airad.model;

import java.util.Date;
import java.util.List;

import com.taobao.api.domain.Item;

/**
 * CoreRichAd.java
 * 
 * @author baojun
 */
public class CoreRichAd {
    private Long memberId;
    /**
     * 富媒体id
     */
    private Integer richId;

    /**
     * 富媒体标题
     */
    private String richMediaTitle;

    /**
     * 富媒体内容
     */
    private String richMediaContent;

    /**
     *展示类型
     */
    private String showType;

    /**
     * 操作人
     */
    private String addOper;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     * 更新人
     */
    private String updOper;

    /**
     * 更新时间
     */
    private Date updTime;

    /**
     * 删除人
     */
    private String delOper;

    /**
     * 删除时间
     */
    private Date delTime;

    /**
     *删除标志
     */
    private String delFlag;

    /**
     * 广告id
     */
    private Integer adId;
    /**
     * 电话
     */
    private String phone;
    /**
     * update标志
     */
    private Integer flag;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CORE_RICH_AD.SORT
     * 
     * @ibatorgenerated Mon Mar 07 17:44:30 CST 2011
     */
    private Integer sort;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_RICH_AD.REL_ID
     * 
     * @ibatorgenerated Wed Mar 09 13:32:12 CST 2011
     */
    private String relId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_RICH_AD.FORMAT_TYPE
     * 
     * @ibatorgenerated Mon Mar 14 16:02:22 CST 2011
     */
    private Integer formatType;

    private LibMapInfo map;
    /**
     * 淘宝集合
     */
    private List<Item> taoBaoList;
    /**
     * 地图路径
     */
    private String mapUrl;
    /**
     * 图片id集合
     */
    private List<String> picIdList;

    /**
     * 淘宝2
     */
    private LibTaobao libTaobao;
    /**
     * market
     */
    private LibMarket libMarket;
    /**
     * callphone
     */
    private LibCallPhone LibCallPhone;

    /**
     * @return the libCallPhone
     */
    public LibCallPhone getLibCallPhone() {
        return LibCallPhone;
    }

    /**
     * @param libCallPhone the libCallPhone to set
     */
    public void setLibCallPhone(LibCallPhone libCallPhone) {
        LibCallPhone = libCallPhone;
    }

    /**
     * @return the taoBaoList
     */
    public List<Item> getTaoBaoList() {
        return taoBaoList;
    }

    /**
     * @param taoBaoList the taoBaoList to set
     */
    public void setTaoBaoList(List<Item> taoBaoList) {
        this.taoBaoList = taoBaoList;
    }

    /**
     * @return the mapUrl
     */
    public String getMapUrl() {
        return mapUrl;
    }

    /**
     * @param mapUrl the mapUrl to set
     */
    public void setMapUrl(String mapUrl) {
        this.mapUrl = mapUrl;
    }

    /**
     * @return the picIdList
     */
    public List<String> getPicIdList() {
        return picIdList;
    }

    /**
     * @param picIdList the picIdList to set
     */
    public void setPicIdList(List<String> picIdList) {
        this.picIdList = picIdList;
    }

    /**
     * @return the richId
     */
    public Integer getRichId() {
        return richId;
    }

    /**
     * @param richId the richId to set
     */
    public void setRichId(Integer richId) {
        this.richId = richId;
    }

    /**
     * @return the richMediaTitle
     */
    public String getRichMediaTitle() {
        return richMediaTitle;
    }

    /**
     * @param richMediaTitle the richMediaTitle to set
     */
    public void setRichMediaTitle(String richMediaTitle) {
        this.richMediaTitle = richMediaTitle;
    }

    /**
     * @return the richMediaContent
     */
    public String getRichMediaContent() {
        return richMediaContent;
    }

    /**
     * @param richMediaContent the richMediaContent to set
     */
    public void setRichMediaContent(String richMediaContent) {
        this.richMediaContent = richMediaContent;
    }

    /**
     * @return the showType
     */
    public String getShowType() {
        return showType;
    }

    /**
     * @param showType the showType to set
     */
    public void setShowType(String showType) {
        this.showType = showType;
    }

    /**
     * @return the addOper
     */
    public String getAddOper() {
        return addOper;
    }

    /**
     * @param addOper the addOper to set
     */
    public void setAddOper(String addOper) {
        this.addOper = addOper;
    }

    /**
     * @return the addTime
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * @param addTime the addTime to set
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * @return the updOper
     */
    public String getUpdOper() {
        return updOper;
    }

    /**
     * @param updOper the updOper to set
     */
    public void setUpdOper(String updOper) {
        this.updOper = updOper;
    }

    /**
     * @return the updTime
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * @param updTime the updTime to set
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * @return the delOper
     */
    public String getDelOper() {
        return delOper;
    }

    /**
     * @param delOper the delOper to set
     */
    public void setDelOper(String delOper) {
        this.delOper = delOper;
    }

    /**
     * @return the delTime
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * @param delTime the delTime to set
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * @return the delFlag
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * @param delFlag the delFlag to set
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * @return the adId
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * @param adId the adId to set
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    public void setMap(LibMapInfo map) {
        this.map = map;
    }

    public LibMapInfo getMap() {
        return map;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getSort() {
        return sort;
    }

    /**
     * @param relId the relId to set
     */
    public void setRelId(String relId) {
        this.relId = relId;
    }

    /**
     * @return the relId
     */
    public String getRelId() {
        return relId;
    }

    /**
     * @param formatType the formatType to set
     */
    public void setFormatType(Integer formatType) {
        this.formatType = formatType;
    }

    /**
     * @return the formatType
     */
    public Integer getFormatType() {
        return formatType;
    }

    /**
     * @param phone the phone to set
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * @return the phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * @param flag the flag to set
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * @return the flag
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * @return the memberId
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * @param memberId the memberId to set
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * @param libTaobao the libTaobao to set
     */
    public void setLibTaobao(LibTaobao libTaobao) {
        this.libTaobao = libTaobao;
    }

    /**
     * @return the libTaobao
     */
    public LibTaobao getLibTaobao() {
        return libTaobao;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((adId == null) ? 0 : adId.hashCode());
        result = prime * result + ((addOper == null) ? 0 : addOper.hashCode());
        result = prime * result + ((addTime == null) ? 0 : addTime.hashCode());
        result = prime * result + ((delFlag == null) ? 0 : delFlag.hashCode());
        result = prime * result + ((delOper == null) ? 0 : delOper.hashCode());
        result = prime * result + ((delTime == null) ? 0 : delTime.hashCode());
        result = prime * result + ((flag == null) ? 0 : flag.hashCode());
        result = prime * result + ((formatType == null) ? 0 : formatType.hashCode());
        result = prime * result + ((libTaobao == null) ? 0 : libTaobao.hashCode());
        result = prime * result + ((map == null) ? 0 : map.hashCode());
        result = prime * result + ((mapUrl == null) ? 0 : mapUrl.hashCode());
        result = prime * result + ((memberId == null) ? 0 : memberId.hashCode());
        result = prime * result + ((phone == null) ? 0 : phone.hashCode());
        result = prime * result + ((picIdList == null) ? 0 : picIdList.hashCode());
        result = prime * result + ((relId == null) ? 0 : relId.hashCode());
        result = prime * result + ((richId == null) ? 0 : richId.hashCode());
        result = prime * result + ((richMediaContent == null) ? 0 : richMediaContent.hashCode());
        result = prime * result + ((richMediaTitle == null) ? 0 : richMediaTitle.hashCode());
        result = prime * result + ((showType == null) ? 0 : showType.hashCode());
        result = prime * result + ((sort == null) ? 0 : sort.hashCode());
        result = prime * result + ((taoBaoList == null) ? 0 : taoBaoList.hashCode());
        result = prime * result + ((updOper == null) ? 0 : updOper.hashCode());
        result = prime * result + ((updTime == null) ? 0 : updTime.hashCode());
        return result;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "CoreRichAd [adId=" + adId + ", addOper=" + addOper + ", addTime=" + addTime + ", delFlag=" + delFlag
                + ", delOper=" + delOper + ", delTime=" + delTime + ", flag=" + flag + ", formatType=" + formatType
                + ", libTaobao=" + libTaobao + ", map=" + map + ", mapUrl=" + mapUrl + ", memberId=" + memberId
                + ", phone=" + phone + ", picIdList=" + picIdList + ", relId=" + relId + ", richId=" + richId
                + ", richMediaContent=" + richMediaContent + ", richMediaTitle=" + richMediaTitle + ", showType="
                + showType + ", sort=" + sort + ", taoBaoList=" + taoBaoList + ", updOper=" + updOper + ", updTime="
                + updTime + "]";
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        CoreRichAd other = (CoreRichAd) obj;
        if (adId == null) {
            if (other.adId != null) {
                return false;
            }
        }
        else if (!adId.equals(other.adId)) {
            return false;
        }
        if (addOper == null) {
            if (other.addOper != null) {
                return false;
            }
        }
        else if (!addOper.equals(other.addOper)) {
            return false;
        }
        if (addTime == null) {
            if (other.addTime != null) {
                return false;
            }
        }
        else if (!addTime.equals(other.addTime)) {
            return false;
        }
        if (delFlag == null) {
            if (other.delFlag != null) {
                return false;
            }
        }
        else if (!delFlag.equals(other.delFlag)) {
            return false;
        }
        if (delOper == null) {
            if (other.delOper != null) {
                return false;
            }
        }
        else if (!delOper.equals(other.delOper)) {
            return false;
        }
        if (delTime == null) {
            if (other.delTime != null) {
                return false;
            }
        }
        else if (!delTime.equals(other.delTime)) {
            return false;
        }
        if (flag == null) {
            if (other.flag != null) {
                return false;
            }
        }
        else if (!flag.equals(other.flag)) {
            return false;
        }
        if (formatType == null) {
            if (other.formatType != null) {
                return false;
            }
        }
        else if (!formatType.equals(other.formatType)) {
            return false;
        }
        if (libTaobao == null) {
            if (other.libTaobao != null) {
                return false;
            }
        }
        else if (!libTaobao.equals(other.libTaobao)) {
            return false;
        }
        if (map == null) {
            if (other.map != null) {
                return false;
            }
        }
        else if (!map.equals(other.map)) {
            return false;
        }
        if (mapUrl == null) {
            if (other.mapUrl != null) {
                return false;
            }
        }
        else if (!mapUrl.equals(other.mapUrl)) {
            return false;
        }
        if (memberId == null) {
            if (other.memberId != null) {
                return false;
            }
        }
        else if (!memberId.equals(other.memberId)) {
            return false;
        }
        if (phone == null) {
            if (other.phone != null) {
                return false;
            }
        }
        else if (!phone.equals(other.phone)) {
            return false;
        }
        if (picIdList == null) {
            if (other.picIdList != null) {
                return false;
            }
        }
        else if (!picIdList.equals(other.picIdList)) {
            return false;
        }
        if (relId == null) {
            if (other.relId != null) {
                return false;
            }
        }
        else if (!relId.equals(other.relId)) {
            return false;
        }
        if (richId == null) {
            if (other.richId != null) {
                return false;
            }
        }
        else if (!richId.equals(other.richId)) {
            return false;
        }
        if (richMediaContent == null) {
            if (other.richMediaContent != null) {
                return false;
            }
        }
        else if (!richMediaContent.equals(other.richMediaContent)) {
            return false;
        }
        if (richMediaTitle == null) {
            if (other.richMediaTitle != null) {
                return false;
            }
        }
        else if (!richMediaTitle.equals(other.richMediaTitle)) {
            return false;
        }
        if (showType == null) {
            if (other.showType != null) {
                return false;
            }
        }
        else if (!showType.equals(other.showType)) {
            return false;
        }
        if (sort == null) {
            if (other.sort != null) {
                return false;
            }
        }
        else if (!sort.equals(other.sort)) {
            return false;
        }
        if (taoBaoList == null) {
            if (other.taoBaoList != null) {
                return false;
            }
        }
        else if (!taoBaoList.equals(other.taoBaoList)) {
            return false;
        }
        if (updOper == null) {
            if (other.updOper != null) {
                return false;
            }
        }
        else if (!updOper.equals(other.updOper)) {
            return false;
        }
        if (updTime == null) {
            if (other.updTime != null) {
                return false;
            }
        }
        else if (!updTime.equals(other.updTime)) {
            return false;
        }
        return true;
    }

    /**
     * @param libMarket the libMarket to set
     */
    public void setLibMarket(LibMarket libMarket) {
        this.libMarket = libMarket;
    }

    /**
     * @return the libMarket
     */
    public LibMarket getLibMarket() {
        return libMarket;
    }

}
