package com.mitian.airad.model;

/**
 * CoreBanner.java
 * 
 * @author baojun
 */
public class CoreBanner {

    private String bannerColor;

    private String bannerModelName;

    private String bannerGrain;
    private Long memberId;

    private String bannerHtml;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_BANNER.BANNER_ID
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    private Integer bannerId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CORE_BANNER.AD_ID
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    private Integer adId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_BANNER.BANNER_BG_TYPE
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    private String bannerBgType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_BANNER.BANNER_TYPE
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    private String bannerType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_BANNER.BANNER_BG_CON
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    private String bannerBgCon;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_BANNER.BANNER_TEXT
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    private String bannerText;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_BANNER.BANNER_ICON_TYPE
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    private String bannerText2;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_BANNER.BANNER_ICON_CON
     * 
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    private String bannerIconCon;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_BANNER.BANNER_ID
     * 
     * @return the value of CORE_BANNER.BANNER_ID
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public Integer getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_BANNER.BANNER_ID
     * 
     * @param bannerId the value for CORE_BANNER.BANNER_ID
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public void setBannerId(Integer bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_BANNER.AD_ID
     * 
     * @return the value of CORE_BANNER.AD_ID
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_BANNER.AD_ID
     * 
     * @param adId the value for CORE_BANNER.AD_ID
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_BANNER.BANNER_BG_TYPE
     * 
     * @return the value of CORE_BANNER.BANNER_BG_TYPE
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public String getBannerBgType() {
        return bannerBgType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_BANNER.BANNER_BG_TYPE
     * 
     * @param bannerBgType the value for CORE_BANNER.BANNER_BG_TYPE
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public void setBannerBgType(String bannerBgType) {
        this.bannerBgType = bannerBgType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_BANNER.BANNER_TYPE
     * 
     * @return the value of CORE_BANNER.BANNER_TYPE
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public String getBannerType() {
        return bannerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_BANNER.BANNER_TYPE
     * 
     * @param bannerType the value for CORE_BANNER.BANNER_TYPE
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public void setBannerType(String bannerType) {
        this.bannerType = bannerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_BANNER.BANNER_BG_CON
     * 
     * @return the value of CORE_BANNER.BANNER_BG_CON
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public String getBannerBgCon() {
        return bannerBgCon;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_BANNER.BANNER_BG_CON
     * 
     * @param bannerBgCon the value for CORE_BANNER.BANNER_BG_CON
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public void setBannerBgCon(String bannerBgCon) {
        this.bannerBgCon = bannerBgCon;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_BANNER.BANNER_TEXT
     * 
     * @return the value of CORE_BANNER.BANNER_TEXT
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public String getBannerText() {
        return bannerText;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_BANNER.BANNER_TEXT
     * 
     * @param bannerText the value for CORE_BANNER.BANNER_TEXT
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public void setBannerText(String bannerText) {
        this.bannerText = bannerText;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_BANNER.BANNER_ICON_TYPE
     * 
     * @return the value of CORE_BANNER.BANNER_ICON_TYPE
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public String getBannerText2() {
        return bannerText2;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_BANNER.BANNER_ICON_TYPE
     * 
     * @param bannerText2 the value for CORE_BANNER.BANNER_ICON_TYPE
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public void setBannerText2(String bannerText2) {
        this.bannerText2 = bannerText2;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_BANNER.BANNER_ICON_CON
     * 
     * @return the value of CORE_BANNER.BANNER_ICON_CON
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public String getBannerIconCon() {
        return bannerIconCon;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_BANNER.BANNER_ICON_CON
     * 
     * @param bannerIconCon the value for CORE_BANNER.BANNER_ICON_CON
     * @ibatorgenerated Tue Mar 01 15:00:34 CST 2011
     */
    public void setBannerIconCon(String bannerIconCon) {
        this.bannerIconCon = bannerIconCon;
    }

    /**
     * @param bannerGrain the bannerGrain to set
     */
    public void setBannerGrain(String bannerGrain) {
        this.bannerGrain = bannerGrain;
    }

    /**
     * @return the bannerGrain
     */
    public String getBannerGrain() {
        return bannerGrain;
    }

    /**
     * @param bannerModelName the bannerModelName to set
     */
    public void setBannerModelName(String bannerModelName) {
        this.bannerModelName = bannerModelName;
    }

    /**
     * @return the bannerModelName
     */
    public String getBannerModelName() {
        return bannerModelName;
    }

    /**
     * @param bannerColor the bannerColor to set
     */
    public void setBannerColor(String bannerColor) {
        this.bannerColor = bannerColor;
    }

    /**
     * @return the bannerColor
     */
    public String getBannerColor() {
        return bannerColor;
    }

    /**
     * @return the memberId
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * @param memberId the memberId to set
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * @param bannerHtml the bannerHtml to set
     */
    public void setBannerHtml(String bannerHtml) {
        this.bannerHtml = bannerHtml;
    }

    /**
     * @return the bannerHtml
     */
    public String getBannerHtml() {
        return bannerHtml;
    }
}
