package com.mitian.airad.model;

import java.util.Date;

/**
 * CoreUserHis.java
 * 
 * @author baojun
 */
public class CoreUserHis {
    private boolean firstLogon;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.LOGIN_ID
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private Integer loginId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.MEMBER_ID
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private Long memberId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.LOGIN_TIME
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private Date loginTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.LOGIN_IP
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private String loginIp;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.ADD_OPER
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private String addOper;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.ADD_TIME
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.UPD_OPER
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private String updOper;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.UPD_TIME
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private Date updTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.DEL_OPER
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private String delOper;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.DEL_TIME
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private Date delTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_USER_HIS.DEL_FLAG
     * 
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    private String delFlag;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.LOGIN_ID
     * 
     * @return the value of CORE_USER_HIS.LOGIN_ID
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.LOGIN_ID
     * 
     * @param loginId the value for CORE_USER_HIS.LOGIN_ID
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.MEMBER_ID
     * 
     * @return the value of CORE_USER_HIS.MEMBER_ID
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.MEMBER_ID
     * 
     * @param memberId the value for CORE_USER_HIS.MEMBER_ID
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.LOGIN_TIME
     * 
     * @return the value of CORE_USER_HIS.LOGIN_TIME
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public Date getLoginTime() {
        if (isFirstLogon()) {
            return null;
        }
        else {
            return loginTime;
        }
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.LOGIN_TIME
     * 
     * @param loginTime the value for CORE_USER_HIS.LOGIN_TIME
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.LOGIN_IP
     * 
     * @return the value of CORE_USER_HIS.LOGIN_IP
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public String getLoginIp() {
        if (isFirstLogon()) {
            return null;
        }
        return loginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.LOGIN_IP
     * 
     * @param loginIp the value for CORE_USER_HIS.LOGIN_IP
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.ADD_OPER
     * 
     * @return the value of CORE_USER_HIS.ADD_OPER
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public String getAddOper() {
        return addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.ADD_OPER
     * 
     * @param addOper the value for CORE_USER_HIS.ADD_OPER
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setAddOper(String addOper) {
        this.addOper = addOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.ADD_TIME
     * 
     * @return the value of CORE_USER_HIS.ADD_TIME
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.ADD_TIME
     * 
     * @param addTime the value for CORE_USER_HIS.ADD_TIME
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.UPD_OPER
     * 
     * @return the value of CORE_USER_HIS.UPD_OPER
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public String getUpdOper() {
        return updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.UPD_OPER
     * 
     * @param updOper the value for CORE_USER_HIS.UPD_OPER
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setUpdOper(String updOper) {
        this.updOper = updOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.UPD_TIME
     * 
     * @return the value of CORE_USER_HIS.UPD_TIME
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.UPD_TIME
     * 
     * @param updTime the value for CORE_USER_HIS.UPD_TIME
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.DEL_OPER
     * 
     * @return the value of CORE_USER_HIS.DEL_OPER
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public String getDelOper() {
        return delOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.DEL_OPER
     * 
     * @param delOper the value for CORE_USER_HIS.DEL_OPER
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setDelOper(String delOper) {
        this.delOper = delOper;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.DEL_TIME
     * 
     * @return the value of CORE_USER_HIS.DEL_TIME
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.DEL_TIME
     * 
     * @param delTime the value for CORE_USER_HIS.DEL_TIME
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_USER_HIS.DEL_FLAG
     * 
     * @return the value of CORE_USER_HIS.DEL_FLAG
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_USER_HIS.DEL_FLAG
     * 
     * @param delFlag the value for CORE_USER_HIS.DEL_FLAG
     * @ibatorgenerated Sun Jan 30 11:18:10 CST 2011
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * @return the firstLogon
     */
    public boolean isFirstLogon() {
        return firstLogon;
    }

    /**
     * @param firstLogon the firstLogon to set
     */
    public void setFirstLogon(boolean firstLogon) {
        this.firstLogon = firstLogon;
    }
}
