package com.mitian.airad.model;

import java.util.Date;

/**
 * CoreAdvertiserImg.java
 * 
 * @author baojun
 */
public class CoreAdvertiserImg {
    // 每天认证的次数
    private int approveNum;

    /**
     * @param approveNum the approveNum to set
     */
    public void setApproveNum(int approveNum) {
        this.approveNum = approveNum;
    }

    /**
     * @return the approveNum
     */
    public int getApproveNum() {
        return approveNum;
    }
    private Date addTime;
    private Integer memberId;

    /**
     * @param memberId the memberId to set
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * @return the memberId
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * @param addTime the addTime to set
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * @return the addTime
     */
    public Date getAddTime() {
        return addTime;
    }
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_ADVERTISER_IMG.CARD_IMG_ID
     * 
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    private Integer cardImgId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_ADVERTISER_IMG.ADVERTISER_ID
     * 
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    private Integer advertiserId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_ADVERTISER_IMG.IMG_SIZE
     * 
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    private int imgSize;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_ADVERTISER_IMG.IMG_FORMAT
     * 
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    private String imgFormat;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * CORE_ADVERTISER_IMG.IMG_CONTENT
     * 
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    private byte[] imgContent;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_ADVERTISER_IMG.CARD_IMG_ID
     * 
     * @return the value of CORE_ADVERTISER_IMG.CARD_IMG_ID
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    public Integer getCardImgId() {
        return cardImgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_ADVERTISER_IMG.CARD_IMG_ID
     * 
     * @param cardImgId the value for CORE_ADVERTISER_IMG.CARD_IMG_ID
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    public void setCardImgId(Integer cardImgId) {
        this.cardImgId = cardImgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_ADVERTISER_IMG.ADVERTISER_ID
     * 
     * @return the value of CORE_ADVERTISER_IMG.ADVERTISER_ID
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    public Integer getAdvertiserId() {
        return advertiserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_ADVERTISER_IMG.ADVERTISER_ID
     * 
     * @param advertiserId the value for CORE_ADVERTISER_IMG.ADVERTISER_ID
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    public void setAdvertiserId(Integer advertiserId) {
        this.advertiserId = advertiserId;
    }

    /**
     * @return the imgSize
     */
    public int getImgSize() {
        return imgSize;
    }

    /**
     * @param imgSize the imgSize to set
     */
    public void setImgSize(int imgSize) {
        this.imgSize = imgSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_ADVERTISER_IMG.IMG_FORMAT
     * 
     * @return the value of CORE_ADVERTISER_IMG.IMG_FORMAT
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    public String getImgFormat() {
        return imgFormat;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_ADVERTISER_IMG.IMG_FORMAT
     * 
     * @param imgFormat the value for CORE_ADVERTISER_IMG.IMG_FORMAT
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    public void setImgFormat(String imgFormat) {
        this.imgFormat = imgFormat;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * CORE_ADVERTISER_IMG.IMG_CONTENT
     * 
     * @return the value of CORE_ADVERTISER_IMG.IMG_CONTENT
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    public byte[] getImgContent() {
        return imgContent;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * CORE_ADVERTISER_IMG.IMG_CONTENT
     * 
     * @param imgContent the value for CORE_ADVERTISER_IMG.IMG_CONTENT
     * @ibatorgenerated Sat Feb 12 18:14:21 CST 2011
     */
    public void setImgContent(byte[] imgContent) {
        this.imgContent = imgContent;
    }
}
