package com.mitian.airad.model;

import java.util.List;

/**
 * LibMapInfo.java
 * 
 * @author baojun
 */
public class LibMapInfo {
    private LibPointInfo libPointInfo;
    private List<LibPointInfo> libPointInfoList;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_MAP_INFO.MAP_ID
     * 
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    private Integer mapId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_MAP_INFO.RICH_ID
     * 
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    private Integer richId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_MAP_INFO.GUIDE_ID
     * 
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    private Integer guideId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_MAP_INFO.PROS_JSON
     * 
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    private String prosJson;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_MAP_INFO.MAP_ID
     * 
     * @return the value of LIB_MAP_INFO.MAP_ID
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    public Integer getMapId() {
        return mapId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_MAP_INFO.MAP_ID
     * 
     * @param mapId the value for LIB_MAP_INFO.MAP_ID
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_MAP_INFO.RICH_ID
     * 
     * @return the value of LIB_MAP_INFO.RICH_ID
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    public Integer getRichId() {
        return richId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_MAP_INFO.RICH_ID
     * 
     * @param richId the value for LIB_MAP_INFO.RICH_ID
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    public void setRichId(Integer richId) {
        this.richId = richId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_MAP_INFO.GUIDE_ID
     * 
     * @return the value of LIB_MAP_INFO.GUIDE_ID
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    public Integer getGuideId() {
        return guideId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_MAP_INFO.GUIDE_ID
     * 
     * @param guideId the value for LIB_MAP_INFO.GUIDE_ID
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    public void setGuideId(Integer guideId) {
        this.guideId = guideId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_MAP_INFO.PROS_JSON
     * 
     * @return the value of LIB_MAP_INFO.PROS_JSON
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    public String getProsJson() {
        return prosJson;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_MAP_INFO.PROS_JSON
     * 
     * @param prosJson the value for LIB_MAP_INFO.PROS_JSON
     * @ibatorgenerated Thu Mar 03 19:33:56 CST 2011
     */
    public void setProsJson(String prosJson) {
        this.prosJson = prosJson;
    }

    public void setLibPointInfo(LibPointInfo libPointInfo) {
        this.libPointInfo = libPointInfo;
    }

    public LibPointInfo getLibPointInfo() {
        return libPointInfo;
    }

    /**
     * @param libPointInfoList the libPointInfoList to set
     */
    public void setLibPointInfoList(List<LibPointInfo> libPointInfoList) {
        this.libPointInfoList = libPointInfoList;
    }

    /**
     * @return the libPointInfoList
     */
    public List<LibPointInfo> getLibPointInfoList() {
        return libPointInfoList;
    }
}
