package com.mitian.airad.model;

/**
 * LibPointInfo.java
 * 
 * @author baojun
 */
public class LibPointInfo {
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_POINT_INFO.FID
     * 
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    private Integer fid;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_POINT_INFO.MAP_ID
     * 
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    private Integer mapId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LIB_POINT_INFO.PROS_JSON
     * 
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    private String prosJson;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_POINT_INFO.FID
     * 
     * @return the value of LIB_POINT_INFO.FID
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_POINT_INFO.FID
     * 
     * @param fid the value for LIB_POINT_INFO.FID
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_POINT_INFO.MAP_ID
     * 
     * @return the value of LIB_POINT_INFO.MAP_ID
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    public Integer getMapId() {
        return mapId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_POINT_INFO.MAP_ID
     * 
     * @param mapId the value for LIB_POINT_INFO.MAP_ID
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LIB_POINT_INFO.PROS_JSON
     * 
     * @return the value of LIB_POINT_INFO.PROS_JSON
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    public String getProsJson() {
        return prosJson;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LIB_POINT_INFO.PROS_JSON
     * 
     * @param prosJson the value for LIB_POINT_INFO.PROS_JSON
     * @ibatorgenerated Wed Mar 02 18:52:22 CST 2011
     */
    public void setProsJson(String prosJson) {
        this.prosJson = prosJson;
    }
}
