package com.mitian.airad.model;

import java.util.Date;

/**
 * LogInfo.java
 * 
 * @author baojun
 */
public class LogInfo {
    private String jobTime;
    private int count;
    private int startPag;
    private int endPag;

    /**
     * @return the startPag
     */
    public int getStartPag() {
        return startPag;
    }

    /**
     * @param startPag the startPag to set
     */
    public void setStartPag(int startPag) {
        this.startPag = startPag;
    }

    /**
     * @return the endPag
     */
    public int getEndPag() {
        return endPag;
    }

    /**
     * @param endPag the endPag to set
     */
    public void setEndPag(int endPag) {
        this.endPag = endPag;
    }

    /**
     * @return the count
     */
    public int getCount() {
        return count;
    }

    /**
     * @param count the count to set
     */
    public void setCount(int count) {
        this.count = count;
    }

    /**
     * @return the jobTime
     */
    public String getJobTime() {
        return jobTime;
    }

    /**
     * @param jobTime the jobTime to set
     */
    public void setJobTime(String jobTime) {
        this.jobTime = jobTime;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_INFO.LOG_ID
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    private Integer logId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_INFO.NAME
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LOG_INFO.JOB_STAT_TIME
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    private Date jobStatTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * LOG_INFO.JOB_ADD_TIME
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    private Date jobAddTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_INFO.JOB_NAME
     * 
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    private String jobName;
    private String jobStatType;

    /**
     * @return the jobStatType
     */
    public String getJobStatType() {
        return jobStatType;
    }

    /**
     * @param jobStatType the jobStatType to set
     */
    public void setJobStatType(String jobStatType) {
        this.jobStatType = jobStatType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LOG_INFO.LOG_ID
     * 
     * @return the value of LOG_INFO.LOG_ID
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LOG_INFO.LOG_ID
     * 
     * @param logId the value for LOG_INFO.LOG_ID
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LOG_INFO.NAME
     * 
     * @return the value of LOG_INFO.NAME
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LOG_INFO.NAME
     * 
     * @param name the value for LOG_INFO.NAME
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LOG_INFO.JOB_STAT_TIME
     * 
     * @return the value of LOG_INFO.JOB_STAT_TIME
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public Date getJobStatTime() {
        return jobStatTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LOG_INFO.JOB_STAT_TIME
     * 
     * @param jobStatTime the value for LOG_INFO.JOB_STAT_TIME
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public void setJobStatTime(Date jobStatTime) {
        this.jobStatTime = jobStatTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LOG_INFO.JOB_ADD_TIME
     * 
     * @return the value of LOG_INFO.JOB_ADD_TIME
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public Date getJobAddTime() {
        return jobAddTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LOG_INFO.JOB_ADD_TIME
     * 
     * @param jobAddTime the value for LOG_INFO.JOB_ADD_TIME
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public void setJobAddTime(Date jobAddTime) {
        this.jobAddTime = jobAddTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * LOG_INFO.JOB_NAME
     * 
     * @return the value of LOG_INFO.JOB_NAME
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * LOG_INFO.JOB_NAME
     * 
     * @param jobName the value for LOG_INFO.JOB_NAME
     * @ibatorgenerated Mon Mar 21 15:11:15 CST 2011
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
}
