package com.mitian.airad.model;

/**
 * SysConfig.java
 * 
 * @author baojun
 */
public class SysConfig {
    private Integer publish;// 0未发布1发布

    /**
     * @param publish the publish to set
     */
    public void setPublish(Integer publish) {
        this.publish = publish;
    }

    /**
     * @return the publish
     */
    public Integer getPublish() {
        return publish;
    }
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * SYS_CONFIG.SYS_CONFIG_ID
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    private Integer sysConfigId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * SYS_CONFIG.SYS_TYPE
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    private String sysType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * SYS_CONFIG.SYS_DESC
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    private String sysDesc;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * SYS_CONFIG.SYS_KEY
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    private String sysKey;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * SYS_CONFIG.SYS_VAL
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    private String sysVal;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
     * SYS_CONFIG.SYS_ORDER
     * 
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    private String sysOrder;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * SYS_CONFIG.SYS_CONFIG_ID
     * 
     * @return the value of SYS_CONFIG.SYS_CONFIG_ID
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public Integer getSysConfigId() {
        return sysConfigId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * SYS_CONFIG.SYS_CONFIG_ID
     * 
     * @param sysConfigId the value for SYS_CONFIG.SYS_CONFIG_ID
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public void setSysConfigId(Integer sysConfigId) {
        this.sysConfigId = sysConfigId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * SYS_CONFIG.SYS_TYPE
     * 
     * @return the value of SYS_CONFIG.SYS_TYPE
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public String getSysType() {
        return sysType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * SYS_CONFIG.SYS_TYPE
     * 
     * @param sysType the value for SYS_CONFIG.SYS_TYPE
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public void setSysType(String sysType) {
        this.sysType = sysType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * SYS_CONFIG.SYS_DESC
     * 
     * @return the value of SYS_CONFIG.SYS_DESC
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public String getSysDesc() {
        return sysDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * SYS_CONFIG.SYS_DESC
     * 
     * @param sysDesc the value for SYS_CONFIG.SYS_DESC
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public void setSysDesc(String sysDesc) {
        this.sysDesc = sysDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * SYS_CONFIG.SYS_KEY
     * 
     * @return the value of SYS_CONFIG.SYS_KEY
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public String getSysKey() {
        return sysKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * SYS_CONFIG.SYS_KEY
     * 
     * @param sysKey the value for SYS_CONFIG.SYS_KEY
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public void setSysKey(String sysKey) {
        this.sysKey = sysKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * SYS_CONFIG.SYS_VAL
     * 
     * @return the value of SYS_CONFIG.SYS_VAL
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public String getSysVal() {
        return sysVal;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * SYS_CONFIG.SYS_VAL
     * 
     * @param sysVal the value for SYS_CONFIG.SYS_VAL
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public void setSysVal(String sysVal) {
        this.sysVal = sysVal;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column
     * SYS_CONFIG.SYS_ORDER
     * 
     * @return the value of SYS_CONFIG.SYS_ORDER
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public String getSysOrder() {
        return sysOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column
     * SYS_CONFIG.SYS_ORDER
     * 
     * @param sysOrder the value for SYS_CONFIG.SYS_ORDER
     * @ibatorgenerated Tue Mar 01 19:02:36 CST 2011
     */
    public void setSysOrder(String sysOrder) {
        this.sysOrder = sysOrder;
    }
}
